// Generated e2e runtime test — java/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.*;
import java.util.List;
import java.util.UUID;
import com.example.db.queries.Queries;
import com.example.db.models.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private static final ObjectMapper GEN_MAPPER = new ObjectMapper();
    private static final String URL =
        System.getenv().getOrDefault("DATABASE_URL",
            "jdbc:postgresql://localhost:15432/sqltgen_e2e");
    private static final String USER = "sqltgen";
    private static final String PASS = "sqltgen";

    private Connection conn;
    private String dbName;

    @BeforeEach
    void setUp() throws Exception {
        dbName = "test_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection admin = DriverManager.getConnection(URL, USER, PASS);
             Statement s = admin.createStatement()) {
            s.execute("CREATE DATABASE \"" + dbName + "\"");
        }
        String baseUrl = URL.replaceFirst("/[^/]*$", "/" + dbName);
        conn = DriverManager.getConnection(baseUrl, USER, PASS);
        conn.setAutoCommit(true);
        var ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/array_overrides/postgresql/schema.sql"));
        try (Statement s = conn.createStatement()) {
            for (String stmt : ddl.split(";")) {
                String t = stmt.strip();
                if (!t.isEmpty()) s.execute(t);
            }
        }
    }

    @AfterEach
    void tearDown() throws Exception {
        if (conn != null) conn.close();
        try (Connection admin = DriverManager.getConnection(URL, USER, PASS);
             Statement s = admin.createStatement()) {
            s.execute("DROP DATABASE IF EXISTS \"" + dbName + "\"");
        }
    }

    private static JsonNode genJson(String raw) {
        try {
            return GEN_MAPPER.readTree(raw);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    void testInsertAndGetRecordGen() throws Exception {
        var uid1 = UUID.randomUUID();
        var uid2 = UUID.randomUUID();
        Queries.insertRecord(conn, "test", List.of(LocalDateTime.of(2024, 1, 15, 10, 30, 0), LocalDateTime.of(2024, 6, 1, 12, 0, 0)), List.of(uid1, uid2));
        var row = Queries.getRecord(conn, 1L).orElseThrow();
        assertNotNull(row);
        assertEquals("test", row.label());
        assertEquals(2, row.timestamps().size());
        assertEquals(LocalDateTime.of(2024, 1, 15, 10, 30, 0), row.timestamps().get(0));
        assertEquals(LocalDateTime.of(2024, 6, 1, 12, 0, 0), row.timestamps().get(1));
        assertEquals(2, row.uuids().size());
        assertEquals(uid1, row.uuids().get(0));
        assertEquals(uid2, row.uuids().get(1));
    }

    @Test
    void testGetRecordNotFoundGen() throws Exception {
        var result = Queries.getRecord(conn, 999L);
        assertTrue(result.isEmpty());
    }

    @Test
    void testEmptyArraysGen() throws Exception {
        Queries.insertRecord(conn, "empty", List.of(), List.of());
        var row = Queries.getRecord(conn, 1L).orElseThrow();
        assertNotNull(row);
        assertEquals(0, row.timestamps().size());
        assertEquals(0, row.uuids().size());
    }

}
