// Generated e2e runtime test — rust/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
use std::str::FromStr;
use e2e_array_overrides_rust_postgresql::db::queries::queries;
use sqlx::postgres::PgPoolOptions;
use sqlx::PgPool;
#[allow(unused_imports)]
use time::macros::{date, datetime, time};

// ─── test setup ───────────────────────────────────────────────────────────────

async fn gen_setup_db() -> (PgPool, String) {
    let url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e".into());
    let bootstrap = PgPool::connect(&url).await.unwrap();
    let db_name = format!("test_{}", uuid::Uuid::new_v4().simple());
    sqlx::query(&format!("CREATE DATABASE \"{db_name}\""))
        .execute(&bootstrap)
        .await
        .unwrap();
    bootstrap.close().await;
    let base = url.rsplit_once('/').map(|(b, _)| b).unwrap_or(&url);
    let pool = PgPoolOptions::new()
        .connect(&format!("{base}/{db_name}"))
        .await
        .unwrap();
    let ddl = include_str!("../../../../../fixtures/array_overrides/postgresql/schema.sql");
    for stmt in ddl.split(';').map(str::trim).filter(|s| !s.is_empty()) {
        sqlx::query(stmt).execute(&pool).await.unwrap();
    }
    (pool, db_name)
}

async fn gen_teardown(pool: PgPool, db_name: String) {
    pool.close().await;
    let url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e".into());
    let admin = PgPool::connect(&url).await.unwrap();
    let _ = sqlx::query(&format!(
        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '{db_name}' AND pid <> pg_backend_pid()"
    ))
    .execute(&admin)
    .await;
    let _ = sqlx::query(&format!("DROP DATABASE IF EXISTS \"{db_name}\""))
        .execute(&admin)
        .await;
    admin.close().await;
}

#[allow(dead_code)]
fn gen_assert_json_str(got: &str, want: serde_json::Value) {
    let got: serde_json::Value = serde_json::from_str(got).unwrap();
    assert_eq!(got, want);
}

// ─── scenarios ────────────────────────────────────────────────────────────────

// ─── :one queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_insert_and_get_record_gen() {
    let (pool, db_name) = gen_setup_db().await;
    queries::insert_record(&pool, "test".to_string(), vec![datetime!(2024-01-15 10:30:00), datetime!(2024-06-01 12:00:00)], vec![uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440001").unwrap(), uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440002").unwrap()]).await.unwrap();
    let row = queries::get_record(&pool, 1).await.unwrap();
    let row = row.expect("expected non-nil row");
    assert_eq!(row.label, "test".to_string());
    assert_eq!(row.timestamps.len(), 2);
    assert_eq!(row.timestamps[0], datetime!(2024-01-15 10:30:00));
    assert_eq!(row.timestamps[1], datetime!(2024-06-01 12:00:00));
    assert_eq!(row.uuids.len(), 2);
    assert_eq!(row.uuids[0], uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440001").unwrap());
    assert_eq!(row.uuids[1], uuid::Uuid::parse_str("550e8400-e29b-41d4-a716-446655440002").unwrap());
    gen_teardown(pool, db_name).await;
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_get_record_not_found_gen() {
    let (pool, db_name) = gen_setup_db().await;
    let result = queries::get_record(&pool, 999).await.unwrap();
    assert!(result.is_none());
    gen_teardown(pool, db_name).await;
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_empty_arrays_gen() {
    let (pool, db_name) = gen_setup_db().await;
    queries::insert_record(&pool, "empty".to_string(), vec![], vec![]).await.unwrap();
    let row = queries::get_record(&pool, 1).await.unwrap();
    let row = row.expect("expected non-nil row");
    assert_eq!(row.timestamps.len(), 0);
    assert_eq!(row.uuids.len(), 0);
    gen_teardown(pool, db_name).await;
}

