use super::*;

// ─── generate: table struct file ─────────────────────────────────────────

#[test]
fn test_generate_table_struct() {
    let schema = Schema::with_tables(vec![user_table()]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "user.hpp");
    assert!(src.contains("struct User {"), "should emit PascalCase struct name");
    assert!(src.contains("std::int64_t id;"), "non-nullable bigint → int64_t");
    assert!(src.contains("std::string name;"), "non-nullable text → string");
    assert!(src.contains("std::optional<std::string> bio;"), "nullable text → optional<string>");
}

#[test]
fn test_generate_pragma_once_and_header_comment() {
    let schema = Schema::with_tables(vec![user_table()]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "user.hpp");
    assert!(src.starts_with("#pragma once\n"), "header should start with #pragma once");
    assert!(src.contains("// Generated by sqltgen. Do not edit."), "should have generated comment");
}

// ─── generate: includes ──────────────────────────────────────────────────

#[test]
fn test_generate_includes_for_user_table() {
    let schema = Schema::with_tables(vec![user_table()]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "user.hpp");
    // user table has BigInt (cstdint), Text (string), nullable (optional)
    assert!(src.contains("#include <cstdint>"), "bigint needs cstdint");
    assert!(src.contains("#include <string>"), "text needs string");
    assert!(src.contains("#include <optional>"), "nullable needs optional");
}

#[test]
fn test_generate_includes_chrono_for_temporal() {
    let table = Table {
        name: "event".to_string(),
        kind: TableKind::Table,
        columns: vec![
            Column { name: "id".to_string(), sql_type: SqlType::Integer, nullable: false, is_primary_key: true },
            Column { name: "created_at".to_string(), sql_type: SqlType::Timestamp, nullable: false, is_primary_key: false },
        ],
    };
    let schema = Schema::with_tables(vec![table]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "event.hpp");
    assert!(src.contains("#include <chrono>"), "timestamp needs chrono");
    assert!(src.contains("#include <cstdint>"), "integer needs cstdint");
}

#[test]
fn test_generate_includes_vector_for_bytes() {
    let table = Table {
        name: "blob".to_string(),
        kind: TableKind::Table,
        columns: vec![
            Column { name: "data".to_string(), sql_type: SqlType::Bytes, nullable: false, is_primary_key: false },
        ],
    };
    let schema = Schema::with_tables(vec![table]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "blob.hpp");
    assert!(src.contains("#include <cstdint>"), "bytes needs cstdint");
    assert!(src.contains("#include <vector>"), "bytes needs vector");
}

#[test]
fn test_generate_no_includes_for_bool_only() {
    let table = Table {
        name: "flag".to_string(),
        kind: TableKind::Table,
        columns: vec![
            Column { name: "active".to_string(), sql_type: SqlType::Boolean, nullable: false, is_primary_key: false },
        ],
    };
    let schema = Schema::with_tables(vec![table]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "flag.hpp");
    // bool needs no includes
    assert!(!src.contains("#include"), "bool-only table should have no includes");
    // Struct should follow directly after the header comment
    assert!(src.contains("struct Flag {"));
    assert!(src.contains("bool active;"));
}

// ─── generate: namespace ─────────────────────────────────────────────────

#[test]
fn test_generate_no_namespace_when_package_empty() {
    let schema = Schema::with_tables(vec![user_table()]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "user.hpp");
    assert!(!src.contains("namespace"), "empty package should not emit namespace");
}

#[test]
fn test_generate_namespace_when_package_set() {
    let schema = Schema::with_tables(vec![user_table()]);
    let config = OutputConfig { out: "out".to_string(), package: "mydb".to_string(), list_params: None, ..Default::default() };
    let files = pg().generate(&schema, &[], &config).unwrap();
    let src = get_file(&files, "user.hpp");
    assert!(src.contains("namespace mydb {"), "should open namespace from package");
    assert!(src.contains("} // namespace mydb"), "should close namespace with comment");
}

// ─── generate: multiple tables ───────────────────────────────────────────

#[test]
fn test_generate_one_file_per_table() {
    let schema = Schema::with_tables(vec![
        user_table(),
        Table {
            name: "post".to_string(),
            kind: TableKind::Table,
            columns: vec![
                Column { name: "id".to_string(), sql_type: SqlType::Integer, nullable: false, is_primary_key: true },
                Column { name: "title".to_string(), sql_type: SqlType::Text, nullable: false, is_primary_key: false },
            ],
        },
    ]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    assert_eq!(files.len(), 2);
    let _ = get_file(&files, "user.hpp");
    let post_src = get_file(&files, "post.hpp");
    assert!(post_src.contains("struct Post {"));
    assert!(post_src.contains("std::int32_t id;"));
    assert!(post_src.contains("std::string title;"));
}

// ─── generate: output path ───────────────────────────────────────────────

#[test]
fn test_generate_file_path_under_out_dir() {
    let schema = Schema::with_tables(vec![user_table()]);
    let config = OutputConfig { out: "generated/db".to_string(), package: String::new(), list_params: None, ..Default::default() };
    let files = pg().generate(&schema, &[], &config).unwrap();
    assert_eq!(files.len(), 1);
    assert_eq!(files[0].path.to_str().unwrap(), "generated/db/user.hpp");
}

// ─── generate: empty schema ──────────────────────────────────────────────

#[test]
fn test_generate_empty_schema_produces_no_files() {
    let schema = Schema::default();
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    assert!(files.is_empty());
}

// ─── generate: includes sorted (BTreeSet) ────────────────────────────────

#[test]
fn test_generate_includes_are_sorted() {
    // A table that needs <cstdint>, <optional>, <string> — check they appear in order.
    let schema = Schema::with_tables(vec![user_table()]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "user.hpp");
    let cstdint_pos = src.find("#include <cstdint>").unwrap();
    let optional_pos = src.find("#include <optional>").unwrap();
    let string_pos = src.find("#include <string>").unwrap();
    assert!(cstdint_pos < optional_pos, "<cstdint> should come before <optional>");
    assert!(optional_pos < string_pos, "<optional> should come before <string>");
}

// ─── generate: array includes ────────────────────────────────────────────

#[test]
fn test_generate_includes_vector_for_array_column() {
    let table = Table {
        name: "tag_list".to_string(),
        kind: TableKind::Table,
        columns: vec![
            Column { name: "tags".to_string(), sql_type: SqlType::Array(Box::new(SqlType::Text)), nullable: false, is_primary_key: false },
        ],
    };
    let schema = Schema::with_tables(vec![table]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    let src = get_file(&files, "tag_list.hpp");
    assert!(src.contains("#include <string>"), "array of text needs string");
    assert!(src.contains("#include <vector>"), "array needs vector");
    assert!(src.contains("std::vector<std::string> tags;"));
}
