use super::*;
use crate::backend::Codegen;
use crate::ir::{NativeListBind, Parameter, Query, ResultColumn};

// ─── .cpp file structure ─────────────────────────────────────────────────

#[test]
fn test_cpp_file_is_generated_alongside_hpp() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let _ = get_file(&files, "queries.hpp");
    let _ = get_file(&files, "queries.cpp");
}

#[test]
fn test_cpp_file_includes_own_header() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("#include \"queries.hpp\""), "cpp file should include its own header");
}

#[test]
fn test_cpp_file_has_generated_comment() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("// Generated by sqltgen. Do not edit."));
}

#[test]
fn test_cpp_file_namespace() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let config = OutputConfig { out: "out".to_string(), package: "mydb".to_string(), list_params: None, ..Default::default() };
    let files = pg().generate(&schema, &[query], &config).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("namespace mydb {"), "cpp file should open namespace");
    assert!(src.contains("} // namespace mydb"), "cpp file should close namespace");
}

#[test]
fn test_cpp_file_no_namespace_when_empty() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(!src.contains("namespace"));
}

// ─── function definition shape ───────────────────────────────────────────

#[test]
fn test_cpp_function_def_has_opening_brace() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("void delete_user(pqxx::connection& db, const std::int64_t& id) {"), "function def should have opening brace, not semicolon");
}

#[test]
fn test_cpp_function_def_has_closing_brace() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("}"), "function def should have closing brace");
}

// ─── pqxx :exec body ────────────────────────────────────────────────────

#[test]
fn test_pqxx_exec_body_with_params() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("pqxx::work txn(db);"), "should create transaction");
    assert!(src.contains("txn.exec(SQL_DELETE_USER, pqxx::params{id}).no_rows();"), "should exec with params and assert no rows");
    assert!(src.contains("txn.commit();"), "should commit transaction");
}

#[test]
fn test_pqxx_exec_body_no_params() {
    let schema = Schema::default();
    let query = Query::exec("DeleteAll", "DELETE FROM user", vec![]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("txn.exec(SQL_DELETE_ALL).no_rows();"), "no params should use exec with no_rows assertion");
}

#[test]
fn test_pqxx_exec_body_multiple_params() {
    let schema = Schema::default();
    let query = Query::exec(
        "UpdateUser",
        "UPDATE user SET name = $1 WHERE id = $2",
        vec![Parameter::scalar(1, "name", SqlType::Text, false), Parameter::scalar(2, "id", SqlType::BigInt, false)],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("txn.exec(SQL_UPDATE_USER, pqxx::params{name, id}).no_rows();"), "should pass all params in pqxx::params");
}

// ─── pqxx :execrows body ────────────────────────────────────────────────

#[test]
fn test_pqxx_execrows_body() {
    let schema = Schema::default();
    let query = Query::exec_rows("DeleteInactive", "DELETE FROM user WHERE active = $1", vec![Parameter::scalar(1, "active", SqlType::Boolean, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("auto affected = txn.exec(SQL_DELETE_INACTIVE, pqxx::params{active}).affected_rows();"), "should capture affected_rows from exec");
    assert!(src.contains("txn.commit();"), "should commit");
    assert!(src.contains("return static_cast<std::int64_t>(affected);"), "should return affected rows as int64");
}

#[test]
fn test_pqxx_execrows_body_no_params() {
    let schema = Schema::default();
    let query = Query::exec_rows("DeleteAll", "DELETE FROM user", vec![]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("auto affected = txn.exec(SQL_DELETE_ALL).affected_rows();"), "no params should use exec");
    assert!(src.contains("return static_cast<std::int64_t>(affected);"));
}

// ─── pqxx :one body ─────────────────────────────────────────────────────

#[test]
fn test_pqxx_one_body_returns_nullopt_on_empty() {
    let schema = Schema::with_tables(vec![user_table()]);
    let query = Query::one(
        "GetUser",
        "SELECT id, name, bio FROM user WHERE id = $1",
        vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("if (!opt) return std::nullopt;"), "should return nullopt when query01 returns empty");
}

#[test]
fn test_pqxx_one_body_constructs_row_from_query01() {
    let schema = Schema::with_tables(vec![user_table()]);
    let query = Query::one(
        "GetUser",
        "SELECT id, name, bio FROM user WHERE id = $1",
        vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("auto opt = txn.query01<std::int64_t, std::string, std::optional<std::string>>(SQL_GET_USER, pqxx::params{id});"));
    assert!(src.contains("auto& [id_, name_, bio_] = *opt;"));
    assert!(src.contains("return User{std::move(id_), std::move(name_), std::move(bio_)};"));
}

#[test]
fn test_pqxx_one_body_inline_row_struct() {
    let schema = Schema::with_tables(vec![user_table()]);
    let query = Query::one(
        "GetUserName",
        "SELECT name FROM user WHERE id = $1",
        vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
        vec![ResultColumn::not_nullable("name", SqlType::Text)],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("return GetUserNameRow{std::move(name_)};"), "should use inline row struct name");
}

// ─── pqxx :many body ────────────────────────────────────────────────────

#[test]
fn test_pqxx_many_body_creates_vector() {
    let schema = Schema::with_tables(vec![user_table()]);
    let query = Query::many(
        "ListUsers",
        "SELECT id, name, bio FROM user",
        vec![],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(src.contains("std::vector<User> rows;"), "should create vector of row type");
}

#[test]
fn test_pqxx_many_body_loops_and_constructs_rows() {
    let schema = Schema::with_tables(vec![user_table()]);
    let query = Query::many(
        "ListUsers",
        "SELECT id, name, bio FROM user",
        vec![],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(
        src.contains("for (auto [id_, name_, bio_] : txn.query<std::int64_t, std::string, std::optional<std::string>>(SQL_LIST_USERS)) {"),
        "should loop over typed query results"
    );
    assert!(src.contains("rows.push_back(User{std::move(id_), std::move(name_), std::move(bio_)});"), "should push constructed row");
    assert!(src.contains("return rows;"), "should return the vector");
}

#[test]
fn test_pqxx_many_body_with_params() {
    let schema = Schema::with_tables(vec![user_table()]);
    let query = Query::many(
        "FindUsers",
        "SELECT id, name, bio FROM user WHERE name = $1",
        vec![Parameter::scalar(1, "name", SqlType::Text, false)],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.cpp");
    assert!(
        src.contains("txn.query<std::int64_t, std::string, std::optional<std::string>>(SQL_FIND_USERS, pqxx::params{name})"),
        "should use typed query with params"
    );
}

// ─── querier class ───────────────────────────────────────────────────────

#[test]
fn test_querier_class_declaration() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("class Querier {"), "should emit Querier class");
    assert!(src.contains("pqxx::connection& db_;"), "should have db_ member");
    assert!(src.contains("explicit Querier(pqxx::connection& db) : db_(db) {}"), "should have constructor");
}

#[test]
fn test_querier_method_declarations() {
    let schema = Schema::default();
    let query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("void delete_user(const std::int64_t& id);"), "querier method should omit db param");
}

#[test]
fn test_querier_method_no_params() {
    let schema = Schema::default();
    let query = Query::exec("DeleteAll", "DELETE FROM user", vec![]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("void delete_all();"), "querier method with no params should have empty parens");
}

#[test]
fn test_querier_method_return_types() {
    let schema = Schema::with_tables(vec![user_table()]);
    let q1 = Query::exec_rows("DeleteInactive", "DELETE FROM user WHERE active = $1", vec![Parameter::scalar(1, "active", SqlType::Boolean, false)]);
    let q2 = Query::one(
        "GetUser",
        "SELECT id, name, bio FROM user WHERE id = $1",
        vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let q3 = Query::many(
        "ListUsers",
        "SELECT id, name, bio FROM user",
        vec![],
        vec![
            ResultColumn::not_nullable("id", SqlType::BigInt),
            ResultColumn::not_nullable("name", SqlType::Text),
            ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
        ],
    );
    let files = pg().generate(&schema, &[q1, q2, q3], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("std::int64_t delete_inactive(const bool& active);"), "execrows querier method");
    assert!(src.contains("std::optional<User> get_user(const std::int64_t& id);"), "one querier method");
    assert!(src.contains("std::vector<User> list_users();"), "many querier method");
}

#[test]
fn test_querier_named_group() {
    let schema = Schema::default();
    let mut query = Query::exec("DeleteUser", "DELETE FROM user WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    query.group = "users".to_string();
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "users.hpp");
    assert!(src.contains("class UsersQuerier {"), "named group should produce UsersQuerier");
}

#[test]
fn test_querier_not_emitted_when_no_queries() {
    let schema = Schema::with_tables(vec![user_table()]);
    let files = pg().generate(&schema, &[], &cfg()).unwrap();
    for f in &files {
        assert!(!f.content.contains("class Querier"), "no Querier class when there are no queries");
    }
}

// ─── list params in signatures ───────────────────────────────────────────

#[test]
fn test_list_param_in_function_signature() {
    let schema = Schema::default();
    let query = Query::many(
        "GetByIds",
        "SELECT id FROM t WHERE id IN ($1)",
        vec![Parameter::list(1, "ids", SqlType::BigInt, false)],
        vec![ResultColumn::not_nullable("id", SqlType::BigInt)],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("const std::vector<std::int64_t>& ids"), "list param should use std::vector");
}

#[test]
fn test_list_param_in_querier_method() {
    let schema = Schema::default();
    let query = Query::many(
        "GetByIds",
        "SELECT id FROM t WHERE id IN ($1)",
        vec![Parameter::list(1, "ids", SqlType::BigInt, false)],
        vec![ResultColumn::not_nullable("id", SqlType::BigInt)],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("const std::vector<std::int64_t>& ids);"), "querier method should also use std::vector for list param");
}

#[test]
fn test_list_param_includes_vector() {
    let schema = Schema::default();
    let query = Query::exec("DeleteByIds", "DELETE FROM t WHERE id IN ($1)", vec![Parameter::list(1, "ids", SqlType::BigInt, false)]);
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("#include <vector>"), "list param should trigger vector include");
}

// ─── list params native SQL ──────────────────────────────────────────────

#[test]
fn test_list_param_native_sql_in_constant() {
    let schema = Schema::default();
    let query = Query::many(
        "GetByIds",
        "SELECT id FROM t WHERE id IN ($1)",
        vec![Parameter::list(1, "ids", SqlType::BigInt, false).with_native_list("SELECT id FROM t WHERE id = ANY($1)", NativeListBind::Array)],
        vec![ResultColumn::not_nullable("id", SqlType::BigInt)],
    );
    let files = pg().generate(&schema, &[query], &cfg()).unwrap();
    let src = get_file(&files, "queries.hpp");
    assert!(src.contains("= ANY($1)"), "SQL constant should use native list SQL");
    assert!(!src.contains("IN ($1)"), "original IN clause should be replaced");
}

// ─── query grouping ─────────────────────────────────────────────────────

#[test]
fn test_grouping_produces_separate_file_pairs() {
    let schema = Schema::default();
    let mut q1 = Query::exec("DeleteUser", "DELETE FROM users WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    q1.group = "users".to_string();
    let mut q2 = Query::exec("DeletePost", "DELETE FROM posts WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    q2.group = "posts".to_string();
    let files = pg().generate(&schema, &[q1, q2], &cfg()).unwrap();
    let _ = get_file(&files, "users.hpp");
    let _ = get_file(&files, "users.cpp");
    let _ = get_file(&files, "posts.hpp");
    let _ = get_file(&files, "posts.cpp");
}

#[test]
fn test_grouping_routes_queries_to_correct_files() {
    let schema = Schema::default();
    let mut q1 = Query::exec("DeleteUser", "DELETE FROM users WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    q1.group = "users".to_string();
    let mut q2 = Query::exec("DeletePost", "DELETE FROM posts WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    q2.group = "posts".to_string();
    let files = pg().generate(&schema, &[q1, q2], &cfg()).unwrap();
    let users_hpp = get_file(&files, "users.hpp");
    let posts_hpp = get_file(&files, "posts.hpp");
    assert!(users_hpp.contains("delete_user"), "users.hpp should contain delete_user");
    assert!(!users_hpp.contains("delete_post"), "users.hpp should not contain delete_post");
    assert!(posts_hpp.contains("delete_post"), "posts.hpp should contain delete_post");
    assert!(!posts_hpp.contains("delete_user"), "posts.hpp should not contain delete_user");
}

#[test]
fn test_grouping_cpp_includes_correct_header() {
    let schema = Schema::default();
    let mut q1 = Query::exec("DeleteUser", "DELETE FROM users WHERE id = $1", vec![Parameter::scalar(1, "id", SqlType::BigInt, false)]);
    q1.group = "users".to_string();
    let files = pg().generate(&schema, &[q1], &cfg()).unwrap();
    let src = get_file(&files, "users.cpp");
    assert!(src.contains("#include \"users.hpp\""), "cpp file should include its group header");
}
