// Generated e2e runtime test — kotlin/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.example.db.models.*
import com.example.db.queries.Queries
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.UUID

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private val GEN_MAPPER = ObjectMapper()
    private val url = System.getenv()
        .getOrDefault("DATABASE_URL", "jdbc:postgresql://localhost:15432/sqltgen_e2e")

    private lateinit var conn: Connection
    private lateinit var dbName: String

    @BeforeEach
    fun setUp() {
        dbName = "test_" + UUID.randomUUID().toString().replace("-", "")
        DriverManager.getConnection(url, "sqltgen", "sqltgen").use { admin ->
            admin.createStatement().use { s ->
                s.execute("""CREATE DATABASE "$dbName"""")
            }
        }
        val baseUrl = url.replaceFirst(Regex("/[^/]*$"), "/$dbName")
        conn = DriverManager.getConnection(baseUrl, "sqltgen", "sqltgen")
        conn.autoCommit = true
        val ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/bookstore/postgresql/schema.sql"))
        conn.createStatement().use { s ->
            for (stmt in ddl.split(";")) {
                val t = stmt.trim()
                if (t.isNotEmpty()) s.execute(t)
            }
        }
    }

    @AfterEach
    fun tearDown() {
        conn.close()
        DriverManager.getConnection(url, "sqltgen", "sqltgen").use { admin ->
            admin.createStatement().use { s ->
                s.execute("""DROP DATABASE IF EXISTS "$dbName"""")
            }
        }
    }

    private fun genJson(raw: String): JsonNode = GEN_MAPPER.readTree(raw)

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    fun testAddSaleItemGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createCustomer(conn, "Customer", "c@example.com")
        Queries.createBook(conn, 1L, "Book", "sci-fi", java.math.BigDecimal("10.0"), null)
        Queries.createSale(conn, 1L)
        Queries.addSaleItem(conn, 1L, 1L, 3, java.math.BigDecimal("10.0"))
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    fun testDeleteBookByIdGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1L, "Book1", "sci-fi", java.math.BigDecimal("10.0"), null)
        val affected = Queries.deleteBookById(conn, 1L)
        assertEquals(1L, affected)
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    fun testListAuthorsGen() {
        Queries.createAuthor(conn, "Asimov", null, 1920)
        Queries.createAuthor(conn, "Herbert", null, 1920)
        val authors = Queries.listAuthors(conn)
        assertEquals(2, authors.size)
        assertEquals("Asimov", authors[0].name)
        assertEquals("Herbert", authors[1].name)
    }

    @Test
    fun testListBooksByGenreGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1L, "SciFi1", "sci-fi", java.math.BigDecimal("9.99"), null)
        Queries.createBook(conn, 1L, "Fantasy1", "fantasy", java.math.BigDecimal("11.99"), null)
        val books = Queries.listBooksByGenre(conn, "sci-fi")
        assertEquals(1, books.size)
        assertEquals("SciFi1", books[0].title)
    }

    @Test
    fun testListBooksByGenreOrAllGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1L, "B1", "sci-fi", java.math.BigDecimal("9.99"), null)
        Queries.createBook(conn, 1L, "B2", "fantasy", java.math.BigDecimal("9.99"), null)
        val all_books = Queries.listBooksByGenreOrAll(conn, null)
        assertEquals(2, all_books.size)
        val scifi = Queries.listBooksByGenreOrAll(conn, "sci-fi")
        assertEquals(1, scifi.size)
    }

    @Test
    fun testListBooksWithAuthorJoinGen() {
        Queries.createAuthor(conn, "Author A", "Bio A", 1920)
        Queries.createBook(conn, 1L, "Book A", "sci-fi", java.math.BigDecimal("9.99"), null)
        val rows = Queries.listBooksWithAuthor(conn)
        assertEquals(1, rows.size)
        assertEquals("Author A", rows[0].authorName)
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    fun testGetAuthorGen() {
        Queries.createAuthor(conn, "Asimov", "Sci-fi master", 1920)
        val author = Queries.getAuthor(conn, 1L)!!
        assertNotNull(author)
        assertEquals("Asimov", author.name)
        assertEquals("Sci-fi master", author.bio)
        assertEquals(1920, author.birthYear)
    }

    @Test
    fun testGetAuthorNotFoundGen() {
        val result = Queries.getAuthor(conn, 999L)
        assertNull(result)
    }

    @Test
    fun testGetBookGen() {
        Queries.createAuthor(conn, "Herbert", null, 1920)
        Queries.createBook(conn, 1L, "Dune", "sci-fi", java.math.BigDecimal("12.99"), LocalDate.of(1965, 6, 1))
        val book = Queries.getBook(conn, 1L)!!
        assertNotNull(book)
        assertEquals("Dune", book.title)
        assertEquals("sci-fi", book.genre)
    }

    // ─── aggregates ────────────────────────────────────────────────────────────

    @Test
    fun testCountBooksByGenreGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1L, "B1", "sci-fi", java.math.BigDecimal("10.0"), null)
        Queries.createBook(conn, 1L, "B2", "sci-fi", java.math.BigDecimal("10.0"), null)
        Queries.createBook(conn, 1L, "B3", "fantasy", java.math.BigDecimal("10.0"), null)
        val counts = Queries.countBooksByGenre(conn)
        assertEquals(2, counts.size)
    }

    // ─── filtering ────────────────────────────────────────────────────────────

    @Test
    fun testGetBooksByPriceRangeGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1L, "Cheap", "sci-fi", java.math.BigDecimal("5.99"), null)
        Queries.createBook(conn, 1L, "Mid", "sci-fi", java.math.BigDecimal("10.5"), null)
        Queries.createBook(conn, 1L, "Expensive", "sci-fi", java.math.BigDecimal("20.99"), null)
        val books = Queries.getBooksByPriceRange(conn, java.math.BigDecimal("7.0"), java.math.BigDecimal("15.0"))
        assertEquals(1, books.size)
        assertEquals("Mid", books[0].title)
    }

    @Test
    fun testSearchBooksByTitleGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1L, "Foundation", "sci-fi", java.math.BigDecimal("9.99"), null)
        Queries.createBook(conn, 1L, "Dune", "sci-fi", java.math.BigDecimal("12.99"), null)
        val books = Queries.searchBooksByTitle(conn, "%ound%")
        assertEquals(1, books.size)
        assertEquals("Foundation", books[0].title)
    }

    // ─── NULL handling ────────────────────────────────────────────────────────────

    @Test
    fun testAuthorsWithNullBioGen() {
        Queries.createAuthor(conn, "WithBio", "Has bio", 1900)
        Queries.createAuthor(conn, "NoBio", null, 1900)
        val authors = Queries.getAuthorsWithNullBio(conn)
        assertEquals(1, authors.size)
        assertEquals("NoBio", authors[0].name)
    }

    @Test
    fun testAuthorsWithBioGen() {
        Queries.createAuthor(conn, "WithBio", "Bio", 1900)
        Queries.createAuthor(conn, "NoBio", null, 1900)
        val authors = Queries.getAuthorsWithBio(conn)
        assertEquals(1, authors.size)
        assertEquals("WithBio", authors[0].name)
    }

}
