"""Generated e2e runtime test — python/mysql. DO NOT EDIT.

Auto-generated by scripts/e2e_testgen from test_spec.yaml.
"""

import datetime
import json
import os
import pathlib
import uuid

import mysql.connector
import pytest

from gen.queries import queries
from gen.models import *

_FIXTURES = pathlib.Path(__file__).parent / ".."
_DB_HOST = os.environ.get("MYSQL_HOST", "127.0.0.1")
_DB_PORT = int(os.environ.get("MYSQL_PORT", "13306"))
_DB_USER = os.environ.get("MYSQL_USER", "sqltgen")
_DB_PASS = os.environ.get("MYSQL_PASS", "sqltgen")
_DB_ROOT_USER = os.environ.get("MYSQL_ROOT_USER", "root")
_DB_ROOT_PASS = os.environ.get("MYSQL_ROOT_PASS", "sqltgen")
_DB_NAME = os.environ.get("MYSQL_DB", "sqltgen_e2e")


@pytest.fixture()
def conn():
    """Yield a MySQL connection with an isolated database; drop it on teardown."""
    db_name = "test_" + uuid.uuid4().hex
    schema_sql = (_FIXTURES / "schema.sql").read_text()

    # Create isolated database.
    admin = mysql.connector.connect(
        host=_DB_HOST, port=_DB_PORT, user=_DB_ROOT_USER, password=_DB_ROOT_PASS, database=_DB_NAME
    )
    cur = admin.cursor()
    cur.execute(f"CREATE DATABASE `{db_name}`")
    cur.execute(f"GRANT ALL ON `{db_name}`.* TO '{_DB_USER}'@'%'")
    cur.close()
    admin.close()

    c = mysql.connector.connect(
        host=_DB_HOST, port=_DB_PORT, user=_DB_USER, password=_DB_PASS, database=db_name
    )
    cur = c.cursor()
    for stmt in schema_sql.split(";"):
        stmt = stmt.strip()
        if stmt:
            cur.execute(stmt)
    c.commit()
    cur.close()
    yield c
    c.close()

    # Drop the test database.
    admin = mysql.connector.connect(
        host=_DB_HOST, port=_DB_PORT, user=_DB_ROOT_USER, password=_DB_ROOT_PASS, database=_DB_NAME
    )
    cur = admin.cursor()
    cur.execute(f"DROP DATABASE IF EXISTS `{db_name}`")
    cur.close()
    admin.close()


def test_get_author(conn):
    queries.create_author(conn, 'Asimov', 'Sci-fi master', 1920)
    author = queries.get_author(conn, 1)
    assert author is not None
    assert author.name == 'Asimov'
    assert author.bio == 'Sci-fi master'
    assert author.birth_year == 1920


def test_get_author_not_found(conn):
    result = queries.get_author(conn, 999)
    assert result is None


def test_get_book(conn):
    queries.create_author(conn, 'Herbert', None, 1920)
    queries.create_book(conn, 1, 'Dune', 'sci-fi', 12.99, datetime.date(1965, 6, 1))
    book = queries.get_book(conn, 1)
    assert book is not None
    assert book.title == 'Dune'
    assert book.genre == 'sci-fi'


def test_list_authors(conn):
    queries.create_author(conn, 'Asimov', None, 1920)
    queries.create_author(conn, 'Herbert', None, 1920)
    authors = queries.list_authors(conn)
    assert len(authors) == 2
    assert authors[0].name == 'Asimov'
    assert authors[1].name == 'Herbert'


def test_list_books_by_genre(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_book(conn, 1, 'SciFi1', 'sci-fi', 9.99, None)
    queries.create_book(conn, 1, 'Fantasy1', 'fantasy', 11.99, None)
    books = queries.list_books_by_genre(conn, 'sci-fi')
    assert len(books) == 1
    assert books[0].title == 'SciFi1'


def test_list_books_by_genre_or_all(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_book(conn, 1, 'B1', 'sci-fi', 9.99, None)
    queries.create_book(conn, 1, 'B2', 'fantasy', 9.99, None)
    all_books = queries.list_books_by_genre_or_all(conn, None)
    assert len(all_books) == 2
    scifi = queries.list_books_by_genre_or_all(conn, 'sci-fi')
    assert len(scifi) == 1


def test_list_books_with_author_join(conn):
    queries.create_author(conn, 'Author A', 'Bio A', 1920)
    queries.create_book(conn, 1, 'Book A', 'sci-fi', 9.99, None)
    rows = queries.list_books_with_author(conn)
    assert len(rows) == 1
    assert rows[0].author_name == 'Author A'


def test_authors_with_null_bio(conn):
    queries.create_author(conn, 'WithBio', 'Has bio', 1900)
    queries.create_author(conn, 'NoBio', None, 1900)
    authors = queries.get_authors_with_null_bio(conn)
    assert len(authors) == 1
    assert authors[0].name == 'NoBio'


def test_authors_with_bio(conn):
    queries.create_author(conn, 'WithBio', 'Bio', 1900)
    queries.create_author(conn, 'NoBio', None, 1900)
    authors = queries.get_authors_with_bio(conn)
    assert len(authors) == 1
    assert authors[0].name == 'WithBio'


def test_add_sale_item(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_customer(conn, 'Customer', 'c@example.com')
    queries.create_book(conn, 1, 'Book', 'sci-fi', 10.0, None)
    queries.create_sale(conn, 1)
    queries.add_sale_item(conn, 1, 1, 3, 10.0)


def test_delete_book_by_id(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_book(conn, 1, 'Book1', 'sci-fi', 10.0, None)
    affected = queries.delete_book_by_id(conn, 1)
    assert affected == 1


def test_count_books_by_genre(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_book(conn, 1, 'B1', 'sci-fi', 10.0, None)
    queries.create_book(conn, 1, 'B2', 'sci-fi', 10.0, None)
    queries.create_book(conn, 1, 'B3', 'fantasy', 10.0, None)
    counts = queries.count_books_by_genre(conn)
    assert len(counts) == 2


def test_get_books_by_price_range(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_book(conn, 1, 'Cheap', 'sci-fi', 5.99, None)
    queries.create_book(conn, 1, 'Mid', 'sci-fi', 10.5, None)
    queries.create_book(conn, 1, 'Expensive', 'sci-fi', 20.99, None)
    books = queries.get_books_by_price_range(conn, 7.0, 15.0)
    assert len(books) == 1
    assert books[0].title == 'Mid'


def test_search_books_by_title(conn):
    queries.create_author(conn, 'A', None, 1900)
    queries.create_book(conn, 1, 'Foundation', 'sci-fi', 9.99, None)
    queries.create_book(conn, 1, 'Dune', 'sci-fi', 12.99, None)
    books = queries.search_books_by_title(conn, '%ound%')
    assert len(books) == 1
    assert books[0].title == 'Foundation'


