"""Generated e2e runtime test — python/postgresql. DO NOT EDIT.

Auto-generated by scripts/e2e_testgen from test_spec.yaml.
"""

import datetime
import json
import os
import pathlib
import uuid

import psycopg
import pytest

from gen.queries import queries
from gen.models import *

_FIXTURES = pathlib.Path(__file__).parent / ".."
_DB_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://sqltgen:sqltgen@localhost:15432/sqltgen_e2e",
)


@pytest.fixture()
def conn():
    """Yield a psycopg connection with an isolated database; drop it on teardown."""
    db_name = "test_" + uuid.uuid4().hex
    schema_sql = (_FIXTURES / "schema.sql").read_text()

    # Create isolated database.
    with psycopg.connect(_DB_URL, autocommit=True) as admin:
        admin.execute(f'CREATE DATABASE "{db_name}"')

    # Parse base URL and connect to the new database.
    base = _DB_URL.rsplit("/", 1)[0]
    with psycopg.connect(f"{base}/{db_name}", autocommit=True) as c:
        c.execute(schema_sql)
        yield c

    # Drop the test database.
    with psycopg.connect(_DB_URL, autocommit=True) as admin:
        admin.execute(f"""
            SELECT pg_terminate_backend(pid)
            FROM pg_stat_activity
            WHERE datname = '{db_name}' AND pid <> pg_backend_pid()
        """)
        admin.execute(f'DROP DATABASE IF EXISTS "{db_name}"')


def test_create_author_returns_row(conn):
    author = queries.create_author(conn, 'Asimov', 'Sci-fi master', 1920)
    assert author is not None
    assert author.name == 'Asimov'
    assert author.bio == 'Sci-fi master'
    assert author.birth_year == 1920


def test_create_author_null_bio(conn):
    author = queries.create_author(conn, 'Herbert', None, 1920)
    assert author is not None
    assert author.name == 'Herbert'
    assert author.bio is None


def test_create_book_returns_row(conn):
    queries.create_author(conn, 'Author', None, 1900)
    book = queries.create_book(conn, 1, 'Dune', 'sci-fi', 12.99, datetime.date(1965, 6, 1))
    assert book is not None
    assert book.title == 'Dune'
    assert book.genre == 'sci-fi'


def test_update_author_bio_returns_row(conn):
    queries.create_author(conn, 'Author', 'Old bio', 1900)
    updated = queries.update_author_bio(conn, 'New bio', 1)
    assert updated is not None
    assert updated.name == 'Author'
    assert updated.bio == 'New bio'


def test_update_author_bio_to_null(conn):
    queries.create_author(conn, 'Author', 'Has bio', 1900)
    updated = queries.update_author_bio(conn, None, 1)
    assert updated is not None
    assert updated.bio is None


def test_delete_author_returns_row(conn):
    queries.create_author(conn, 'ToDelete', None, 1900)
    deleted = queries.delete_author(conn, 1)
    assert deleted is not None
    assert deleted.name == 'ToDelete'
    gone = queries.get_author(conn, 1)
    assert gone is None


def test_delete_author_not_found(conn):
    result = queries.delete_author(conn, 999)
    assert result is None


