// Generated e2e runtime test — go/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"math/rand"
	"os"
	"reflect"
	"strings"
	"testing"
	"time"

	gen "e2e-bookstore-go-postgresql/gen"

	"github.com/jackc/pgx/v5/pgxpool"
	_ "github.com/jackc/pgx/v5/stdlib"
)

// ─── test setup ──────────────────────────────────────────────────────────────

func genDSN() string {
	if v := os.Getenv("DATABASE_URL"); v != "" {
		return v
	}
	return "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e"
}

func setupDB(t *testing.T) (*pgxpool.Pool, func()) {
	t.Helper()
	ctx := context.Background()

	dbName := fmt.Sprintf("test_%d", rand.Int63())
	admin, err := sql.Open("pgx", genDSN())
	if err != nil {
		t.Fatal(err)
	}
	if _, err := admin.ExecContext(ctx, fmt.Sprintf(`CREATE DATABASE "%s"`, dbName)); err != nil {
		t.Fatal(err)
	}
	admin.Close()

	dbURL := genReplaceLastSegment(genDSN(), dbName)
	pool, err := pgxpool.New(ctx, dbURL)
	if err != nil {
		t.Fatal(err)
	}

	ddl, err := os.ReadFile("../schema.sql")
	if err != nil {
		t.Fatal(err)
	}
	for _, stmt := range genSplitStatements(string(ddl)) {
		if _, err := pool.Exec(ctx, stmt); err != nil {
			t.Fatal(err)
		}
	}

	cleanup := func() {
		pool.Close()
		adm, _ := sql.Open("pgx", genDSN())
		adm.ExecContext(ctx, fmt.Sprintf(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '%s' AND pid <> pg_backend_pid()`, dbName))
		adm.ExecContext(ctx, fmt.Sprintf(`DROP DATABASE IF EXISTS "%s"`, dbName))
		adm.Close()
	}
	return pool, cleanup
}

func genReplaceLastSegment(url, replacement string) string {
	i := strings.LastIndex(url, "/")
	if i < 0 {
		return url
	}
	return url[:i+1] + replacement
}

func genSplitStatements(ddl string) []string {
	var stmts []string
	for _, s := range strings.Split(ddl, ";") {
		s = strings.TrimSpace(s)
		if s != "" {
			stmts = append(stmts, s)
		}
	}
	return stmts
}

// ─── test helpers ────────────────────────────────────────────────────────────

// genUUID generates a random UUID v4-like string for test row isolation.
func genUUID() string {
	return fmt.Sprintf("%08x-%04x-4%03x-%04x-%012x",
		rand.Int63()&0xFFFFFFFF,
		rand.Int63()&0xFFFF,
		rand.Int63()&0xFFF,
		rand.Int63()&0x3FFF|0x8000,
		rand.Int63()&0xFFFFFFFFFFFF,
	)
}

// genMarshal marshals v to JSON bytes.
func genMarshal(v interface{}) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}

// _genBytesOf extracts a []byte representation from []byte, *[]byte,
// sql.NullString, or string — used to normalise JSON field types across engines.
func _genBytesOf(v interface{}) []byte {
	switch t := v.(type) {
	case []byte:
		return t
	case *[]byte:
		if t != nil {
			return *t
		}
		return nil
	case sql.NullString:
		if t.Valid {
			return []byte(t.String)
		}
		return nil
	case string:
		return []byte(t)
	}
	panic(fmt.Sprintf("_genBytesOf: unexpected type %T", v))
}

// _genTimeOf extracts a time.Time from time.Time or sql.NullTime.
func _genTimeOf(v interface{}) time.Time {
	switch t := v.(type) {
	case time.Time:
		return t
	case sql.NullTime:
		return t.Time
	}
	panic(fmt.Sprintf("_genTimeOf: unexpected type %T", v))
}

// _genIsNull returns true when v is null/invalid (nil pointer, or invalid
// sql.NullTime / sql.NullString).
func _genIsNull(v interface{}) bool {
	switch t := v.(type) {
	case sql.NullTime:
		return !t.Valid
	case sql.NullString:
		return !t.Valid
	case *[]byte:
		return t == nil
	}
	return v == nil
}

// _genPtrTo returns a pointer to a copy of v. Used for nullable enum parameters.
func _genPtrTo[T any](v T) *T {
	return &v
}

// genAssertJSON asserts that got and want contain equivalent JSON values.
// got may be []byte, *[]byte, sql.NullString, or string.
// want must be a Go value that can be JSON-marshalled (e.g. map[string]interface{}).
func genAssertJSON(t *testing.T, got, want interface{}) {
	t.Helper()
	var gotParsed, wantParsed interface{}
	if err := json.Unmarshal(_genBytesOf(got), &gotParsed); err != nil {
		t.Fatalf("genAssertJSON: failed to unmarshal got: %v (value: %v)", err, got)
	}
	if err := json.Unmarshal(genMarshal(want), &wantParsed); err != nil {
		t.Fatalf("genAssertJSON: failed to unmarshal want: %v", err)
	}
	if !reflect.DeepEqual(gotParsed, wantParsed) {
		t.Errorf("expected %v, got %v", wantParsed, gotParsed)
	}
}

// mustJSON marshals v to JSON bytes. Used for JSON parameter binding.
func mustJSON(v interface{}) []byte {
	b, err := json.Marshal(v)
	if err != nil {
		panic(err)
	}
	return b
}

// ptrBytes returns a pointer to a byte slice copy.
func ptrBytes(b []byte) *[]byte {
	return &b
}

// testUUID returns a deterministic-looking UUID string for test assertions.
func testUUID() string {
	return fmt.Sprintf("%08x-0000-4000-8000-%012x", rand.Int63()&0xFFFFFFFF, rand.Int63()&0xFFFFFFFFFFFF)
}

// ─── scenarios ───────────────────────────────────────────────────────────────

// ─── :exec queries ───────────────────────────────────────────────────────────

func TestAddSaleItemGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateCustomer(ctx, db, "Customer", "c@example.com"); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Book", "sci-fi", "10.0", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateSale(ctx, db, 1); err != nil {
		t.Fatal(err)
	}
	if err := gen.AddSaleItem(ctx, db, 1, 1, 3, "10.0"); err != nil {
		t.Fatal(err)
	}
}

// ─── :execrows queries ───────────────────────────────────────────────────────────

func TestDeleteBookByIdGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Book1", "sci-fi", "10.0", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	affected, err := gen.DeleteBookById(ctx, db, 1)
	if err != nil {
		t.Fatal(err)
	}
	if affected != 1 { t.Errorf("expected %v, got %v", 1, affected) }
}

// ─── :many queries ───────────────────────────────────────────────────────────

func TestListAuthorsGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "Asimov", sql.NullString{}, sql.NullInt32{Int32: 1920, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateAuthor(ctx, db, "Herbert", sql.NullString{}, sql.NullInt32{Int32: 1920, Valid: true}); err != nil {
		t.Fatal(err)
	}
	authors, err := gen.ListAuthors(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	_ = authors
	if len(authors) != 2 { t.Fatalf("expected len=2, got %d", len(authors)) }
	if authors[0].Name != "Asimov" { t.Errorf("expected %v, got %v", "Asimov", authors[0].Name) }
	if authors[1].Name != "Herbert" { t.Errorf("expected %v, got %v", "Herbert", authors[1].Name) }
}

func TestListBooksByGenreGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "SciFi1", "sci-fi", "9.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Fantasy1", "fantasy", "11.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	books, err := gen.ListBooksByGenre(ctx, db, "sci-fi")
	if err != nil {
		t.Fatal(err)
	}
	_ = books
	if len(books) != 1 { t.Fatalf("expected len=1, got %d", len(books)) }
	if books[0].Title != "SciFi1" { t.Errorf("expected %v, got %v", "SciFi1", books[0].Title) }
}

func TestListBooksByGenreOrAllGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "B1", "sci-fi", "9.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "B2", "fantasy", "9.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	all_books, err := gen.ListBooksByGenreOrAll(ctx, db, sql.NullString{})
	if err != nil {
		t.Fatal(err)
	}
	_ = all_books
	if len(all_books) != 2 { t.Fatalf("expected len=2, got %d", len(all_books)) }
	scifi, err := gen.ListBooksByGenreOrAll(ctx, db, sql.NullString{String: "sci-fi", Valid: true})
	if err != nil {
		t.Fatal(err)
	}
	_ = scifi
	if len(scifi) != 1 { t.Fatalf("expected len=1, got %d", len(scifi)) }
}

func TestListBooksWithAuthorJoinGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "Author A", sql.NullString{String: "Bio A", Valid: true}, sql.NullInt32{Int32: 1920, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Book A", "sci-fi", "9.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	rows, err := gen.ListBooksWithAuthor(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	_ = rows
	if len(rows) != 1 { t.Fatalf("expected len=1, got %d", len(rows)) }
	if rows[0].AuthorName != "Author A" { t.Errorf("expected %v, got %v", "Author A", rows[0].AuthorName) }
}

// ─── :one queries ───────────────────────────────────────────────────────────

func TestGetAuthorGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "Asimov", sql.NullString{String: "Sci-fi master", Valid: true}, sql.NullInt32{Int32: 1920, Valid: true}); err != nil {
		t.Fatal(err)
	}
	author, err := gen.GetAuthor(ctx, db, 1)
	if err != nil {
		t.Fatal(err)
	}
	_ = author
	if author == nil { t.Fatalf("expected non-nil author") }
	if author.Name != "Asimov" { t.Errorf("expected %v, got %v", "Asimov", author.Name) }
	if !author.Bio.Valid || author.Bio.String != "Sci-fi master" { t.Errorf("expected %v, got %v", "Sci-fi master", author.Bio) }
	if !author.BirthYear.Valid || author.BirthYear.Int32 != 1920 { t.Errorf("expected %v, got %v", 1920, author.BirthYear) }
}

func TestGetAuthorNotFoundGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	result, err := gen.GetAuthor(ctx, db, 999)
	if err != nil {
		t.Fatal(err)
	}
	_ = result
	if result != nil { t.Fatalf("expected nil, got %v", result) }
}

func TestGetBookGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "Herbert", sql.NullString{}, sql.NullInt32{Int32: 1920, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Dune", "sci-fi", "12.99", sql.NullTime{Time: time.Date(1965, 6, 1, 0, 0, 0, 0, time.UTC), Valid: true}); err != nil {
		t.Fatal(err)
	}
	book, err := gen.GetBook(ctx, db, 1)
	if err != nil {
		t.Fatal(err)
	}
	_ = book
	if book == nil { t.Fatalf("expected non-nil book") }
	if book.Title != "Dune" { t.Errorf("expected %v, got %v", "Dune", book.Title) }
	if book.Genre != "sci-fi" { t.Errorf("expected %v, got %v", "sci-fi", book.Genre) }
}

// ─── aggregates ───────────────────────────────────────────────────────────

func TestCountBooksByGenreGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "B1", "sci-fi", "10.0", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "B2", "sci-fi", "10.0", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "B3", "fantasy", "10.0", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	counts, err := gen.CountBooksByGenre(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	_ = counts
	if len(counts) != 2 { t.Fatalf("expected len=2, got %d", len(counts)) }
}

// ─── filtering ───────────────────────────────────────────────────────────

func TestGetBooksByPriceRangeGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Cheap", "sci-fi", "5.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Mid", "sci-fi", "10.5", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Expensive", "sci-fi", "20.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	books, err := gen.GetBooksByPriceRange(ctx, db, "7.0", "15.0")
	if err != nil {
		t.Fatal(err)
	}
	_ = books
	if len(books) != 1 { t.Fatalf("expected len=1, got %d", len(books)) }
	if books[0].Title != "Mid" { t.Errorf("expected %v, got %v", "Mid", books[0].Title) }
}

func TestSearchBooksByTitleGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "A", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Foundation", "sci-fi", "9.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateBook(ctx, db, 1, "Dune", "sci-fi", "12.99", sql.NullTime{}); err != nil {
		t.Fatal(err)
	}
	books, err := gen.SearchBooksByTitle(ctx, db, "%ound%")
	if err != nil {
		t.Fatal(err)
	}
	_ = books
	if len(books) != 1 { t.Fatalf("expected len=1, got %d", len(books)) }
	if books[0].Title != "Foundation" { t.Errorf("expected %v, got %v", "Foundation", books[0].Title) }
}

// ─── NULL handling ───────────────────────────────────────────────────────────

func TestAuthorsWithNullBioGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "WithBio", sql.NullString{String: "Has bio", Valid: true}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateAuthor(ctx, db, "NoBio", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	authors, err := gen.GetAuthorsWithNullBio(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	_ = authors
	if len(authors) != 1 { t.Fatalf("expected len=1, got %d", len(authors)) }
	if authors[0].Name != "NoBio" { t.Errorf("expected %v, got %v", "NoBio", authors[0].Name) }
}

func TestAuthorsWithBioGen(t *testing.T) {
	db, cleanup := setupDB(t)
	defer cleanup()
	ctx := context.Background()
	if _, err := gen.CreateAuthor(ctx, db, "WithBio", sql.NullString{String: "Bio", Valid: true}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	if _, err := gen.CreateAuthor(ctx, db, "NoBio", sql.NullString{}, sql.NullInt32{Int32: 1900, Valid: true}); err != nil {
		t.Fatal(err)
	}
	authors, err := gen.GetAuthorsWithBio(ctx, db)
	if err != nil {
		t.Fatal(err)
	}
	_ = authors
	if len(authors) != 1 { t.Fatalf("expected len=1, got %d", len(authors)) }
	if authors[0].Name != "WithBio" { t.Errorf("expected %v, got %v", "WithBio", authors[0].Name) }
}

