/**
 * Generated e2e runtime test — javascript/postgresql. DO NOT EDIT.
 *
 * Auto-generated by scripts/e2e_testgen from test_spec.yaml.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes, randomUUID } from 'node:crypto';
import pg from 'pg';
const { Client } = pg;

import * as queries from './gen/queries/index.js';

const FIXTURES = join(import.meta.dirname, '../../../../fixtures/array_overrides/postgresql');
const DATABASE_URL = process.env['DATABASE_URL']
  ?? 'postgresql://sqltgen:sqltgen@localhost:15432/sqltgen_e2e';

async function makeClient() {
  const dbName = 'test_' + randomBytes(16).toString('hex');
  const schemaSql = readFileSync(join(FIXTURES, 'schema.sql'), 'utf8');
  const base = DATABASE_URL.replace(/\/[^/]*$/, '');
  const admin = new Client({ connectionString: DATABASE_URL });
  await admin.connect();
  await admin.query(`CREATE DATABASE "${dbName}"`);
  await admin.end();
  const db = new Client({ connectionString: `${base}/${dbName}` });
  await db.connect();
  for (const stmt of schemaSql.split(';').map(s => s.trim()).filter(Boolean)) {
    await db.query(stmt);
  }
  return { db, dbName };
}

async function teardown(db, dbName) {
  await db.end();
  const admin = new Client({ connectionString: DATABASE_URL });
  await admin.connect();
  await admin.query(`SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '${dbName}' AND pid <> pg_backend_pid()`);
  await admin.query(`DROP DATABASE IF EXISTS "${dbName}"`);
  await admin.end();
}

// ─── :one queries ────────────────────────────────────────────────────────────

describe(':one queries', () => {
  it('insert and get record', async () => {
    const { db, dbName } = await makeClient();
    try {
      await queries.insertRecord(db, 'test', [new Date("2024-01-15T10:30:00"), new Date("2024-06-01T12:00:00")], ['550e8400-e29b-41d4-a716-446655440001', '550e8400-e29b-41d4-a716-446655440002'])
      const row = await queries.getRecord(db, 1)
      assert.ok(row)
      assert.equal(row.label, 'test')
      assert.equal(row.timestamps.length, 2)
      assert.deepEqual(row.timestamps[0], new Date("2024-01-15T10:30:00"))
      assert.deepEqual(row.timestamps[1], new Date("2024-06-01T12:00:00"))
      assert.equal(row.uuids.length, 2)
      assert.equal(row.uuids[0], '550e8400-e29b-41d4-a716-446655440001')
      assert.equal(row.uuids[1], '550e8400-e29b-41d4-a716-446655440002')
    } finally { await teardown(db, dbName); }
  });

  it('get record not found', async () => {
    const { db, dbName } = await makeClient();
    try {
      const result = await queries.getRecord(db, 999)
      assert.equal(result, null)
    } finally { await teardown(db, dbName); }
  });

  it('empty arrays', async () => {
    const { db, dbName } = await makeClient();
    try {
      await queries.insertRecord(db, 'empty', [], [])
      const row = await queries.getRecord(db, 1)
      assert.ok(row)
      assert.equal(row.timestamps.length, 0)
      assert.equal(row.uuids.length, 0)
    } finally { await teardown(db, dbName); }
  });

});

