// Generated e2e runtime test — java/sqlite. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.*;
import java.util.List;
import java.util.UUID;
import com.example.db.queries.Queries;
import com.example.db.models.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private static final ObjectMapper GEN_MAPPER = new ObjectMapper();
    private Connection conn;

    @BeforeEach
    void setUp() throws Exception {
        conn = DriverManager.getConnection("jdbc:sqlite::memory:");
        conn.setAutoCommit(true);
        String ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/bookstore/sqlite/schema.sql"));
        try (Statement s = conn.createStatement()) {
            for (String stmt : ddl.split(";")) {
                String t = stmt.strip();
                if (!t.isEmpty()) s.execute(t);
            }
        }
    }

    @AfterEach
    void tearDown() throws Exception {
        if (conn != null) conn.close();
    }

    private static JsonNode genJson(String raw) {
        try {
            return GEN_MAPPER.readTree(raw);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    void testAddSaleItemGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createCustomer(conn, "Customer", "c@example.com");
        Queries.createBook(conn, 1, "Book", "sci-fi", 10.0, null);
        Queries.createSale(conn, 1);
        Queries.addSaleItem(conn, 1, 1, 3, 10.0);
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    void testDeleteBookByIdGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1, "Book1", "sci-fi", 10.0, null);
        var affected = Queries.deleteBookById(conn, 1);
        assertEquals(1L, affected);
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    void testListAuthorsGen() throws Exception {
        Queries.createAuthor(conn, "Asimov", null, 1920);
        Queries.createAuthor(conn, "Herbert", null, 1920);
        var authors = Queries.listAuthors(conn);
        assertEquals(2, authors.size());
        assertEquals("Asimov", authors.get(0).name());
        assertEquals("Herbert", authors.get(1).name());
    }

    @Test
    void testListBooksByGenreGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1, "SciFi1", "sci-fi", 9.99, null);
        Queries.createBook(conn, 1, "Fantasy1", "fantasy", 11.99, null);
        var books = Queries.listBooksByGenre(conn, "sci-fi");
        assertEquals(1, books.size());
        assertEquals("SciFi1", books.get(0).title());
    }

    @Test
    void testListBooksByGenreOrAllGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1, "B1", "sci-fi", 9.99, null);
        Queries.createBook(conn, 1, "B2", "fantasy", 9.99, null);
        var all_books = Queries.listBooksByGenreOrAll(conn, null);
        assertEquals(2, all_books.size());
        var scifi = Queries.listBooksByGenreOrAll(conn, "sci-fi");
        assertEquals(1, scifi.size());
    }

    @Test
    void testListBooksWithAuthorJoinGen() throws Exception {
        Queries.createAuthor(conn, "Author A", "Bio A", 1920);
        Queries.createBook(conn, 1, "Book A", "sci-fi", 9.99, null);
        var rows = Queries.listBooksWithAuthor(conn);
        assertEquals(1, rows.size());
        assertEquals("Author A", rows.get(0).authorName());
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    void testGetAuthorGen() throws Exception {
        Queries.createAuthor(conn, "Asimov", "Sci-fi master", 1920);
        var author = Queries.getAuthor(conn, 1).orElseThrow();
        assertNotNull(author);
        assertEquals("Asimov", author.name());
        assertEquals("Sci-fi master", author.bio());
        assertEquals(1920L, author.birthYear());
    }

    @Test
    void testGetAuthorNotFoundGen() throws Exception {
        var result = Queries.getAuthor(conn, 999);
        assertTrue(result.isEmpty());
    }

    @Test
    void testGetBookGen() throws Exception {
        Queries.createAuthor(conn, "Herbert", null, 1920);
        Queries.createBook(conn, 1, "Dune", "sci-fi", 12.99, LocalDate.of(1965, 6, 1));
        var book = Queries.getBook(conn, 1).orElseThrow();
        assertNotNull(book);
        assertEquals("Dune", book.title());
        assertEquals("sci-fi", book.genre());
    }

    // ─── aggregates ────────────────────────────────────────────────────────────

    @Test
    void testCountBooksByGenreGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1, "B1", "sci-fi", 10.0, null);
        Queries.createBook(conn, 1, "B2", "sci-fi", 10.0, null);
        Queries.createBook(conn, 1, "B3", "fantasy", 10.0, null);
        var counts = Queries.countBooksByGenre(conn);
        assertEquals(2, counts.size());
    }

    // ─── filtering ────────────────────────────────────────────────────────────

    @Test
    void testGetBooksByPriceRangeGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1, "Cheap", "sci-fi", 5.0, null);
        Queries.createBook(conn, 1, "Mid", "sci-fi", 10.0, null);
        Queries.createBook(conn, 1, "Expensive", "sci-fi", 20.0, null);
        var books = Queries.getBooksByPriceRange(conn, 7.0, 15.0);
        assertEquals(1, books.size());
        assertEquals("Mid", books.get(0).title());
    }

    @Test
    void testSearchBooksByTitleGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1, "Foundation", "sci-fi", 9.99, null);
        Queries.createBook(conn, 1, "Dune", "sci-fi", 12.99, null);
        var books = Queries.searchBooksByTitle(conn, "%ound%");
        assertEquals(1, books.size());
        assertEquals("Foundation", books.get(0).title());
    }

    // ─── NULL handling ────────────────────────────────────────────────────────────

    @Test
    void testAuthorsWithNullBioGen() throws Exception {
        Queries.createAuthor(conn, "WithBio", "Has bio", 1900);
        Queries.createAuthor(conn, "NoBio", null, 1900);
        var authors = Queries.getAuthorsWithNullBio(conn);
        assertEquals(1, authors.size());
        assertEquals("NoBio", authors.get(0).name());
    }

    @Test
    void testAuthorsWithBioGen() throws Exception {
        Queries.createAuthor(conn, "WithBio", "Bio", 1900);
        Queries.createAuthor(conn, "NoBio", null, 1900);
        var authors = Queries.getAuthorsWithBio(conn);
        assertEquals(1, authors.size());
        assertEquals("WithBio", authors.get(0).name());
    }

}
