use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::common::{infer_table, sql_const_name, to_pascal_case, to_snake_case};
use crate::backend::{Codegen, GeneratedFile};
use crate::config::OutputConfig;
use crate::ir::{Query, QueryCmd, Schema, SqlType};

pub enum PythonTarget {
    Postgres,
    Sqlite,
    Mysql,
}

pub struct PythonCodegen {
    pub target: PythonTarget,
}

impl Codegen for PythonCodegen {
    fn generate(&self, schema: &Schema, queries: &[Query], config: &OutputConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let mut files = Vec::new();

        // One @dataclass file per table
        for table in &schema.tables {
            let class_name = to_pascal_case(&table.name);
            let mut src = String::new();
            writeln!(src, "# Generated by sqltgen. Do not edit.")?;
            writeln!(src, "from __future__ import annotations")?;
            writeln!(src)?;
            writeln!(src, "import dataclasses")?;

            let mut imports = TypeImports::default();
            for col in &table.columns {
                imports.scan(&col.sql_type);
            }
            imports.write(&mut src)?;

            writeln!(src)?;
            writeln!(src)?;
            writeln!(src, "@dataclasses.dataclass")?;
            writeln!(src, "class {class_name}:")?;
            for col in &table.columns {
                let ty = python_type(&col.sql_type, col.nullable);
                writeln!(src, "    {}: {}", col.name, ty)?;
            }

            let path = PathBuf::from(&config.out).join(format!("{}.py", table.name));
            files.push(GeneratedFile { path, content: src });
        }

        // queries.py
        if !queries.is_empty() {
            let src = build_queries_file(queries, schema, &self.target)?;
            let path = PathBuf::from(&config.out).join("queries.py");
            files.push(GeneratedFile { path, content: src });
        }

        // __init__.py
        {
            let mut src = String::new();
            writeln!(src, "# Generated by sqltgen. Do not edit.")?;
            for table in &schema.tables {
                let class_name = to_pascal_case(&table.name);
                writeln!(src, "from .{} import {}", table.name, class_name)?;
            }
            if !queries.is_empty() {
                writeln!(src, "from . import queries")?;
            }

            let path = PathBuf::from(&config.out).join("__init__.py");
            files.push(GeneratedFile { path, content: src });
        }

        Ok(files)
    }
}

fn build_queries_file(queries: &[Query], schema: &Schema, target: &PythonTarget) -> anyhow::Result<String> {
    let mut src = String::new();

    let has_inline_rows = queries.iter().any(|q| infer_table(q, schema).is_none() && !q.result_columns.is_empty());

    // Collect type imports across all query params and result columns
    let mut imports = TypeImports::default();
    for query in queries {
        for p in &query.params {
            imports.scan(&p.sql_type);
        }
        for col in &query.result_columns {
            imports.scan(&col.sql_type);
        }
    }

    // Header
    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    match target {
        PythonTarget::Postgres => writeln!(src, "# Runtime: psycopg (psycopg3) — pip install psycopg")?,
        PythonTarget::Sqlite => writeln!(src, "# Runtime: sqlite3 (stdlib)")?,
        PythonTarget::Mysql => writeln!(src, "# Runtime: mysql-connector-python — pip install mysql-connector-python")?,
    }
    writeln!(src, "from __future__ import annotations")?;
    writeln!(src)?;
    if has_inline_rows {
        writeln!(src, "import dataclasses")?;
    }
    match target {
        PythonTarget::Postgres => writeln!(src, "import psycopg")?,
        PythonTarget::Sqlite => writeln!(src, "import sqlite3")?,
        PythonTarget::Mysql => writeln!(src, "import mysql.connector")?,
    }
    imports.write(&mut src)?;

    // Table imports (sorted, only tables used as return types)
    let mut needed_tables: BTreeSet<&str> = BTreeSet::new();
    for query in queries {
        if let Some(table_name) = infer_table(query, schema) {
            needed_tables.insert(table_name);
        }
    }
    if !needed_tables.is_empty() {
        writeln!(src)?;
        for table_name in &needed_tables {
            let class_name = to_pascal_case(table_name);
            writeln!(src, "from .{table_name} import {class_name}")?;
        }
    }

    // SQL constants
    writeln!(src)?;
    for query in queries {
        let const_name = sql_const_name(&query.name);
        let sql = rewrite_sql(&query.sql, target).replace('"', "\\\"").replace('\n', " ");
        let sql = sql.trim_end().trim_end_matches(';');
        writeln!(src, r#"{const_name} = "{sql}""#)?;
    }

    // Query functions
    for query in queries {
        writeln!(src)?;
        writeln!(src)?;
        if infer_table(query, schema).is_none() && !query.result_columns.is_empty() {
            emit_row_dataclass(&mut src, query)?;
            writeln!(src)?;
            writeln!(src)?;
        }
        emit_python_query(&mut src, query, schema, target)?;
    }

    Ok(src)
}

fn emit_row_dataclass(src: &mut String, query: &Query) -> anyhow::Result<()> {
    let name = row_class_name(&query.name);
    writeln!(src, "@dataclasses.dataclass")?;
    writeln!(src, "class {name}:")?;
    for col in &query.result_columns {
        let ty = python_type(&col.sql_type, col.nullable);
        writeln!(src, "    {}: {}", col.name, ty)?;
    }
    Ok(())
}

fn emit_python_query(src: &mut String, query: &Query, schema: &Schema, target: &PythonTarget) -> anyhow::Result<()> {
    match target {
        PythonTarget::Postgres => emit_cursor_query(src, query, schema, "psycopg.Connection"),
        PythonTarget::Mysql => emit_cursor_query(src, query, schema, "mysql.connector.MySQLConnection"),
        PythonTarget::Sqlite => emit_sqlite_query(src, query, schema),
    }
}

/// Emits a query function using a cursor context manager (`with conn.cursor() as cur:`).
/// Used by both the psycopg (Postgres) and mysql-connector-python (MySQL) targets,
/// which share the same cursor API and `%s` placeholder style.
fn emit_cursor_query(src: &mut String, query: &Query, schema: &Schema, conn_type: &str) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let return_type = cursor_return_type(query, schema);

    let params_sig: String = std::iter::once(format!("conn: {conn_type}"))
        .chain(query.params.iter().map(|p| format!("{}: {}", to_snake_case(&p.name), python_type(&p.sql_type, p.nullable))))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;
    writeln!(src, "    with conn.cursor() as cur:")?;

    let execute_call = build_execute_call(&const_name, query);
    writeln!(src, "        cur.{execute_call}")?;

    match query.cmd {
        QueryCmd::Exec => {},
        QueryCmd::ExecRows => {
            writeln!(src, "        return cur.rowcount")?;
        },
        QueryCmd::One => {
            let row_type = result_row_type(query, schema);
            writeln!(src, "        row = cur.fetchone()")?;
            writeln!(src, "        if row is None:")?;
            writeln!(src, "            return None")?;
            writeln!(src, "        return {row_type}(*row)")?;
        },
        QueryCmd::Many => {
            let row_type = result_row_type(query, schema);
            writeln!(src, "        return [{row_type}(*row) for row in cur.fetchall()]")?;
        },
    }

    Ok(())
}

fn emit_sqlite_query(src: &mut String, query: &Query, schema: &Schema) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let return_type = sqlite_return_type(query, schema);

    let params_sig: String = std::iter::once("conn: sqlite3.Connection".to_string())
        .chain(query.params.iter().map(|p| format!("{}: {}", to_snake_case(&p.name), python_type(&p.sql_type, p.nullable))))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;

    // sqlite3 uses conn.execute() directly — no cursor context manager
    let execute_call = build_execute_call(&const_name, query);
    match query.cmd {
        QueryCmd::Exec => {
            writeln!(src, "    conn.{execute_call}")?;
        },
        QueryCmd::ExecRows => {
            writeln!(src, "    return conn.{execute_call}.rowcount")?;
        },
        QueryCmd::One => {
            let row_type = result_row_type(query, schema);
            writeln!(src, "    row = conn.{execute_call}.fetchone()")?;
            writeln!(src, "    if row is None:")?;
            writeln!(src, "        return None")?;
            writeln!(src, "    return {row_type}(*row)")?;
        },
        QueryCmd::Many => {
            let row_type = result_row_type(query, schema);
            writeln!(src, "    return [{row_type}(*row) for row in conn.{execute_call}.fetchall()]")?;
        },
    }

    Ok(())
}

fn build_execute_call(const_name: &str, query: &Query) -> String {
    if query.params.is_empty() {
        format!("execute({const_name})")
    } else {
        let args: Vec<String> = query.params.iter().map(|p| to_snake_case(&p.name)).collect();
        let tuple = if args.len() == 1 { format!("({},)", args[0]) } else { format!("({})", args.join(", ")) };
        format!("execute({const_name}, {tuple})")
    }
}

fn cursor_return_type(query: &Query, schema: &Schema) -> String {
    match query.cmd {
        QueryCmd::One => format!("{} | None", result_row_type(query, schema)),
        QueryCmd::Many => format!("list[{}]", result_row_type(query, schema)),
        QueryCmd::Exec => "None".to_string(),
        QueryCmd::ExecRows => "int".to_string(),
    }
}

fn sqlite_return_type(query: &Query, schema: &Schema) -> String {
    cursor_return_type(query, schema)
}

// ─── Type helpers ─────────────────────────────────────────────────────────────

fn python_type(sql_type: &SqlType, nullable: bool) -> String {
    let base = match sql_type {
        SqlType::Boolean => "bool".to_string(),
        SqlType::SmallInt | SqlType::Integer | SqlType::BigInt => "int".to_string(),
        SqlType::Real | SqlType::Double => "float".to_string(),
        SqlType::Decimal => "decimal.Decimal".to_string(),
        SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) => "str".to_string(),
        SqlType::Bytes => "bytes".to_string(),
        SqlType::Date => "datetime.date".to_string(),
        SqlType::Time => "datetime.time".to_string(),
        SqlType::Timestamp | SqlType::TimestampTz => "datetime.datetime".to_string(),
        SqlType::Interval => "datetime.timedelta".to_string(),
        SqlType::Uuid => "uuid.UUID".to_string(),
        SqlType::Json | SqlType::Jsonb => "Any".to_string(),
        SqlType::Array(inner) => {
            let inner_ty = python_type(inner, false);
            let list_ty = format!("list[{inner_ty}]");
            return if nullable { format!("{list_ty} | None") } else { list_ty };
        },
        SqlType::Custom(_) => "Any".to_string(),
    };
    if nullable {
        format!("{base} | None")
    } else {
        base
    }
}

#[derive(Default)]
struct TypeImports {
    decimal: bool,
    datetime: bool,
    uuid: bool,
    any_type: bool,
}

impl TypeImports {
    fn scan(&mut self, ty: &SqlType) {
        match ty {
            SqlType::Decimal => self.decimal = true,
            SqlType::Date | SqlType::Time | SqlType::Timestamp | SqlType::TimestampTz | SqlType::Interval => self.datetime = true,
            SqlType::Uuid => self.uuid = true,
            SqlType::Json | SqlType::Jsonb | SqlType::Custom(_) => self.any_type = true,
            SqlType::Array(inner) => self.scan(inner),
            _ => {},
        }
    }

    fn write(&self, src: &mut String) -> anyhow::Result<()> {
        if self.decimal {
            writeln!(src, "import decimal")?;
        }
        if self.datetime {
            writeln!(src, "import datetime")?;
        }
        if self.uuid {
            writeln!(src, "import uuid")?;
        }
        if self.any_type {
            writeln!(src, "from typing import Any")?;
        }
        Ok(())
    }
}

// ─── SQL helpers ──────────────────────────────────────────────────────────────

fn rewrite_sql(sql: &str, target: &PythonTarget) -> String {
    match target {
        // Both psycopg and mysql-connector-python use %s positional placeholders
        PythonTarget::Postgres | PythonTarget::Mysql => rewrite_sql_postgres(sql),
        PythonTarget::Sqlite => rewrite_sql_sqlite(sql),
    }
}

/// Replace `$N` or `?N` → `%s` for psycopg3.
fn rewrite_sql_postgres(sql: &str) -> String {
    let mut out = String::with_capacity(sql.len());
    let mut chars = sql.chars().peekable();
    while let Some(ch) = chars.next() {
        if (ch == '$' || ch == '?') && chars.peek().is_some_and(|c| c.is_ascii_digit()) {
            out.push_str("%s");
            while chars.peek().is_some_and(|c| c.is_ascii_digit()) {
                chars.next();
            }
        } else {
            out.push(ch);
        }
    }
    out
}

/// Rewrite `?N` or `$N` → `?` for sqlite3.
fn rewrite_sql_sqlite(sql: &str) -> String {
    let mut out = String::with_capacity(sql.len());
    let mut chars = sql.chars().peekable();
    while let Some(ch) = chars.next() {
        if (ch == '?' || ch == '$') && chars.peek().is_some_and(|c| c.is_ascii_digit()) {
            out.push('?');
            while chars.peek().is_some_and(|c| c.is_ascii_digit()) {
                chars.next();
            }
        } else {
            out.push(ch);
        }
    }
    out
}

// ─── Row helpers ──────────────────────────────────────────────────────────────

fn result_row_type(query: &Query, schema: &Schema) -> String {
    if let Some(table_name) = infer_table(query, schema) {
        return to_pascal_case(table_name);
    }
    if !query.result_columns.is_empty() {
        return row_class_name(&query.name);
    }
    "Any".to_string()
}

fn row_class_name(query_name: &str) -> String {
    format!("{}Row", to_pascal_case(query_name))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::OutputConfig;
    use crate::ir::{Column, Parameter, Query, QueryCmd, ResultColumn, Schema, SqlType, Table};

    fn cfg() -> OutputConfig {
        OutputConfig { out: "out".to_string(), package: String::new() }
    }

    fn get_file<'a>(files: &'a [GeneratedFile], name: &str) -> &'a str {
        files.iter().find(|f| f.path.file_name().is_some_and(|n| n == name)).unwrap_or_else(|| panic!("file {name:?} not found")).content.as_str()
    }

    fn pg() -> PythonCodegen {
        PythonCodegen { target: PythonTarget::Postgres }
    }
    fn sq() -> PythonCodegen {
        PythonCodegen { target: PythonTarget::Sqlite }
    }
    fn my() -> PythonCodegen {
        PythonCodegen { target: PythonTarget::Mysql }
    }

    fn user_table() -> Table {
        Table {
            name: "user".to_string(),
            columns: vec![
                Column { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false, is_primary_key: true },
                Column { name: "name".to_string(), sql_type: SqlType::Text, nullable: false, is_primary_key: false },
                Column { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true, is_primary_key: false },
            ],
        }
    }

    // ─── generate: dataclass file ───────────────────────────────────────────

    #[test]
    fn test_generate_table_dataclass() {
        let schema = Schema { tables: vec![user_table()] };
        let files = pg().generate(&schema, &[], &cfg()).unwrap();
        let src = get_file(&files, "user.py");
        assert!(src.contains("@dataclasses.dataclass"));
        assert!(src.contains("class User:"));
        assert!(src.contains("id: int"));
        assert!(src.contains("name: str"));
        assert!(src.contains("bio: str | None"));
    }

    #[test]
    fn test_generate_init_file_exports_tables_and_queries() {
        let schema = Schema { tables: vec![user_table()] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT id, name, bio FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
            ],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "__init__.py");
        assert!(src.contains("from .user import User"));
        assert!(src.contains("from . import queries"));
    }

    // ─── generate: driver import ────────────────────────────────────────────

    #[test]
    fn test_generate_postgres_imports_psycopg() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("import psycopg"));
        assert!(!src.contains("import sqlite3"));
    }

    #[test]
    fn test_generate_sqlite_imports_sqlite3() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = ?1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = sq().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("import sqlite3"));
        assert!(!src.contains("import psycopg"));
    }

    // ─── generate: SQL constant name ────────────────────────────────────────

    #[test]
    fn test_generate_sql_const_name_is_screaming_snake_case() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "GetUserById".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("SQL_GET_USER_BY_ID"));
    }

    // ─── generate: query commands (psycopg) ─────────────────────────────────

    #[test]
    fn test_generate_psycopg_exec_query() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def delete_user(conn: psycopg.Connection, id: int) -> None:"));
        assert!(src.contains("with conn.cursor() as cur:"));
        assert!(src.contains("cur.execute(SQL_DELETE_USER, (id,))"));
    }

    #[test]
    fn test_generate_psycopg_one_query_infers_table_return_type() {
        let schema = Schema { tables: vec![user_table()] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT id, name, bio FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
            ],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def get_user(conn: psycopg.Connection, id: int) -> User | None:"));
        assert!(src.contains("row = cur.fetchone()"));
        assert!(src.contains("return User(*row)"));
    }

    #[test]
    fn test_generate_psycopg_many_query_infers_table_return_type() {
        let schema = Schema { tables: vec![user_table()] };
        let query = Query {
            name: "ListUsers".to_string(),
            cmd: QueryCmd::Many,
            sql: "SELECT id, name, bio FROM user".to_string(),
            params: vec![],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
            ],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def list_users(conn: psycopg.Connection) -> list[User]:"));
        assert!(src.contains("return [User(*row) for row in cur.fetchall()]"));
    }

    #[test]
    fn test_generate_psycopg_execrows_query() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUsers".to_string(),
            cmd: QueryCmd::ExecRows,
            sql: "DELETE FROM user WHERE active = $1".to_string(),
            params: vec![Parameter { index: 1, name: "active".to_string(), sql_type: SqlType::Boolean, nullable: false }],
            result_columns: vec![],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def delete_users(conn: psycopg.Connection, active: bool) -> int:"));
        assert!(src.contains("return cur.rowcount"));
    }

    // ─── generate: query commands (sqlite3) ─────────────────────────────────

    #[test]
    fn test_generate_sqlite_exec_query_uses_conn_execute() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = ?1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = sq().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def delete_user(conn: sqlite3.Connection, id: int) -> None:"));
        // sqlite3 uses conn.execute() directly — no cursor context manager
        assert!(src.contains("conn.execute(SQL_DELETE_USER, (id,))"));
        assert!(!src.contains("with conn.cursor()"));
    }

    #[test]
    fn test_generate_sqlite_one_query_infers_table_return_type() {
        let schema = Schema { tables: vec![user_table()] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT id, name, bio FROM user WHERE id = ?1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
            ],
        };
        let files = sq().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def get_user(conn: sqlite3.Connection, id: int) -> User | None:"));
        assert!(src.contains("row = conn.execute(SQL_GET_USER, (id,)).fetchone()"));
        assert!(src.contains("return User(*row)"));
    }

    // ─── generate: inline row dataclass ─────────────────────────────────────

    #[test]
    fn test_generate_inline_row_dataclass_for_partial_result() {
        let schema = Schema { tables: vec![user_table()] };
        let query = Query {
            name: "GetUserName".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT name FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false }],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("class GetUserNameRow:"));
        assert!(src.contains("GetUserNameRow | None"));
    }

    // ─── generate: mysql target ─────────────────────────────────────────────

    #[test]
    fn test_generate_mysql_imports_connector() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = my().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("import mysql.connector"));
        assert!(!src.contains("import psycopg"));
    }

    #[test]
    fn test_generate_mysql_uses_mysql_connection_type() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = my().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("conn: mysql.connector.MySQLConnection"));
    }

    #[test]
    fn test_generate_mysql_uses_cursor_context_manager() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = my().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("with conn.cursor() as cur:"));
    }

    #[test]
    fn test_generate_mysql_rewrites_placeholders_to_percent_s() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = my().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("\"DELETE FROM user WHERE id = %s\""));
    }

    #[test]
    fn test_generate_mysql_one_query() {
        let schema = Schema { tables: vec![user_table()] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT id, name, bio FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "bio".to_string(), sql_type: SqlType::Text, nullable: true },
            ],
        };
        let files = my().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("def get_user(conn: mysql.connector.MySQLConnection, id: int) -> User | None:"));
        assert!(src.contains("row = cur.fetchone()"));
        assert!(src.contains("return User(*row)"));
    }

    // ─── generate: placeholder rewriting ────────────────────────────────────

    #[test]
    fn test_generate_postgres_rewrites_placeholders_to_percent_s() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = $1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = pg().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("\"DELETE FROM user WHERE id = %s\""));
    }

    #[test]
    fn test_generate_sqlite_rewrites_placeholders_to_question_mark() {
        let schema = Schema { tables: vec![] };
        let query = Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM user WHERE id = ?1".to_string(),
            params: vec![Parameter { index: 1, name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false }],
            result_columns: vec![],
        };
        let files = sq().generate(&schema, &[query], &cfg()).unwrap();
        let src = get_file(&files, "queries.py");
        assert!(src.contains("\"DELETE FROM user WHERE id = ?\""));
    }
}
