use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::{Codegen, GeneratedFile};
use crate::config::OutputConfig;
use crate::ir::{Query, QueryCmd, Schema, SqlType};

pub struct PythonCodegen;

impl Codegen for PythonCodegen {
    fn generate(
        &self,
        schema: &Schema,
        queries: &[Query],
        config: &OutputConfig,
    ) -> anyhow::Result<Vec<GeneratedFile>> {
        let mut files = Vec::new();

        // One @dataclass file per table
        for table in &schema.tables {
            let class_name = to_pascal_case(&table.name);
            let mut src = String::new();
            writeln!(src, "# Generated by sqltgen. Do not edit.")?;
            writeln!(src, "from __future__ import annotations")?;
            writeln!(src)?;
            writeln!(src, "import dataclasses")?;

            let mut imports = TypeImports::default();
            for col in &table.columns {
                imports.scan(&col.sql_type);
            }
            imports.write(&mut src)?;

            writeln!(src)?;
            writeln!(src)?;
            writeln!(src, "@dataclasses.dataclass")?;
            writeln!(src, "class {class_name}:")?;
            for col in &table.columns {
                let ty = python_type(&col.sql_type, col.nullable);
                writeln!(src, "    {}: {}", col.name, ty)?;
            }

            let path = PathBuf::from(&config.out).join(format!("{}.py", table.name));
            files.push(GeneratedFile { path, content: src });
        }

        // queries.py
        if !queries.is_empty() {
            let src = build_queries_file(queries, schema)?;
            let path = PathBuf::from(&config.out).join("queries.py");
            files.push(GeneratedFile { path, content: src });
        }

        // __init__.py
        {
            let mut src = String::new();
            writeln!(src, "# Generated by sqltgen. Do not edit.")?;
            for table in &schema.tables {
                let class_name = to_pascal_case(&table.name);
                writeln!(src, "from .{} import {}", table.name, class_name)?;
            }
            if !queries.is_empty() {
                writeln!(src, "from . import queries")?;
            }

            let path = PathBuf::from(&config.out).join("__init__.py");
            files.push(GeneratedFile { path, content: src });
        }

        Ok(files)
    }
}

fn build_queries_file(queries: &[Query], schema: &Schema) -> anyhow::Result<String> {
    let mut src = String::new();

    let has_inline_rows = queries
        .iter()
        .any(|q| infer_table(q, schema).is_none() && !q.result_columns.is_empty());

    // Collect type imports across all query params and result columns
    let mut imports = TypeImports::default();
    for query in queries {
        for p in &query.params {
            imports.scan(&p.sql_type);
        }
        for col in &query.result_columns {
            imports.scan(&col.sql_type);
        }
    }

    // Header
    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    writeln!(src, "# Runtime: psycopg (psycopg3) — pip install psycopg")?;
    writeln!(src, "from __future__ import annotations")?;
    writeln!(src)?;
    if has_inline_rows {
        writeln!(src, "import dataclasses")?;
    }
    writeln!(src, "import psycopg")?;
    imports.write(&mut src)?;

    // Table imports (sorted, only tables used as return types)
    let mut needed_tables: BTreeSet<&str> = BTreeSet::new();
    for query in queries {
        if let Some(table_name) = infer_table(query, schema) {
            needed_tables.insert(table_name);
        }
    }
    if !needed_tables.is_empty() {
        writeln!(src)?;
        for table_name in &needed_tables {
            let class_name = to_pascal_case(table_name);
            writeln!(src, "from .{table_name} import {class_name}")?;
        }
    }

    // SQL constants
    writeln!(src)?;
    for query in queries {
        let const_name = sql_const_name(&query.name);
        let sql = python_sql(&query.sql)
            .replace('"', "\\\"")
            .replace('\n', " ");
        let sql = sql.trim_end().trim_end_matches(';');
        writeln!(src, r#"{const_name} = "{sql}""#)?;
    }

    // Query functions
    for query in queries {
        writeln!(src)?;
        writeln!(src)?;
        if infer_table(query, schema).is_none() && !query.result_columns.is_empty() {
            emit_row_dataclass(&mut src, query)?;
            writeln!(src)?;
            writeln!(src)?;
        }
        emit_python_query(&mut src, query, schema)?;
    }

    Ok(src)
}

fn emit_row_dataclass(src: &mut String, query: &Query) -> anyhow::Result<()> {
    let name = row_class_name(&query.name);
    writeln!(src, "@dataclasses.dataclass")?;
    writeln!(src, "class {name}:")?;
    for col in &query.result_columns {
        let ty = python_type(&col.sql_type, col.nullable);
        writeln!(src, "    {}: {}", col.name, ty)?;
    }
    Ok(())
}

fn emit_python_query(src: &mut String, query: &Query, schema: &Schema) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&query.name);
    let const_name = sql_const_name(&query.name);

    let return_type = match query.cmd {
        QueryCmd::One => {
            let row_type = result_row_type(query, schema);
            format!("{row_type} | None")
        }
        QueryCmd::Many => {
            let row_type = result_row_type(query, schema);
            format!("list[{row_type}]")
        }
        QueryCmd::Exec => "None".to_string(),
        QueryCmd::ExecRows => "int".to_string(),
    };

    let params_sig: String = std::iter::once("conn: psycopg.Connection".to_string())
        .chain(query.params.iter().map(|p| {
            format!(
                "{}: {}",
                to_snake_case(&p.name),
                python_type(&p.sql_type, p.nullable)
            )
        }))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;
    writeln!(src, "    with conn.cursor() as cur:")?;

    if query.params.is_empty() {
        writeln!(src, "        cur.execute({const_name})")?;
    } else {
        let args: Vec<String> = query
            .params
            .iter()
            .map(|p| to_snake_case(&p.name))
            .collect();
        let tuple = if args.len() == 1 {
            format!("({},)", args[0])
        } else {
            format!("({})", args.join(", "))
        };
        writeln!(src, "        cur.execute({const_name}, {tuple})")?;
    }

    match query.cmd {
        QueryCmd::Exec => {}
        QueryCmd::ExecRows => {
            writeln!(src, "        return cur.rowcount")?;
        }
        QueryCmd::One => {
            let row_type = result_row_type(query, schema);
            writeln!(src, "        row = cur.fetchone()")?;
            writeln!(src, "        if row is None:")?;
            writeln!(src, "            return None")?;
            writeln!(src, "        return {row_type}(*row)")?;
        }
        QueryCmd::Many => {
            let row_type = result_row_type(query, schema);
            writeln!(
                src,
                "        return [{row_type}(*row) for row in cur.fetchall()]"
            )?;
        }
    }

    Ok(())
}

// ─── Type helpers ─────────────────────────────────────────────────────────────

fn python_type(sql_type: &SqlType, nullable: bool) -> String {
    let base = match sql_type {
        SqlType::Boolean => "bool".to_string(),
        SqlType::SmallInt | SqlType::Integer | SqlType::BigInt => "int".to_string(),
        SqlType::Real | SqlType::Double => "float".to_string(),
        SqlType::Decimal => "decimal.Decimal".to_string(),
        SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) => "str".to_string(),
        SqlType::Bytes => "bytes".to_string(),
        SqlType::Date => "datetime.date".to_string(),
        SqlType::Time => "datetime.time".to_string(),
        SqlType::Timestamp | SqlType::TimestampTz => "datetime.datetime".to_string(),
        SqlType::Interval => "datetime.timedelta".to_string(),
        SqlType::Uuid => "uuid.UUID".to_string(),
        SqlType::Json | SqlType::Jsonb => "Any".to_string(),
        SqlType::Array(inner) => {
            let inner_ty = python_type(inner, false);
            let list_ty = format!("list[{inner_ty}]");
            return if nullable {
                format!("{list_ty} | None")
            } else {
                list_ty
            };
        }
        SqlType::Custom(_) => "Any".to_string(),
    };
    if nullable {
        format!("{base} | None")
    } else {
        base
    }
}

#[derive(Default)]
struct TypeImports {
    decimal: bool,
    datetime: bool,
    uuid: bool,
    any_type: bool,
}

impl TypeImports {
    fn scan(&mut self, ty: &SqlType) {
        match ty {
            SqlType::Decimal => self.decimal = true,
            SqlType::Date
            | SqlType::Time
            | SqlType::Timestamp
            | SqlType::TimestampTz
            | SqlType::Interval => self.datetime = true,
            SqlType::Uuid => self.uuid = true,
            SqlType::Json | SqlType::Jsonb | SqlType::Custom(_) => self.any_type = true,
            SqlType::Array(inner) => self.scan(inner),
            _ => {}
        }
    }

    fn write(&self, src: &mut String) -> anyhow::Result<()> {
        if self.decimal {
            writeln!(src, "import decimal")?;
        }
        if self.datetime {
            writeln!(src, "import datetime")?;
        }
        if self.uuid {
            writeln!(src, "import uuid")?;
        }
        if self.any_type {
            writeln!(src, "from typing import Any")?;
        }
        Ok(())
    }
}

// ─── SQL helpers ──────────────────────────────────────────────────────────────

/// Replace PostgreSQL `$N` or SQLite `?N` placeholders with psycopg `%s` markers.
fn python_sql(sql: &str) -> String {
    let mut out = String::with_capacity(sql.len());
    let mut chars = sql.chars().peekable();
    while let Some(ch) = chars.next() {
        if (ch == '$' || ch == '?') && chars.peek().is_some_and(|c| c.is_ascii_digit()) {
            out.push_str("%s");
            while chars.peek().is_some_and(|c| c.is_ascii_digit()) {
                chars.next();
            }
        } else {
            out.push(ch);
        }
    }
    out
}

// ─── Row helpers ──────────────────────────────────────────────────────────────

fn infer_table<'a>(query: &Query, schema: &'a Schema) -> Option<&'a str> {
    for table in &schema.tables {
        if table.columns.len() == query.result_columns.len()
            && table
                .columns
                .iter()
                .zip(&query.result_columns)
                .all(|(a, b)| a.name == b.name)
        {
            return Some(&table.name);
        }
    }
    None
}

fn result_row_type(query: &Query, schema: &Schema) -> String {
    if let Some(table_name) = infer_table(query, schema) {
        return to_pascal_case(table_name);
    }
    if !query.result_columns.is_empty() {
        return row_class_name(&query.name);
    }
    "Any".to_string()
}

fn row_class_name(query_name: &str) -> String {
    format!("{}Row", to_pascal_case(query_name))
}

fn sql_const_name(query_name: &str) -> String {
    format!("SQL_{}", to_snake_case(query_name).to_uppercase())
}

// ─── Name helpers ─────────────────────────────────────────────────────────────

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.extend(c.to_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}
