use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::common::{
    infer_table, jdbc_sql, positional_bind_names, replace_list_in_clause, split_at_in_clause, sql_const_name, to_camel_case, to_pascal_case,
};
use crate::backend::{Codegen, GeneratedFile};
use crate::config::{ListParamStrategy, OutputConfig};
use crate::ir::{Parameter, Query, QueryCmd, Schema, SqlType, Table};

/// Database engine and npm driver to target for JS/TS output.
pub enum JsTarget {
    /// PostgreSQL via node-postgres (`pg`).
    Postgres,
    /// SQLite via better-sqlite3.
    Sqlite,
    /// MySQL via mysql2.
    Mysql,
}

/// Whether to emit TypeScript (inline types) or JavaScript (JSDoc annotations).
pub enum JsOutput {
    TypeScript,
    JavaScript,
}

/// Code generator for the `"typescript"` and `"javascript"` gen keys.
///
/// Both keys route to this struct with the appropriate [`JsOutput`] variant.
/// TypeScript emits inline type annotations; JavaScript emits JSDoc instead.
pub struct TypeScriptCodegen {
    /// Database driver target.
    pub target: JsTarget,
    /// TypeScript or JavaScript output mode.
    pub output: JsOutput,
}

impl Codegen for TypeScriptCodegen {
    fn generate(&self, schema: &Schema, queries: &[Query], config: &OutputConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let ext = self.ext();
        let mut files = Vec::new();
        for table in &schema.tables {
            let content = self.emit_model_file(table)?;
            files.push(GeneratedFile { path: PathBuf::from(&config.out).join(format!("{}.{ext}", table.name)), content });
        }
        if !queries.is_empty() {
            let content = build_queries_file(queries, schema, &self.target, &self.output, config)?;
            files.push(GeneratedFile { path: PathBuf::from(&config.out).join(format!("queries.{ext}")), content });
        }
        let index_content = self.emit_index_file(schema, !queries.is_empty())?;
        files.push(GeneratedFile { path: PathBuf::from(&config.out).join(format!("index.{ext}")), content: index_content });
        Ok(files)
    }
}

impl TypeScriptCodegen {
    /// Returns the file extension: `"ts"` for TypeScript, `"js"` for JavaScript.
    fn ext(&self) -> &'static str {
        match self.output {
            JsOutput::TypeScript => "ts",
            JsOutput::JavaScript => "js",
        }
    }

    fn emit_model_file(&self, table: &Table) -> anyhow::Result<String> {
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        let name = to_pascal_case(&table.name);
        let fields: Vec<(&str, &SqlType, bool)> = table.columns.iter().map(|c| (c.name.as_str(), &c.sql_type, c.nullable)).collect();
        match self.output {
            JsOutput::TypeScript => emit_ts_interface(&mut src, &name, &fields)?,
            JsOutput::JavaScript => emit_js_typedef(&mut src, &name, &fields)?,
        }
        Ok(src)
    }

    fn emit_index_file(&self, schema: &Schema, has_queries: bool) -> anyhow::Result<String> {
        // TypeScript imports must not use .ts extensions; JS (ESM) requires .js.
        let import_ext = match self.output {
            JsOutput::TypeScript => "",
            JsOutput::JavaScript => ".js",
        };
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        for table in &schema.tables {
            writeln!(src, "export * from './{}{import_ext}';", table.name)?;
        }
        if has_queries {
            writeln!(src, "export * from './queries{import_ext}';")?;
        }
        Ok(src)
    }
}

// ─── Type emission ────────────────────────────────────────────────────────────

/// Emit a TypeScript `interface` block for the given fields.
fn emit_ts_interface(src: &mut String, name: &str, fields: &[(&str, &SqlType, bool)]) -> anyhow::Result<()> {
    writeln!(src, "export interface {name} {{")?;
    for (fname, ftype, nullable) in fields {
        writeln!(src, "  {fname}: {};", js_type(ftype, *nullable))?;
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Emit a JSDoc `@typedef` block for the given fields.
fn emit_js_typedef(src: &mut String, name: &str, fields: &[(&str, &SqlType, bool)]) -> anyhow::Result<()> {
    writeln!(src, "/**")?;
    writeln!(src, " * @typedef {{Object}} {name}")?;
    for (fname, ftype, nullable) in fields {
        let ty = js_type(ftype, *nullable);
        writeln!(src, " * @property {{{ty}}} {fname}")?;
    }
    writeln!(src, " */")?;
    Ok(())
}

/// Emit the inline row type for a query whose result doesn't match any schema table.
fn emit_inline_row_type(src: &mut String, query: &Query, output: &JsOutput) -> anyhow::Result<()> {
    let name = format!("{}Row", to_pascal_case(&query.name));
    let fields: Vec<(&str, &SqlType, bool)> = query.result_columns.iter().map(|c| (c.name.as_str(), &c.sql_type, c.nullable)).collect();
    match output {
        JsOutput::TypeScript => emit_ts_interface(src, &name, &fields),
        JsOutput::JavaScript => emit_js_typedef(src, &name, &fields),
    }
}

/// Map a SQL type to its JavaScript/TypeScript type string.
fn js_type(sql_type: &SqlType, nullable: bool) -> String {
    let base = js_base_type(sql_type);
    if nullable {
        format!("{base} | null")
    } else {
        base
    }
}

fn js_base_type(sql_type: &SqlType) -> String {
    match sql_type {
        SqlType::Boolean => "boolean".to_string(),
        SqlType::SmallInt | SqlType::Integer | SqlType::BigInt => "number".to_string(),
        SqlType::Real | SqlType::Double | SqlType::Decimal => "number".to_string(),
        SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) => "string".to_string(),
        SqlType::Interval | SqlType::Uuid => "string".to_string(),
        SqlType::Bytes => "Buffer".to_string(),
        SqlType::Date | SqlType::Time | SqlType::Timestamp | SqlType::TimestampTz => "Date".to_string(),
        SqlType::Json | SqlType::Jsonb => "unknown".to_string(),
        SqlType::Array(inner) => format!("{}[]", js_base_type(inner)),
        SqlType::Custom(_) => "unknown".to_string(),
    }
}

// ─── Queries file ─────────────────────────────────────────────────────────────

fn build_queries_file(queries: &[Query], schema: &Schema, target: &JsTarget, output: &JsOutput, config: &OutputConfig) -> anyhow::Result<String> {
    let strategy = config.list_params.clone().unwrap_or_default();
    let mut src = String::new();
    writeln!(src, "// Generated by sqltgen. Do not edit.")?;
    emit_driver_header(&mut src, target, output)?;
    emit_table_imports(&mut src, &needed_tables(queries, schema), output)?;
    writeln!(src)?;
    emit_sql_constants(&mut src, queries, target, &strategy)?;
    for query in queries {
        writeln!(src)?;
        if infer_table(query, schema).is_none() && !query.result_columns.is_empty() {
            emit_inline_row_type(&mut src, query, output)?;
            writeln!(src)?;
        }
        emit_query(&mut src, query, schema, target, output, &strategy)?;
    }
    Ok(src)
}

/// Collect the names of schema tables used as return types by any query.
fn needed_tables<'a>(queries: &[Query], schema: &'a Schema) -> BTreeSet<&'a str> {
    let mut set = BTreeSet::new();
    for query in queries {
        if let Some(name) = infer_table(query, schema) {
            set.insert(name);
        }
    }
    set
}

/// Emit driver import (TS) or typedef (JS) at the top of the queries file.
fn emit_driver_header(src: &mut String, target: &JsTarget, output: &JsOutput) -> anyhow::Result<()> {
    writeln!(src, "// Runtime: {}", driver_install_hint(target))?;
    writeln!(src)?;
    match output {
        JsOutput::TypeScript => match target {
            JsTarget::Postgres => writeln!(src, "import type {{ ClientBase }} from 'pg';")?,
            JsTarget::Sqlite => writeln!(src, "import type {{ Database }} from 'better-sqlite3';")?,
            JsTarget::Mysql => writeln!(src, "import type {{ Connection, ResultSetHeader, RowDataPacket }} from 'mysql2/promise';")?,
        },
        JsOutput::JavaScript => match target {
            JsTarget::Postgres => writeln!(src, "/** @typedef {{import('pg').ClientBase}} ClientBase */")?,
            JsTarget::Sqlite => writeln!(src, "/** @typedef {{import('better-sqlite3').Database}} Database */")?,
            JsTarget::Mysql => {
                writeln!(src, "/** @typedef {{import('mysql2/promise').Connection}} Connection */")?;
                writeln!(src, "/** @typedef {{import('mysql2/promise').ResultSetHeader}} ResultSetHeader */")?;
            },
        },
    }
    Ok(())
}

fn driver_install_hint(target: &JsTarget) -> &'static str {
    match target {
        JsTarget::Postgres => "pg (node-postgres) — npm install pg",
        JsTarget::Sqlite => "better-sqlite3 — npm install better-sqlite3",
        JsTarget::Mysql => "mysql2 — npm install mysql2",
    }
}

/// Emit table type imports into the queries file.
fn emit_table_imports(src: &mut String, tables: &BTreeSet<&str>, output: &JsOutput) -> anyhow::Result<()> {
    if tables.is_empty() {
        return Ok(());
    }
    writeln!(src)?;
    for name in tables {
        let class_name = to_pascal_case(name);
        match output {
            JsOutput::TypeScript => writeln!(src, "import type {{ {class_name} }} from './{name}';")?,
            JsOutput::JavaScript => writeln!(src, "/** @typedef {{import('./{name}.js').{class_name}}} {class_name} */")?,
        }
    }
    Ok(())
}

/// Emit SQL string constants for all non-dynamic-list queries.
fn emit_sql_constants(src: &mut String, queries: &[Query], target: &JsTarget, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    for query in queries {
        if query.params.iter().any(|p| p.is_list) && *strategy == ListParamStrategy::Dynamic {
            continue;
        }
        let const_name = sql_const_name(&query.name);
        let base_sql = match query.params.iter().find(|p| p.is_list) {
            Some(lp) => rewrite_list_sql_native(&query.sql, lp, target),
            None => query.sql.clone(),
        };
        let sql = rewrite_placeholders(&base_sql, target).replace('"', "\\\"").replace('\n', " ");
        let sql = sql.trim_end().trim_end_matches(';');
        writeln!(src, r#"const {const_name} = "{sql}";"#)?;
    }
    Ok(())
}

/// Rewrite `$N`/`?N` placeholders for the target driver.
/// PostgreSQL keeps `$N`, SQLite and MySQL rewrite to anonymous `?`.
fn rewrite_placeholders(sql: &str, target: &JsTarget) -> String {
    match target {
        JsTarget::Postgres => sql.to_string(),
        JsTarget::Sqlite | JsTarget::Mysql => jdbc_sql(sql),
    }
}

/// Rewrite the `IN ($N)` / `IN (?N)` list-param placeholder to the native driver form.
fn rewrite_list_sql_native(sql: &str, lp: &Parameter, target: &JsTarget) -> String {
    let replacement = match target {
        JsTarget::Postgres => format!("= ANY(${})", lp.index),
        JsTarget::Sqlite => format!("IN (SELECT value FROM json_each(?{}))", lp.index),
        JsTarget::Mysql => {
            let col_type = mysql_json_col_type(&lp.sql_type);
            format!("IN (SELECT value FROM JSON_TABLE(?,'$[*]' COLUMNS(value {col_type} PATH '$')) t)")
        },
    };
    replace_list_in_clause(sql, lp.index, &replacement).unwrap_or_else(|| {
        eprintln!("warning: list param '{}' not found in IN clause, treating as scalar", lp.name);
        sql.to_string()
    })
}

fn mysql_json_col_type(sql_type: &SqlType) -> &'static str {
    match sql_type {
        SqlType::Boolean => "BOOLEAN",
        SqlType::SmallInt => "SMALLINT",
        SqlType::Integer => "INT",
        SqlType::BigInt => "BIGINT",
        SqlType::Real => "FLOAT",
        SqlType::Double => "DOUBLE",
        SqlType::Decimal => "DECIMAL(38,10)",
        _ => "CHAR(255)",
    }
}

// ─── Query function emission ──────────────────────────────────────────────────

fn emit_query(src: &mut String, query: &Query, schema: &Schema, target: &JsTarget, output: &JsOutput, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    match target {
        JsTarget::Postgres => emit_pg_query(src, query, schema, output, strategy),
        JsTarget::Sqlite => emit_sqlite_query(src, query, schema, output, strategy),
        JsTarget::Mysql => emit_mysql_query(src, query, schema, output, strategy),
    }
}

/// Emit the JSDoc annotation block for a query function (JS output only).
fn emit_jsdoc(src: &mut String, conn_type: &str, params: &[&Parameter], return_type: &str, output: &JsOutput) -> anyhow::Result<()> {
    if matches!(output, JsOutput::TypeScript) {
        return Ok(());
    }
    writeln!(src, "/**")?;
    writeln!(src, " * @param {{{conn_type}}} db")?;
    for p in params {
        let ty = if p.is_list { format!("{}[]", js_type(&p.sql_type, false)) } else { js_type(&p.sql_type, p.nullable) };
        writeln!(src, " * @param {{{ty}}} {}", to_camel_case(&p.name))?;
    }
    writeln!(src, " * @returns {{Promise<{return_type}>}}")?;
    writeln!(src, " */")?;
    Ok(())
}

/// Emit the `export async function` opening line.
/// TypeScript includes type annotations; JavaScript uses plain parameter names.
fn emit_fn_open(src: &mut String, fn_name: &str, conn_type: &str, params: &[&Parameter], return_type: &str, output: &JsOutput) -> anyhow::Result<()> {
    match output {
        JsOutput::TypeScript => {
            let typed: Vec<String> = params
                .iter()
                .map(|p| {
                    let ty = if p.is_list { format!("{}[]", js_type(&p.sql_type, false)) } else { js_type(&p.sql_type, p.nullable) };
                    format!("{}: {ty}", to_camel_case(&p.name))
                })
                .collect();
            let sig = std::iter::once(format!("db: {conn_type}")).chain(typed).collect::<Vec<_>>().join(", ");
            writeln!(src, "export async function {fn_name}({sig}): Promise<{return_type}> {{")?;
        },
        JsOutput::JavaScript => {
            let names: Vec<String> = std::iter::once("db".to_string()).chain(params.iter().map(|p| to_camel_case(&p.name))).collect();
            writeln!(src, "export async function {fn_name}({}) {{", names.join(", "))?;
        },
    }
    Ok(())
}

/// Compute the JS/TS return type string for a query.
fn return_type(query: &Query, schema: &Schema) -> String {
    let row = row_type_name(query, schema);
    match query.cmd {
        QueryCmd::One => format!("{row} | null"),
        QueryCmd::Many => format!("{row}[]"),
        QueryCmd::Exec => "void".to_string(),
        QueryCmd::ExecRows => "number".to_string(),
    }
}

/// Compute the row type name for a query result (table name or `{Query}Row`).
fn row_type_name(query: &Query, schema: &Schema) -> String {
    if let Some(table_name) = infer_table(query, schema) {
        return to_pascal_case(table_name);
    }
    format!("{}Row", to_pascal_case(&query.name))
}

// ─── PostgreSQL (pg) ─────────────────────────────────────────────────────────

fn emit_pg_query(src: &mut String, query: &Query, schema: &Schema, output: &JsOutput, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = query.params.iter().find(|p| p.is_list) {
        return emit_pg_list_query(src, query, schema, output, strategy, lp);
    }
    let fn_name = to_camel_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let ret = return_type(query, schema);
    let params: Vec<&Parameter> = query.params.iter().collect();
    emit_jsdoc(src, "ClientBase", &params, &ret, output)?;
    emit_fn_open(src, &fn_name, "ClientBase", &params, &ret, output)?;
    let args = pg_params_array(query);
    match query.cmd {
        QueryCmd::Exec => writeln!(src, "  await db.query({const_name}, {args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = await db.query({const_name}, {args});")?;
            writeln!(src, "  return result.rowCount ?? 0;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(query, schema);
            let call = pg_query_call(&const_name, &row, &args, output);
            writeln!(src, "  const result = await {call};")?;
            writeln!(src, "  return result.rows[0] ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(query, schema);
            let call = pg_query_call(&const_name, &row, &args, output);
            writeln!(src, "  const result = await {call};")?;
            writeln!(src, "  return result.rows;")?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build `db.query<Row>(sql, args)` for TypeScript or `db.query(sql, args)` for JavaScript.
fn pg_query_call(const_name: &str, row_type: &str, args: &str, output: &JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!("db.query<{row_type}>({const_name}, {args})"),
        JsOutput::JavaScript => format!("db.query({const_name}, {args})"),
    }
}

/// Build the `[p1, p2, ...]` params array for a pg query (unique params by index).
fn pg_params_array(query: &Query) -> String {
    let mut params: Vec<&Parameter> = query.params.iter().collect();
    params.sort_by_key(|p| p.index);
    let names: Vec<String> = params.iter().map(|p| to_camel_case(&p.name)).collect();
    format!("[{}]", names.join(", "))
}

fn emit_pg_list_query(src: &mut String, query: &Query, schema: &Schema, output: &JsOutput, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let fn_name = to_camel_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let ret = return_type(query, schema);
    let params: Vec<&Parameter> = query.params.iter().collect();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, "ClientBase", &params, &ret, output)?;
    emit_fn_open(src, &fn_name, "ClientBase", &params, &ret, output)?;
    match strategy {
        ListParamStrategy::Native => {
            // pg accepts a JS array directly for = ANY($N)
            let args = pg_params_array(query);
            let row = row_type_name(query, schema);
            let call = pg_query_call(&const_name, &row, &args, output);
            match query.cmd {
                QueryCmd::Exec => writeln!(src, "  await db.query({const_name}, {args});")?,
                QueryCmd::ExecRows => {
                    writeln!(src, "  const result = await db.query({const_name}, {args});")?;
                    writeln!(src, "  return result.rowCount ?? 0;")?;
                },
                QueryCmd::One => {
                    writeln!(src, "  const result = await {call};")?;
                    writeln!(src, "  return result.rows[0] ?? null;")?;
                },
                QueryCmd::Many => {
                    writeln!(src, "  const result = await {call};")?;
                    writeln!(src, "  return result.rows;")?;
                },
            }
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&query.sql, lp.index).unwrap_or_else(|| (query.sql.clone(), String::new()));
            let before = before_raw.replace('"', "\\\"").replace('\n', " ");
            let after = after_raw.replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            // Placeholder offset: list param starts at position (scalars before lp + 1)
            let offset = scalar_params.iter().filter(|p| p.index < lp.index).count() + 1;
            writeln!(src, "  const placeholders = {lp_name}.map((_, i) => '$' + ({offset} + i)).join(', ');")?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_camel_case(&p.name)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_camel_case(&p.name)).collect();
            let all_args = [before_args, vec![format!("...{lp_name}")], after_args].concat().join(", ");
            let row = row_type_name(query, schema);
            let call = pg_query_call("sql", &row, &format!("[{all_args}]"), output);
            match query.cmd {
                QueryCmd::Exec => writeln!(src, "  await db.query(sql, [{all_args}]);")?,
                QueryCmd::ExecRows => {
                    writeln!(src, "  const result = await db.query(sql, [{all_args}]);")?;
                    writeln!(src, "  return result.rowCount ?? 0;")?;
                },
                QueryCmd::One => {
                    writeln!(src, "  const result = await {call};")?;
                    writeln!(src, "  return result.rows[0] ?? null;")?;
                },
                QueryCmd::Many => {
                    writeln!(src, "  const result = await {call};")?;
                    writeln!(src, "  return result.rows;")?;
                },
            }
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

// ─── SQLite (better-sqlite3) ─────────────────────────────────────────────────

fn emit_sqlite_query(src: &mut String, query: &Query, schema: &Schema, output: &JsOutput, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = query.params.iter().find(|p| p.is_list) {
        return emit_sqlite_list_query(src, query, schema, output, strategy, lp);
    }
    let fn_name = to_camel_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let ret = return_type(query, schema);
    let params: Vec<&Parameter> = query.params.iter().collect();
    emit_jsdoc(src, "Database", &params, &ret, output)?;
    emit_fn_open(src, &fn_name, "Database", &params, &ret, output)?;
    let args = sqlite_spread_args(query);
    match query.cmd {
        QueryCmd::Exec => writeln!(src, "  db.prepare({const_name}).run({args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = db.prepare({const_name}).run({args});")?;
            writeln!(src, "  return result.changes;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(query, schema);
            let cast = sqlite_cast(&format!("{row} | undefined"), output);
            writeln!(src, "  const row = db.prepare({const_name}).get({args}){cast};")?;
            writeln!(src, "  return row ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(query, schema);
            let cast = sqlite_cast(&format!("{row}[]"), output);
            writeln!(src, "  return db.prepare({const_name}).all({args}){cast};")?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the spread argument list for a better-sqlite3 prepared statement call.
///
/// better-sqlite3 uses anonymous `?` placeholders; the arg list must follow the SQL
/// occurrence order including repeated params (e.g. a `@genre` used twice → two args).
fn sqlite_spread_args(query: &Query) -> String {
    positional_bind_names(query).iter().map(|&n| to_camel_case(n)).collect::<Vec<_>>().join(", ")
}

/// Returns ` as Type` for TypeScript or empty string for JavaScript.
fn sqlite_cast(ts_type: &str, output: &JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!(" as {ts_type}"),
        JsOutput::JavaScript => String::new(),
    }
}

fn emit_sqlite_list_query(
    src: &mut String,
    query: &Query,
    schema: &Schema,
    output: &JsOutput,
    strategy: &ListParamStrategy,
    lp: &Parameter,
) -> anyhow::Result<()> {
    let fn_name = to_camel_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let ret = return_type(query, schema);
    let params: Vec<&Parameter> = query.params.iter().collect();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, "Database", &params, &ret, output)?;
    emit_fn_open(src, &fn_name, "Database", &params, &ret, output)?;
    match strategy {
        ListParamStrategy::Native => {
            writeln!(src, "  const {lp_name}Json = JSON.stringify({lp_name});")?;
            let args = sqlite_list_spread_args(query, lp, &format!("{lp_name}Json"));
            emit_sqlite_body(src, query, schema, &const_name, &args, output)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&query.sql, lp.index).unwrap_or_else(|| (query.sql.clone(), String::new()));
            // Rewrite $N → ? for any scalar params that appear before/after the list.
            let before = jdbc_sql(&before_raw).replace('"', "\\\"").replace('\n', " ");
            let after = jdbc_sql(&after_raw).replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            writeln!(src, r#"  const placeholders = {lp_name}.map(() => "?").join(", ");"#)?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_camel_case(&p.name)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_camel_case(&p.name)).collect();
            let all_args = [before_args, vec![format!("...{lp_name}")], after_args].concat().join(", ");
            emit_sqlite_body(src, query, schema, "sql", &all_args, output)?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the spread args string for a SQLite native-list query.
///
/// Follows SQL occurrence order (via [`positional_bind_names`]), substituting the list
/// param's JSON expression wherever that param's name would appear.
fn sqlite_list_spread_args(query: &Query, lp: &Parameter, lp_expr: &str) -> String {
    let lp_camel = to_camel_case(&lp.name);
    positional_bind_names(query)
        .iter()
        .map(|&n| {
            let cn = to_camel_case(n);
            if cn == lp_camel {
                lp_expr.to_string()
            } else {
                cn
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_sqlite_body(src: &mut String, query: &Query, schema: &Schema, sql_expr: &str, args: &str, output: &JsOutput) -> anyhow::Result<()> {
    match query.cmd {
        QueryCmd::Exec => writeln!(src, "  db.prepare({sql_expr}).run({args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = db.prepare({sql_expr}).run({args});")?;
            writeln!(src, "  return result.changes;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(query, schema);
            let cast = sqlite_cast(&format!("{row} | undefined"), output);
            writeln!(src, "  const row = db.prepare({sql_expr}).get({args}){cast};")?;
            writeln!(src, "  return row ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(query, schema);
            let cast = sqlite_cast(&format!("{row}[]"), output);
            writeln!(src, "  return db.prepare({sql_expr}).all({args}){cast};")?;
        },
    }
    Ok(())
}

// ─── MySQL (mysql2) ───────────────────────────────────────────────────────────

fn emit_mysql_query(src: &mut String, query: &Query, schema: &Schema, output: &JsOutput, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = query.params.iter().find(|p| p.is_list) {
        return emit_mysql_list_query(src, query, schema, output, strategy, lp);
    }
    let fn_name = to_camel_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let ret = return_type(query, schema);
    let params: Vec<&Parameter> = query.params.iter().collect();
    emit_jsdoc(src, "Connection", &params, &ret, output)?;
    emit_fn_open(src, &fn_name, "Connection", &params, &ret, output)?;
    let args = mysql_params_array(query);
    emit_mysql_body(src, query, schema, &const_name, &args, output)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the `[p1, p2, ...]` params array for mysql2 (positional `?`, params in SQL order).
fn mysql_params_array(query: &Query) -> String {
    let names: Vec<String> = positional_bind_names(query).iter().map(|&n| to_camel_case(n)).collect();
    format!("[{}]", names.join(", "))
}

fn emit_mysql_body(src: &mut String, query: &Query, schema: &Schema, sql_expr: &str, args: &str, output: &JsOutput) -> anyhow::Result<()> {
    match query.cmd {
        QueryCmd::Exec => writeln!(src, "  await db.execute({sql_expr}, {args});")?,
        QueryCmd::ExecRows => {
            let rsh = mysql_generic(output, "ResultSetHeader");
            writeln!(src, "  const [result] = await db.execute{rsh}({sql_expr}, {args});")?;
            writeln!(src, "  return result.affectedRows;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(query, schema);
            let rdp = mysql_generic(output, "RowDataPacket[]");
            let cast = mysql_cast(&format!("{row} | undefined"), output);
            writeln!(src, "  const [rows] = await db.execute{rdp}({sql_expr}, {args});")?;
            writeln!(src, "  return (rows[0]{cast}) ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(query, schema);
            let rdp = mysql_generic(output, "RowDataPacket[]");
            let cast = mysql_cast(&format!("{row}[]"), output);
            writeln!(src, "  const [rows] = await db.execute{rdp}({sql_expr}, {args});")?;
            writeln!(src, "  return rows{cast};")?;
        },
    }
    Ok(())
}

/// Returns `<Type>` (TS) or empty string (JS) for a mysql2 generic type parameter.
fn mysql_generic(output: &JsOutput, ts_type: &str) -> String {
    match output {
        JsOutput::TypeScript => format!("<{ts_type}>"),
        JsOutput::JavaScript => String::new(),
    }
}

/// Returns ` as Type` (TS) or empty string (JS) for a mysql2 type cast.
fn mysql_cast(ts_type: &str, output: &JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!(" as {ts_type}"),
        JsOutput::JavaScript => String::new(),
    }
}

fn emit_mysql_list_query(
    src: &mut String,
    query: &Query,
    schema: &Schema,
    output: &JsOutput,
    strategy: &ListParamStrategy,
    lp: &Parameter,
) -> anyhow::Result<()> {
    let fn_name = to_camel_case(&query.name);
    let const_name = sql_const_name(&query.name);
    let ret = return_type(query, schema);
    let params: Vec<&Parameter> = query.params.iter().collect();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, "Connection", &params, &ret, output)?;
    emit_fn_open(src, &fn_name, "Connection", &params, &ret, output)?;
    match strategy {
        ListParamStrategy::Native => {
            writeln!(src, "  const {lp_name}Json = JSON.stringify({lp_name});")?;
            let args = mysql_list_params_array(query, lp, &format!("{lp_name}Json"));
            emit_mysql_body(src, query, schema, &const_name, &args, output)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&query.sql, lp.index).unwrap_or_else(|| (query.sql.clone(), String::new()));
            let before = jdbc_sql(&before_raw).replace('"', "\\\"").replace('\n', " ");
            let after = jdbc_sql(&after_raw).replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            writeln!(src, r#"  const placeholders = {lp_name}.map(() => "?").join(", ");"#)?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_camel_case(&p.name)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_camel_case(&p.name)).collect();
            let all_args = [before_args, vec![format!("...{lp_name}")], after_args].concat().join(", ");
            emit_mysql_body(src, query, schema, "sql", &format!("[{all_args}]"), output)?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the `[p1, p2, ...]` array for a MySQL native list query,
/// substituting the JSON-stringified expression for the list param slot.
fn mysql_list_params_array(query: &Query, lp: &Parameter, lp_expr: &str) -> String {
    let mut params: Vec<&Parameter> = query.params.iter().collect();
    params.sort_by_key(|p| p.index);
    let names: Vec<String> = params.iter().map(|p| if p.index == lp.index { lp_expr.to_string() } else { to_camel_case(&p.name) }).collect();
    format!("[{}]", names.join(", "))
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::{Column, Parameter, Query, QueryCmd, ResultColumn, Schema, SqlType, Table};

    fn schema_with_users() -> Schema {
        Schema {
            tables: vec![Table {
                name: "users".to_string(),
                columns: vec![
                    Column { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false, is_primary_key: true },
                    Column { name: "name".to_string(), sql_type: SqlType::Text, nullable: false, is_primary_key: false },
                    Column { name: "email".to_string(), sql_type: SqlType::VarChar(Some(255)), nullable: true, is_primary_key: false },
                ],
            }],
        }
    }

    fn get_user_query() -> Query {
        Query {
            name: "GetUser".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT id, name, email FROM users WHERE id = $1".to_string(),
            params: vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "email".to_string(), sql_type: SqlType::VarChar(Some(255)), nullable: true },
            ],
        }
    }

    fn list_users_query() -> Query {
        Query {
            name: "ListUsers".to_string(),
            cmd: QueryCmd::Many,
            sql: "SELECT id, name, email FROM users".to_string(),
            params: vec![],
            result_columns: vec![
                ResultColumn { name: "id".to_string(), sql_type: SqlType::BigInt, nullable: false },
                ResultColumn { name: "name".to_string(), sql_type: SqlType::Text, nullable: false },
                ResultColumn { name: "email".to_string(), sql_type: SqlType::VarChar(Some(255)), nullable: true },
            ],
        }
    }

    fn delete_user_query() -> Query {
        Query {
            name: "DeleteUser".to_string(),
            cmd: QueryCmd::Exec,
            sql: "DELETE FROM users WHERE id = $1".to_string(),
            params: vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
            result_columns: vec![],
        }
    }

    fn delete_users_query() -> Query {
        Query {
            name: "DeleteUsers".to_string(),
            cmd: QueryCmd::ExecRows,
            sql: "DELETE FROM users WHERE id = $1".to_string(),
            params: vec![Parameter::scalar(1, "id", SqlType::BigInt, false)],
            result_columns: vec![],
        }
    }

    fn config() -> OutputConfig {
        OutputConfig { out: "src".to_string(), package: String::new(), list_params: None }
    }

    // ─── js_type ─────────────────────────────────────────────────────────────

    #[test]
    fn test_js_type_primitives() {
        assert_eq!(js_type(&SqlType::Boolean, false), "boolean");
        assert_eq!(js_type(&SqlType::Integer, false), "number");
        assert_eq!(js_type(&SqlType::BigInt, false), "number");
        assert_eq!(js_type(&SqlType::Text, false), "string");
        assert_eq!(js_type(&SqlType::Uuid, false), "string");
        assert_eq!(js_type(&SqlType::Bytes, false), "Buffer");
        assert_eq!(js_type(&SqlType::Date, false), "Date");
        assert_eq!(js_type(&SqlType::Timestamp, false), "Date");
        assert_eq!(js_type(&SqlType::Json, false), "unknown");
    }

    #[test]
    fn test_js_type_nullable() {
        assert_eq!(js_type(&SqlType::Text, true), "string | null");
        assert_eq!(js_type(&SqlType::BigInt, true), "number | null");
    }

    #[test]
    fn test_js_type_array() {
        assert_eq!(js_type(&SqlType::Array(Box::new(SqlType::Integer)), false), "number[]");
        assert_eq!(js_type(&SqlType::Array(Box::new(SqlType::Text)), true), "string[] | null");
    }

    // ─── model file ──────────────────────────────────────────────────────────

    #[test]
    fn test_ts_model_file_interface() {
        let schema = schema_with_users();
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::TypeScript };
        let content = gen.emit_model_file(&schema.tables[0]).unwrap();
        assert!(content.contains("export interface Users {"));
        assert!(content.contains("id: number;"));
        assert!(content.contains("name: string;"));
        assert!(content.contains("email: string | null;"));
    }

    #[test]
    fn test_js_model_file_typedef() {
        let schema = schema_with_users();
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::JavaScript };
        let content = gen.emit_model_file(&schema.tables[0]).unwrap();
        assert!(content.contains("@typedef {Object} Users"));
        assert!(content.contains("@property {number} id"));
        assert!(content.contains("@property {string} name"));
        assert!(content.contains("@property {string | null} email"));
    }

    // ─── index file ──────────────────────────────────────────────────────────

    #[test]
    fn test_ts_index_file_with_queries() {
        let schema = schema_with_users();
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::TypeScript };
        let content = gen.emit_index_file(&schema, true).unwrap();
        assert!(content.contains("export * from './users';"));
        assert!(content.contains("export * from './queries';"));
    }

    #[test]
    fn test_js_index_file_no_queries() {
        let schema = schema_with_users();
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::JavaScript };
        let content = gen.emit_index_file(&schema, false).unwrap();
        assert!(content.contains("export * from './users.js';"));
        assert!(!content.contains("queries"));
    }

    // ─── pg queries file ─────────────────────────────────────────────────────

    #[test]
    fn test_pg_ts_one_query() {
        let schema = schema_with_users();
        let queries = vec![get_user_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("import type { ClientBase } from 'pg';"));
        assert!(content.contains("import type { Users } from './users';"));
        assert!(content.contains("async function getUser(db: ClientBase, id: number): Promise<Users | null>"));
        assert!(content.contains("db.query<Users>"));
        assert!(content.contains("result.rows[0] ?? null"));
    }

    #[test]
    fn test_pg_ts_many_query() {
        let schema = schema_with_users();
        let queries = vec![list_users_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("Promise<Users[]>"));
        assert!(content.contains("return result.rows;"));
    }

    #[test]
    fn test_pg_ts_exec_and_execrows() {
        let schema = schema_with_users();
        let queries = vec![delete_user_query(), delete_users_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("Promise<void>"));
        assert!(content.contains("Promise<number>"));
        assert!(content.contains("result.rowCount ?? 0"));
    }

    #[test]
    fn test_pg_js_one_query() {
        let schema = schema_with_users();
        let queries = vec![get_user_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Postgres, output: JsOutput::JavaScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("@typedef {import('pg').ClientBase} ClientBase"));
        assert!(content.contains("@param {ClientBase} db"));
        assert!(content.contains("@param {number} id"));
        assert!(content.contains("@returns {Promise<Users | null>}"));
        assert!(content.contains("export async function getUser(db, id)"));
        assert!(!content.contains("db.query<Users>")); // no generics in JS
        assert!(content.contains("result.rows[0] ?? null"));
    }

    // ─── sqlite queries file ─────────────────────────────────────────────────

    #[test]
    fn test_sqlite_ts_one_query() {
        let schema = schema_with_users();
        let queries = vec![get_user_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Sqlite, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("import type { Database } from 'better-sqlite3';"));
        assert!(content.contains("db: Database"));
        assert!(content.contains(".get(id) as Users | undefined"));
        assert!(content.contains("row ?? null"));
    }

    #[test]
    fn test_sqlite_ts_many_query() {
        let schema = schema_with_users();
        let queries = vec![list_users_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Sqlite, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains(".all() as Users[]"));
    }

    #[test]
    fn test_sqlite_js_one_query() {
        let schema = schema_with_users();
        let queries = vec![get_user_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Sqlite, output: JsOutput::JavaScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("@typedef {import('better-sqlite3').Database} Database"));
        assert!(content.contains("export async function getUser(db, id)"));
        assert!(!content.contains("as Users")); // no casts in JS
        assert!(content.contains("row ?? null"));
    }

    // ─── mysql queries file ───────────────────────────────────────────────────

    #[test]
    fn test_mysql_ts_one_query() {
        let schema = schema_with_users();
        let queries = vec![get_user_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Mysql, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("import type { Connection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';"));
        assert!(content.contains("db: Connection"));
        assert!(content.contains("execute<RowDataPacket[]>"));
        assert!(content.contains("as Users | undefined"));
        assert!(content.contains("?? null"));
    }

    #[test]
    fn test_mysql_ts_execrows() {
        let schema = schema_with_users();
        let queries = vec![delete_users_query()];
        let gen = TypeScriptCodegen { target: JsTarget::Mysql, output: JsOutput::TypeScript };
        let content = build_queries_file(&queries, &schema, &gen.target, &gen.output, &config()).unwrap();
        assert!(content.contains("execute<ResultSetHeader>"));
        assert!(content.contains("result.affectedRows"));
    }

    // ─── inline row type ─────────────────────────────────────────────────────

    #[test]
    fn test_inline_row_type_ts() {
        let query = Query {
            name: "GetStats".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT count(*) AS total FROM users".to_string(),
            params: vec![],
            result_columns: vec![ResultColumn { name: "total".to_string(), sql_type: SqlType::BigInt, nullable: true }],
        };
        let mut src = String::new();
        emit_inline_row_type(&mut src, &query, &JsOutput::TypeScript).unwrap();
        assert!(src.contains("export interface GetStatsRow {"));
        assert!(src.contains("total: number | null;"));
    }

    #[test]
    fn test_inline_row_type_js() {
        let query = Query {
            name: "GetStats".to_string(),
            cmd: QueryCmd::One,
            sql: "SELECT count(*) AS total FROM users".to_string(),
            params: vec![],
            result_columns: vec![ResultColumn { name: "total".to_string(), sql_type: SqlType::BigInt, nullable: true }],
        };
        let mut src = String::new();
        emit_inline_row_type(&mut src, &query, &JsOutput::JavaScript).unwrap();
        assert!(src.contains("@typedef {Object} GetStatsRow"));
        assert!(src.contains("@property {number | null} total"));
    }
}
