use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::common::{group_queries, has_inline_rows, infer_row_type_name, infer_table, mysql_json_table_col_type, queries_file_stem, sql_const_name};
use crate::backend::naming::{to_camel_case, to_pascal_case};
use crate::backend::sql_rewrite::{positional_bind_names, rewrite_list_sql_native, rewrite_to_anon_params, split_at_in_clause, ListRewriteTarget};
use crate::backend::{Codegen, GeneratedFile};
use crate::config::{Engine, ListParamStrategy, OutputConfig};
use crate::ir::{Parameter, Query, QueryCmd, Schema, SqlType, Table};

/// Database engine and npm driver to target for JS/TS output.
pub enum JsTarget {
    /// PostgreSQL via node-postgres (`pg`).
    Postgres,
    /// SQLite via better-sqlite3.
    Sqlite,
    /// MySQL via mysql2.
    Mysql,
}

impl From<Engine> for JsTarget {
    fn from(engine: Engine) -> Self {
        match engine {
            Engine::Postgresql => JsTarget::Postgres,
            Engine::Sqlite => JsTarget::Sqlite,
            Engine::Mysql => JsTarget::Mysql,
        }
    }
}

/// Whether to emit TypeScript (inline types) or JavaScript (JSDoc annotations).
pub enum JsOutput {
    TypeScript,
    JavaScript,
}

/// Per-query context computed once in the target-specific emitter and forwarded to body helpers.
struct QueryContext<'a> {
    query: &'a Query,
    schema: &'a Schema,
    output: &'a JsOutput,
    target: &'a JsTarget,
    fn_name: String,
    ret: String,
    conn_type: &'static str,
}

impl<'a> QueryContext<'a> {
    fn new(query: &'a Query, schema: &'a Schema, output: &'a JsOutput, target: &'a JsTarget, conn_type: &'static str) -> Self {
        Self { fn_name: to_camel_case(&query.name), ret: return_type(query, schema), query, schema, output, target, conn_type }
    }

    fn params(&self) -> Vec<&'a Parameter> {
        self.query.params.iter().collect()
    }
}

/// Code generator for the `"typescript"` and `"javascript"` gen keys.
///
/// Both keys route to this struct with the appropriate [`JsOutput`] variant.
/// TypeScript emits inline type annotations; JavaScript emits JSDoc instead.
pub struct TypeScriptCodegen {
    /// Database driver target.
    pub target: JsTarget,
    /// TypeScript or JavaScript output mode.
    pub output: JsOutput,
}

impl Codegen for TypeScriptCodegen {
    fn generate(&self, schema: &Schema, queries: &[Query], config: &OutputConfig) -> anyhow::Result<Vec<GeneratedFile>> {
        let ext = self.ext();
        let mut files = Vec::new();
        for table in &schema.tables {
            let content = self.emit_model_file(table)?;
            files.push(GeneratedFile { path: PathBuf::from(&config.out).join(format!("{}.{ext}", table.name)), content });
        }
        // One queries file per group
        let groups = group_queries(queries);
        let mut group_stems: Vec<String> = Vec::new();
        for (group, group_queries) in &groups {
            let stem = queries_file_stem(group).to_string();
            group_stems.push(stem.clone());
            let content = build_queries_file(group_queries, schema, &self.target, &self.output, config)?;
            files.push(GeneratedFile { path: PathBuf::from(&config.out).join(format!("{stem}.{ext}")), content });
        }
        let index_content = self.emit_index_file(schema, &group_stems)?;
        files.push(GeneratedFile { path: PathBuf::from(&config.out).join(format!("index.{ext}")), content: index_content });
        Ok(files)
    }
}

impl TypeScriptCodegen {
    /// Returns the file extension: `"ts"` for TypeScript, `"js"` for JavaScript.
    fn ext(&self) -> &'static str {
        match self.output {
            JsOutput::TypeScript => "ts",
            JsOutput::JavaScript => "js",
        }
    }

    fn emit_model_file(&self, table: &Table) -> anyhow::Result<String> {
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        let name = to_pascal_case(&table.name);
        let fields: Vec<(&str, &SqlType, bool)> = table.columns.iter().map(|c| (c.name.as_str(), &c.sql_type, c.nullable)).collect();
        match self.output {
            JsOutput::TypeScript => emit_ts_interface(&mut src, &name, &fields, &self.target)?,
            JsOutput::JavaScript => emit_js_typedef(&mut src, &name, &fields, &self.target)?,
        }
        Ok(src)
    }

    fn emit_index_file(&self, schema: &Schema, group_stems: &[String]) -> anyhow::Result<String> {
        // TypeScript imports must not use .ts extensions; JS (ESM) requires .js.
        let import_ext = match self.output {
            JsOutput::TypeScript => "",
            JsOutput::JavaScript => ".js",
        };
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        for table in &schema.tables {
            writeln!(src, "export * from './{}{import_ext}';", table.name)?;
        }
        for stem in group_stems {
            writeln!(src, "export * from './{stem}{import_ext}';")?;
        }
        Ok(src)
    }
}

// ─── Type emission ────────────────────────────────────────────────────────────

/// Emit a TypeScript `interface` block for the given fields.
fn emit_ts_interface(src: &mut String, name: &str, fields: &[(&str, &SqlType, bool)], target: &JsTarget) -> anyhow::Result<()> {
    writeln!(src, "export interface {name} {{")?;
    for (fname, ftype, nullable) in fields {
        writeln!(src, "  {fname}: {};", js_type(ftype, *nullable, target))?;
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Emit a JSDoc `@typedef` block for the given fields.
fn emit_js_typedef(src: &mut String, name: &str, fields: &[(&str, &SqlType, bool)], target: &JsTarget) -> anyhow::Result<()> {
    writeln!(src, "/**")?;
    writeln!(src, " * @typedef {{Object}} {name}")?;
    for (fname, ftype, nullable) in fields {
        let ty = js_type(ftype, *nullable, target);
        writeln!(src, " * @property {{{ty}}} {fname}")?;
    }
    writeln!(src, " */")?;
    Ok(())
}

/// Emit the inline row type for a query whose result doesn't match any schema table.
fn emit_inline_row_type(src: &mut String, query: &Query, output: &JsOutput, target: &JsTarget) -> anyhow::Result<()> {
    let name = format!("{}Row", to_pascal_case(&query.name));
    let fields: Vec<(&str, &SqlType, bool)> = query.result_columns.iter().map(|c| (c.name.as_str(), &c.sql_type, c.nullable)).collect();
    match output {
        JsOutput::TypeScript => emit_ts_interface(src, &name, &fields, target),
        JsOutput::JavaScript => emit_js_typedef(src, &name, &fields, target),
    }
}

/// Map a SQL type to its JavaScript/TypeScript type string.
fn js_type(sql_type: &SqlType, nullable: bool, target: &JsTarget) -> String {
    let base = js_base_type(sql_type, target);
    if nullable {
        format!("{base} | null")
    } else {
        base
    }
}

fn js_base_type(sql_type: &SqlType, target: &JsTarget) -> String {
    match sql_type {
        SqlType::Boolean => "boolean".to_string(),
        SqlType::SmallInt | SqlType::Integer | SqlType::BigInt => "number".to_string(),
        SqlType::Real | SqlType::Double | SqlType::Decimal => "number".to_string(),
        SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) => "string".to_string(),
        SqlType::Interval | SqlType::Uuid => "string".to_string(),
        SqlType::Bytes => "Buffer".to_string(),
        // mysql2 returns DATE columns as 'YYYY-MM-DD' strings (not Date objects) and
        // sending a JS Date for a DATE param causes timezone-shift bugs. Use string.
        SqlType::Date => {
            if matches!(target, JsTarget::Mysql) {
                "string".to_string()
            } else {
                "Date".to_string()
            }
        },
        SqlType::Time | SqlType::Timestamp | SqlType::TimestampTz => "Date".to_string(),
        SqlType::Json | SqlType::Jsonb => "unknown".to_string(),
        SqlType::Array(inner) => format!("{}[]", js_base_type(inner, target)),
        SqlType::Custom(_) => "unknown".to_string(),
    }
}

// ─── Queries file ─────────────────────────────────────────────────────────────

fn build_queries_file(queries: &[Query], schema: &Schema, target: &JsTarget, output: &JsOutput, config: &OutputConfig) -> anyhow::Result<String> {
    let strategy = config.list_params.clone().unwrap_or_default();
    let mut src = String::new();
    writeln!(src, "// Generated by sqltgen. Do not edit.")?;
    emit_driver_header(&mut src, target, output)?;
    emit_table_imports(&mut src, &needed_tables(queries, schema), output)?;
    writeln!(src)?;
    emit_sql_constants(&mut src, queries, target, &strategy)?;
    for query in queries {
        writeln!(src)?;
        if has_inline_rows(query, schema) {
            emit_inline_row_type(&mut src, query, output, target)?;
            writeln!(src)?;
        }
        emit_query(&mut src, query, schema, target, output, &strategy)?;
    }
    Ok(src)
}

/// Collect the names of schema tables used as return types by any query.
fn needed_tables<'a>(queries: &[Query], schema: &'a Schema) -> BTreeSet<&'a str> {
    let mut set = BTreeSet::new();
    for query in queries {
        if let Some(name) = infer_table(query, schema) {
            set.insert(name);
        }
    }
    set
}

/// Emit driver import (TS) or typedef (JS) at the top of the queries file.
fn emit_driver_header(src: &mut String, target: &JsTarget, output: &JsOutput) -> anyhow::Result<()> {
    writeln!(src, "// Runtime: {}", driver_install_hint(target))?;
    writeln!(src)?;
    match output {
        JsOutput::TypeScript => match target {
            JsTarget::Postgres => writeln!(src, "import type {{ ClientBase }} from 'pg';")?,
            JsTarget::Sqlite => writeln!(src, "import type {{ Database }} from 'better-sqlite3';")?,
            JsTarget::Mysql => writeln!(src, "import type {{ Connection, ResultSetHeader, RowDataPacket }} from 'mysql2/promise';")?,
        },
        JsOutput::JavaScript => match target {
            JsTarget::Postgres => writeln!(src, "/** @typedef {{import('pg').ClientBase}} ClientBase */")?,
            JsTarget::Sqlite => writeln!(src, "/** @typedef {{import('better-sqlite3').Database}} Database */")?,
            JsTarget::Mysql => {
                writeln!(src, "/** @typedef {{import('mysql2/promise').Connection}} Connection */")?;
                writeln!(src, "/** @typedef {{import('mysql2/promise').ResultSetHeader}} ResultSetHeader */")?;
            },
        },
    }
    Ok(())
}

fn driver_install_hint(target: &JsTarget) -> &'static str {
    match target {
        JsTarget::Postgres => "pg (node-postgres) — npm install pg",
        JsTarget::Sqlite => "better-sqlite3 — npm install better-sqlite3",
        JsTarget::Mysql => "mysql2 — npm install mysql2",
    }
}

/// Emit table type imports into the queries file.
fn emit_table_imports(src: &mut String, tables: &BTreeSet<&str>, output: &JsOutput) -> anyhow::Result<()> {
    if tables.is_empty() {
        return Ok(());
    }
    writeln!(src)?;
    for name in tables {
        let class_name = to_pascal_case(name);
        match output {
            JsOutput::TypeScript => writeln!(src, "import type {{ {class_name} }} from './{name}';")?,
            JsOutput::JavaScript => writeln!(src, "/** @typedef {{import('./{name}.js').{class_name}}} {class_name} */")?,
        }
    }
    Ok(())
}

/// Emit SQL string constants for all non-dynamic-list queries.
fn emit_sql_constants(src: &mut String, queries: &[Query], target: &JsTarget, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    for query in queries {
        if query.params.iter().any(|p| p.is_list) && *strategy == ListParamStrategy::Dynamic {
            continue;
        }
        let const_name = sql_const_name(&query.name);
        // NOTE: only one list parameter per query is currently supported.
        let base_sql = match query.params.iter().find(|p| p.is_list) {
            Some(lp) => rewrite_list_sql_native(&query.sql, lp, list_rewrite_target(lp, target)),
            None => query.sql.clone(),
        };
        let sql = normalize_sql(&base_sql, target).replace('"', "\\\"").replace('\n', " ");
        let sql = sql.trim_end().trim_end_matches(';');
        writeln!(src, r#"const {const_name} = "{sql}";"#)?;
    }
    Ok(())
}

/// Rewrite `$N`/`?N` placeholders for the target driver.
/// PostgreSQL keeps `$N`, SQLite and MySQL rewrite to anonymous `?`.
/// Rewrite SQL placeholders for the target driver.
///
/// PostgreSQL (`pg`) accepts `$N` natively; leave the SQL unchanged.
/// SQLite (`better-sqlite3`) and MySQL (`mysql2`) require anonymous `?`.
fn normalize_sql(sql: &str, target: &JsTarget) -> String {
    match target {
        JsTarget::Postgres => sql.to_string(),
        JsTarget::Sqlite | JsTarget::Mysql => rewrite_to_anon_params(sql),
    }
}

/// Build the [`ListRewriteTarget`] for the current JS/TS database target.
fn list_rewrite_target(lp: &Parameter, target: &JsTarget) -> ListRewriteTarget {
    match target {
        JsTarget::Postgres => ListRewriteTarget::PgArray,
        JsTarget::Sqlite => ListRewriteTarget::JsonEach(format!("?{}", lp.index)),
        JsTarget::Mysql => ListRewriteTarget::JsonTable { placeholder: "?".to_string(), col_type: mysql_json_table_col_type(&lp.sql_type).to_string() },
    }
}

// ─── Query function emission ──────────────────────────────────────────────────

fn emit_query(src: &mut String, query: &Query, schema: &Schema, target: &JsTarget, output: &JsOutput, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    match target {
        JsTarget::Postgres => emit_pg_query(src, query, schema, target, output, strategy),
        JsTarget::Sqlite => emit_sqlite_query(src, query, schema, target, output, strategy),
        JsTarget::Mysql => emit_mysql_query(src, query, schema, target, output, strategy),
    }
}

/// Emit the JSDoc annotation block for a query function (JS output only).
fn emit_jsdoc(src: &mut String, conn_type: &str, params: &[&Parameter], return_type: &str, output: &JsOutput, target: &JsTarget) -> anyhow::Result<()> {
    if matches!(output, JsOutput::TypeScript) {
        return Ok(());
    }
    writeln!(src, "/**")?;
    writeln!(src, " * @param {{{conn_type}}} db")?;
    for p in params {
        let ty = if p.is_list { format!("{}[]", js_type(&p.sql_type, false, target)) } else { js_type(&p.sql_type, p.nullable, target) };
        writeln!(src, " * @param {{{ty}}} {}", to_camel_case(&p.name))?;
    }
    writeln!(src, " * @returns {{Promise<{return_type}>}}")?;
    writeln!(src, " */")?;
    Ok(())
}

/// Emit the `export async function` opening line.
/// TypeScript includes type annotations; JavaScript uses plain parameter names.
fn emit_fn_open(
    src: &mut String,
    fn_name: &str,
    conn_type: &str,
    params: &[&Parameter],
    return_type: &str,
    output: &JsOutput,
    target: &JsTarget,
) -> anyhow::Result<()> {
    match output {
        JsOutput::TypeScript => {
            let typed: Vec<String> = params
                .iter()
                .map(|p| {
                    let ty = if p.is_list { format!("{}[]", js_type(&p.sql_type, false, target)) } else { js_type(&p.sql_type, p.nullable, target) };
                    format!("{}: {ty}", to_camel_case(&p.name))
                })
                .collect();
            let sig = std::iter::once(format!("db: {conn_type}")).chain(typed).collect::<Vec<_>>().join(", ");
            writeln!(src, "export async function {fn_name}({sig}): Promise<{return_type}> {{")?;
        },
        JsOutput::JavaScript => {
            let names: Vec<String> = std::iter::once("db".to_string()).chain(params.iter().map(|p| to_camel_case(&p.name))).collect();
            writeln!(src, "export async function {fn_name}({}) {{", names.join(", "))?;
        },
    }
    Ok(())
}

/// Compute the JS/TS return type string for a query.
fn return_type(query: &Query, schema: &Schema) -> String {
    let row = row_type_name(query, schema);
    match query.cmd {
        QueryCmd::One => format!("{row} | null"),
        QueryCmd::Many => format!("{row}[]"),
        QueryCmd::Exec => "void".to_string(),
        QueryCmd::ExecRows => "number".to_string(),
    }
}

/// Compute the row type name for a query result (table name or `{Query}Row`).
fn row_type_name(query: &Query, schema: &Schema) -> String {
    infer_row_type_name(query, schema).unwrap_or_else(|| format!("{}Row", to_pascal_case(&query.name)))
}

// ─── PostgreSQL (pg) ─────────────────────────────────────────────────────────

fn emit_pg_query(src: &mut String, query: &Query, schema: &Schema, target: &JsTarget, output: &JsOutput, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    let ctx = QueryContext::new(query, schema, output, target, "ClientBase");
    if let Some(lp) = query.params.iter().find(|p| p.is_list) {
        return emit_pg_list_query(src, &ctx, strategy, lp);
    }
    let const_name = sql_const_name(&query.name);
    let params = ctx.params();
    emit_jsdoc(src, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    emit_fn_open(src, &ctx.fn_name, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    let args = pg_params_array(query);
    emit_pg_body(src, &ctx, &const_name, &args)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Emit the query body for a PostgreSQL function: the `db.query(...)` call and result handling.
///
/// Accepts either a SQL constant name (static query) or a runtime `sql` variable (dynamic list
/// expansion) as `sql_expr`, and the pre-built params array string as `args`.
fn emit_pg_body(src: &mut String, ctx: &QueryContext, sql_expr: &str, args: &str) -> anyhow::Result<()> {
    match ctx.query.cmd {
        QueryCmd::Exec => writeln!(src, "  await db.query({sql_expr}, {args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = await db.query({sql_expr}, {args});")?;
            writeln!(src, "  return result.rowCount ?? 0;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(ctx.query, ctx.schema);
            let call = pg_query_call(sql_expr, &row, args, ctx.output);
            writeln!(src, "  const result = await {call};")?;
            writeln!(src, "  return result.rows[0] ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(ctx.query, ctx.schema);
            let call = pg_query_call(sql_expr, &row, args, ctx.output);
            writeln!(src, "  const result = await {call};")?;
            writeln!(src, "  return result.rows;")?;
        },
    }
    Ok(())
}

/// Build `db.query<Row>(sql, args)` for TypeScript or `db.query(sql, args)` for JavaScript.
fn pg_query_call(const_name: &str, row_type: &str, args: &str, output: &JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!("db.query<{row_type}>({const_name}, {args})"),
        JsOutput::JavaScript => format!("db.query({const_name}, {args})"),
    }
}

/// Build the `[p1, p2, ...]` params array for a pg query (unique params by index).
///
/// PostgreSQL uses `$N` reference-by-number, so each unique parameter index appears
/// exactly once in the bound array regardless of how many times it is referenced in
/// the SQL. Contrast with [`mysql_params_array`], which uses [`positional_bind_names`]
/// to repeat values for every anonymous `?` occurrence.
fn pg_params_array(query: &Query) -> String {
    let mut params: Vec<&Parameter> = query.params.iter().collect();
    params.sort_by_key(|p| p.index);
    let names: Vec<String> = params.iter().map(|p| to_camel_case(&p.name)).collect();
    format!("[{}]", names.join(", "))
}

fn emit_pg_list_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    emit_fn_open(src, &ctx.fn_name, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    match strategy {
        ListParamStrategy::Native => {
            let args = pg_params_array(ctx.query);
            emit_pg_body(src, ctx, &const_name, &args)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = before_raw.replace('"', "\\\"").replace('\n', " ");
            let after = after_raw.replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            let offset = scalar_params.iter().filter(|p| p.index < lp.index).count() + 1;
            writeln!(src, "  const placeholders = {lp_name}.map((_, i) => '$' + ({offset} + i)).join(', ');")?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_camel_case(&p.name)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_camel_case(&p.name)).collect();
            let all_args = [before_args, vec![format!("...{lp_name}")], after_args].concat().join(", ");
            emit_pg_body(src, ctx, "sql", &format!("[{all_args}]"))?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

// ─── SQLite (better-sqlite3) ─────────────────────────────────────────────────

fn emit_sqlite_query(
    src: &mut String,
    query: &Query,
    schema: &Schema,
    target: &JsTarget,
    output: &JsOutput,
    strategy: &ListParamStrategy,
) -> anyhow::Result<()> {
    let ctx = QueryContext::new(query, schema, output, target, "Database");
    if let Some(lp) = query.params.iter().find(|p| p.is_list) {
        return emit_sqlite_list_query(src, &ctx, strategy, lp);
    }
    let const_name = sql_const_name(&query.name);
    let params = ctx.params();
    emit_jsdoc(src, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    emit_fn_open(src, &ctx.fn_name, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    let args = sqlite_spread_args(query);
    emit_sqlite_body(src, &ctx, &const_name, &args)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the spread argument list for a better-sqlite3 prepared statement call.
///
/// better-sqlite3 uses anonymous `?` placeholders; the arg list must follow the SQL
/// occurrence order including repeated params (e.g. a `@genre` used twice → two args).
fn sqlite_spread_args(query: &Query) -> String {
    positional_bind_names(query).iter().map(|&n| to_camel_case(n)).collect::<Vec<_>>().join(", ")
}

/// Returns ` as Type` for TypeScript or empty string for JavaScript.
///
/// Used for better-sqlite3 `.get()`/`.all()` return types and mysql2 row casts,
/// both of which need an explicit `as T` only in TypeScript output.
fn ts_cast(ts_type: &str, output: &JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!(" as {ts_type}"),
        JsOutput::JavaScript => String::new(),
    }
}

fn emit_sqlite_list_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    emit_fn_open(src, &ctx.fn_name, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    match strategy {
        ListParamStrategy::Native => {
            writeln!(src, "  const {lp_name}Json = JSON.stringify({lp_name});")?;
            let args = sqlite_list_spread_args(ctx.query, lp, &format!("{lp_name}Json"));
            emit_sqlite_body(src, ctx, &const_name, &args)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = rewrite_to_anon_params(&before_raw).replace('"', "\\\"").replace('\n', " ");
            let after = rewrite_to_anon_params(&after_raw).replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            writeln!(src, r#"  const placeholders = {lp_name}.map(() => "?").join(", ");"#)?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_camel_case(&p.name)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_camel_case(&p.name)).collect();
            let all_args = [before_args, vec![format!("...{lp_name}")], after_args].concat().join(", ");
            emit_sqlite_body(src, ctx, "sql", &all_args)?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the spread args string for a SQLite native-list query.
///
/// Follows SQL occurrence order (via [`positional_bind_names`]), substituting the list
/// param's JSON expression wherever that param's name would appear.
fn sqlite_list_spread_args(query: &Query, lp: &Parameter, lp_expr: &str) -> String {
    let lp_camel = to_camel_case(&lp.name);
    positional_bind_names(query)
        .iter()
        .map(|&n| {
            let cn = to_camel_case(n);
            if cn == lp_camel {
                lp_expr.to_string()
            } else {
                cn
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_sqlite_body(src: &mut String, ctx: &QueryContext, sql_expr: &str, args: &str) -> anyhow::Result<()> {
    match ctx.query.cmd {
        QueryCmd::Exec => writeln!(src, "  db.prepare({sql_expr}).run({args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = db.prepare({sql_expr}).run({args});")?;
            writeln!(src, "  return result.changes;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(ctx.query, ctx.schema);
            let cast = ts_cast(&format!("{row} | undefined"), ctx.output);
            writeln!(src, "  const row = db.prepare({sql_expr}).get({args}){cast};")?;
            writeln!(src, "  return row ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(ctx.query, ctx.schema);
            let cast = ts_cast(&format!("{row}[]"), ctx.output);
            writeln!(src, "  return db.prepare({sql_expr}).all({args}){cast};")?;
        },
    }
    Ok(())
}

// ─── MySQL (mysql2) ───────────────────────────────────────────────────────────

fn emit_mysql_query(
    src: &mut String,
    query: &Query,
    schema: &Schema,
    target: &JsTarget,
    output: &JsOutput,
    strategy: &ListParamStrategy,
) -> anyhow::Result<()> {
    let ctx = QueryContext::new(query, schema, output, target, "Connection");
    if let Some(lp) = query.params.iter().find(|p| p.is_list) {
        return emit_mysql_list_query(src, &ctx, strategy, lp);
    }
    let const_name = sql_const_name(&query.name);
    let params = ctx.params();
    emit_jsdoc(src, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    emit_fn_open(src, &ctx.fn_name, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    let args = mysql_params_array(query);
    emit_mysql_body(src, &ctx, &const_name, &args)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the `[p1, p2, ...]` params array for mysql2 (positional `?`, params in SQL order).
fn mysql_params_array(query: &Query) -> String {
    let names: Vec<String> = positional_bind_names(query).iter().map(|&n| to_camel_case(n)).collect();
    format!("[{}]", names.join(", "))
}

fn emit_mysql_body(src: &mut String, ctx: &QueryContext, sql_expr: &str, args: &str) -> anyhow::Result<()> {
    // mysql2's execute() sends all JS `number` values as DOUBLE in the binary
    // protocol. MySQL rejects DOUBLE for LIMIT/OFFSET and other integer contexts.
    // Using query() sends parameters via the text protocol (client-side escaping),
    // which avoids the type mismatch and works correctly for all param types.
    match ctx.query.cmd {
        QueryCmd::Exec => writeln!(src, "  await db.query({sql_expr}, {args});")?,
        QueryCmd::ExecRows => {
            let rsh = mysql_type_param(ctx.output, "ResultSetHeader");
            writeln!(src, "  const [result] = await db.query{rsh}({sql_expr}, {args});")?;
            writeln!(src, "  return result.affectedRows;")?;
        },
        QueryCmd::One => {
            let row = row_type_name(ctx.query, ctx.schema);
            let rdp = mysql_type_param(ctx.output, "RowDataPacket[]");
            let cast = ts_cast(&format!("{row} | undefined"), ctx.output);
            writeln!(src, "  const [rows] = await db.query{rdp}({sql_expr}, {args});")?;
            writeln!(src, "  return (rows[0]{cast}) ?? null;")?;
        },
        QueryCmd::Many => {
            let row = row_type_name(ctx.query, ctx.schema);
            let rdp = mysql_type_param(ctx.output, "RowDataPacket[]");
            let cast = ts_cast(&format!("{row}[]"), ctx.output);
            writeln!(src, "  const [rows] = await db.query{rdp}({sql_expr}, {args});")?;
            writeln!(src, "  return rows{cast};")?;
        },
    }
    Ok(())
}

/// Returns `<Type>` (TS) or empty string (JS) for a mysql2 generic type parameter.
/// Emit `<T>` (TypeScript generic type argument) or empty string (JavaScript).
///
/// Used to make mysql2 `execute` calls typed: `db.execute<RowDataPacket[]>(...)`.
fn mysql_type_param(output: &JsOutput, ts_type: &str) -> String {
    match output {
        JsOutput::TypeScript => format!("<{ts_type}>"),
        JsOutput::JavaScript => String::new(),
    }
}

fn emit_mysql_list_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    emit_fn_open(src, &ctx.fn_name, ctx.conn_type, &params, &ctx.ret, ctx.output, ctx.target)?;
    match strategy {
        ListParamStrategy::Native => {
            writeln!(src, "  const {lp_name}Json = JSON.stringify({lp_name});")?;
            let args = mysql_list_params_array(ctx.query, lp, &format!("{lp_name}Json"));
            emit_mysql_body(src, ctx, &const_name, &args)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = rewrite_to_anon_params(&before_raw).replace('"', "\\\"").replace('\n', " ");
            let after = rewrite_to_anon_params(&after_raw).replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            writeln!(src, r#"  const placeholders = {lp_name}.map(() => "?").join(", ");"#)?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_camel_case(&p.name)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_camel_case(&p.name)).collect();
            let all_args = [before_args, vec![format!("...{lp_name}")], after_args].concat().join(", ");
            emit_mysql_body(src, ctx, "sql", &format!("[{all_args}]"))?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the `[p1, p2, ...]` array for a MySQL native list query,
/// substituting the JSON-stringified expression for the list param slot.
fn mysql_list_params_array(query: &Query, lp: &Parameter, lp_expr: &str) -> String {
    let mut params: Vec<&Parameter> = query.params.iter().collect();
    params.sort_by_key(|p| p.index);
    let names: Vec<String> = params.iter().map(|p| if p.index == lp.index { lp_expr.to_string() } else { to_camel_case(&p.name) }).collect();
    format!("[{}]", names.join(", "))
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests;

