services:
  db:
    image: ghcr.io/sqltgen/db-mysql:latest
    build:
      context: .
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "sqltgen", "-psqltgen"]
      interval: 0.1s
      timeout: 3s
      retries: 30
