// Generated e2e runtime test — rust/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
use e2e_schema_qualified_rust_postgresql::db::queries::queries;
use sqlx::postgres::PgPoolOptions;
use sqlx::PgPool;
#[allow(unused_imports)]
use time::macros::{date, datetime, time};

// ─── test setup ───────────────────────────────────────────────────────────────

async fn gen_setup_db() -> (PgPool, String) {
    let url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e".into());
    let bootstrap = PgPool::connect(&url).await.unwrap();
    let db_name = format!("test_{}", uuid::Uuid::new_v4().simple());
    sqlx::query(&format!("CREATE DATABASE \"{db_name}\""))
        .execute(&bootstrap)
        .await
        .unwrap();
    bootstrap.close().await;
    let base = url.rsplit_once('/').map(|(b, _)| b).unwrap_or(&url);
    let pool = PgPoolOptions::new()
        .connect(&format!("{base}/{db_name}"))
        .await
        .unwrap();
    let ddl = include_str!("../../../../../fixtures/schema_qualified/postgresql/schema.sql");
    for stmt in ddl.split(';').map(str::trim).filter(|s| !s.is_empty()) {
        sqlx::query(stmt).execute(&pool).await.unwrap();
    }
    (pool, db_name)
}

async fn gen_teardown(pool: PgPool, db_name: String) {
    pool.close().await;
    let url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e".into());
    let admin = PgPool::connect(&url).await.unwrap();
    let _ = sqlx::query(&format!(
        "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '{db_name}' AND pid <> pg_backend_pid()"
    ))
    .execute(&admin)
    .await;
    let _ = sqlx::query(&format!("DROP DATABASE IF EXISTS \"{db_name}\""))
        .execute(&admin)
        .await;
    admin.close().await;
}

#[allow(dead_code)]
fn gen_assert_json_str(got: &str, want: serde_json::Value) {
    let got: serde_json::Value = serde_json::from_str(got).unwrap();
    assert_eq!(got, want);
}

// ─── scenarios ────────────────────────────────────────────────────────────────

// ─── cross-schema queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_create_and_list_audit_logs_gen() {
    let (pool, db_name) = gen_setup_db().await;
    queries::create_audit_log(&pool, 1, "login".to_string()).await.unwrap();
    queries::create_audit_log(&pool, 1, "view_dashboard".to_string()).await.unwrap();
    let logs = queries::list_audit_logs(&pool).await.unwrap();
    assert_eq!(logs.len(), 2);
    assert_eq!(logs[0].action, "view_dashboard".to_string());
    assert_eq!(logs[1].action, "login".to_string());
    assert_eq!(logs[0].user_id, 1);
    gen_teardown(pool, db_name).await;
}

// ─── public schema queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_get_user_from_public_schema_gen() {
    let (pool, db_name) = gen_setup_db().await;
    let result = queries::get_user(&pool, 999).await.unwrap();
    assert!(result.is_none());
    gen_teardown(pool, db_name).await;
}

