// Generated e2e runtime test — java/sqlite. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.*;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private static final ObjectMapper GEN_MAPPER = new ObjectMapper();
    private Connection conn;

    @BeforeEach
    void setUp() throws Exception {
        conn = DriverManager.getConnection("jdbc:sqlite::memory:");
        conn.setAutoCommit(true);
        String ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/type_overrides/sqlite/schema.sql"));
        try (Statement s = conn.createStatement()) {
            for (String stmt : ddl.split(";")) {
                String t = stmt.strip();
                if (!t.isEmpty()) s.execute(t);
            }
        }
    }

    @AfterEach
    void tearDown() throws Exception {
        if (conn != null) conn.close();
    }

    private static JsonNode genJson(String raw) {
        try {
            return GEN_MAPPER.readTree(raw);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    void testUpdatePayloadGen() throws Exception {
        Queries.insertEvent(conn, "test", "{\"v\": 1}", "{\"source\": \"web\"}", UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null);
        Queries.updatePayload(conn, "{\"v\": 2, \"changed\": true}", null, 1);
        var ev = Queries.getEvent(conn, 1).orElseThrow();
        assertNotNull(ev);
        assertEquals(genJson("{\"v\": 2, \"changed\": true}"), genJson(ev.payload()));
        assertNull(ev.meta());
    }

    @Test
    void testUpdateEventDateGen() throws Exception {
        Queries.insertEvent(conn, "dated", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, LocalDate.of(2024, 1, 1), null);
        Queries.updateEventDate(conn, LocalDate.of(2024, 12, 31), 1);
        var ev = Queries.getEvent(conn, 1).orElseThrow();
        assertNotNull(ev);
        assertEquals(LocalDate.of(2024, 12, 31), ev.eventDate());
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    void testInsertEventRowsGen() throws Exception {
        var n = Queries.insertEventRows(conn, "rowtest", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null);
        assertEquals(1L, n);
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    void testListEventsGen() throws Exception {
        var ts = LocalDateTime.of(2024, 6, 1, 12, 0, 0);
        Queries.insertEvent(conn, "alpha", "{}", null, UUID.randomUUID().toString(), ts, null, null, null);
        Queries.insertEvent(conn, "beta", "{}", null, UUID.randomUUID().toString(), ts, null, null, null);
        Queries.insertEvent(conn, "gamma", "{}", null, UUID.randomUUID().toString(), ts, null, null, null);
        var events = Queries.listEvents(conn);
        assertEquals(3, events.size());
        assertEquals("alpha", events.get(0).name());
        assertEquals("beta", events.get(1).name());
        assertEquals("gamma", events.get(2).name());
    }

    @Test
    void testGetEventsByDateRangeGen() throws Exception {
        Queries.insertEvent(conn, "early", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 1, 1, 10, 0, 0), null, null, null);
        Queries.insertEvent(conn, "mid", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null);
        Queries.insertEvent(conn, "late", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 12, 1, 15, 0, 0), null, null, null);
        var events = Queries.getEventsByDateRange(conn, LocalDateTime.of(2024, 1, 1, 0, 0, 0), LocalDateTime.of(2024, 7, 1, 0, 0, 0));
        assertEquals(2, events.size());
        assertEquals("early", events.get(0).name());
        assertEquals("mid", events.get(1).name());
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    void testInsertAndGetEventGen() throws Exception {
        var doc_id = UUID.randomUUID().toString();
        Queries.insertEvent(conn, "login", "{\"type\": \"click\", \"x\": 10}", "{\"source\": \"web\"}", doc_id, LocalDateTime.of(2024, 6, 1, 12, 0, 0), LocalDateTime.of(2024, 6, 1, 14, 0, 0), LocalDate.of(2024, 6, 1), LocalTime.of(9, 0, 0));
        var ev = Queries.getEvent(conn, 1).orElseThrow();
        assertNotNull(ev);
        assertEquals("login", ev.name());
        assertEquals(genJson("{\"type\": \"click\", \"x\": 10}"), genJson(ev.payload()));
        assertEquals(genJson("{\"source\": \"web\"}"), genJson(ev.meta()));
        assertEquals(doc_id, ev.docId());
        assertEquals(LocalDateTime.of(2024, 6, 1, 12, 0, 0), ev.createdAt());
        assertEquals(LocalDateTime.of(2024, 6, 1, 14, 0, 0), ev.scheduledAt());
        assertEquals(LocalDate.of(2024, 6, 1), ev.eventDate());
        assertEquals(LocalTime.of(9, 0, 0), ev.eventTime());
    }

    @Test
    void testGetEventNotFoundGen() throws Exception {
        var result = Queries.getEvent(conn, 999);
        assertTrue(result.isEmpty());
    }

    // ─── count queries ────────────────────────────────────────────────────────────

    @Test
    void testCountEventsGen() throws Exception {
        Queries.insertEvent(conn, "ev1", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 0, 0, 0), null, null, null);
        Queries.insertEvent(conn, "ev2", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 2, 0, 0, 0), null, null, null);
        Queries.insertEvent(conn, "ev3", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 3, 0, 0, 0), null, null, null);
        var row = Queries.countEvents(conn, LocalDateTime.of(2024, 1, 1, 0, 0, 0)).orElseThrow();
        assertNotNull(row);
        assertEquals(3L, row.total());
    }

    // ─── projection queries ────────────────────────────────────────────────────────────

    @Test
    void testFindByDateGen() throws Exception {
        var target = LocalDate.of(2024, 6, 15);
        Queries.insertEvent(conn, "dated", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, target, null);
        var row = Queries.findByDate(conn, target).orElseThrow();
        assertNotNull(row);
        assertEquals("dated", row.name());
    }

    @Test
    void testFindByUuidGen() throws Exception {
        var doc_id = UUID.randomUUID().toString();
        Queries.insertEvent(conn, "uuid-test", "{}", null, doc_id, LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null);
        var row = Queries.findByDocId(conn, doc_id).orElseThrow();
        assertNotNull(row);
        assertEquals("uuid-test", row.name());
    }

}
