use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::GeneratedFile;
use crate::backend::naming::to_pascal_case;
use crate::config::OutputConfig;
use crate::ir::{SqlType, Table};

pub(super) fn cpp_type(sql_type: &SqlType, nullable: bool) -> String {
    let base = match sql_type {
        SqlType::Boolean => "bool".to_string(),
        SqlType::SmallInt => "std::int16_t".to_string(),
        SqlType::Integer => "std::int32_t".to_string(),
        SqlType::BigInt => "std::int64_t".to_string(),
        SqlType::Real => "float".to_string(),
        SqlType::Double => "double".to_string(),
        SqlType::Decimal => "std::string".to_string(), // double loses precision
        SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) => "std::string".to_string(),
        SqlType::Bytes => "std::vector<std::uint8_t>".to_string(),
        SqlType::Date => "std::chrono::year_month_day".to_string(),
        SqlType::Time => "std::chrono::seconds".to_string(),
        SqlType::Timestamp | SqlType::TimestampTz => "std::chrono::system_clock::time_point".to_string(),
        SqlType::Interval => "std::chrono::microseconds".to_string(),
        SqlType::Uuid => "std::string".to_string(),
        SqlType::Json | SqlType::Jsonb => "std::string".to_string(),
        SqlType::Array(inner) => format!("std::vector<{}>", cpp_type(inner, false)),
        SqlType::Custom(_) => "std::string".to_string(),
    };

    if nullable {
        format!("std::optional<{base}>")
    } else {
        base
    }
}

#[derive(Default)]
struct CppIncludes {
    set: BTreeSet<&'static str>,
}

impl CppIncludes {
    fn scan(&mut self, sql_type: &SqlType, nullable: bool) {
        if nullable {
            self.set.insert("<optional>");
        }

        match sql_type {
            SqlType::Boolean | SqlType::Real | SqlType::Double => {},
            SqlType::SmallInt | SqlType::Integer | SqlType::BigInt => {
                self.set.insert("<cstdint>");
            },
            SqlType::Decimal | SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) | SqlType::Uuid | SqlType::Json | SqlType::Jsonb | SqlType::Custom(_) => {
                self.set.insert("<string>");
            },
            SqlType::Bytes => {
                self.set.insert("<cstdint>");
                self.set.insert("<vector>");
            },
            SqlType::Date | SqlType::Time | SqlType::Timestamp | SqlType::TimestampTz | SqlType::Interval => {
                self.set.insert("<chrono>");
            },
            SqlType::Array(inner) => {
                self.set.insert("<vector>");
                self.scan(inner, false);
            },
        }
    }
}

fn emit_table_header(table: &Table, namespace: &str) -> anyhow::Result<String> {
    let mut src = String::new();
    let struct_name = to_pascal_case(&table.name);

    let mut includes = CppIncludes::default();
    for col in &table.columns {
        includes.scan(&col.sql_type, col.nullable);
    }

    writeln!(src, "#pragma once")?;
    writeln!(src, "// Generated by sqltgen. Do not edit.")?;
    writeln!(src)?;

    for include in &includes.set {
        writeln!(src, "#include {include}")?;
    }

    if !includes.set.is_empty() {
        writeln!(src)?;
    }

    if !namespace.is_empty() {
        writeln!(src, "namespace {namespace} {{")?;
        writeln!(src)?;
    }

    writeln!(src, "struct {struct_name} {{")?;
    for col in &table.columns {
        writeln!(src, "    {} {};", cpp_type(&col.sql_type, col.nullable), col.name)?;
    }
    writeln!(src, "}};")?;

    if !namespace.is_empty() {
        writeln!(src)?;
        writeln!(src, "}} // namespace {namespace}")?;
    }

    Ok(src)
}

pub(super) fn generate_table_files(schema: &crate::ir::Schema, config: &OutputConfig) -> anyhow::Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();

    for table in &schema.tables {
        files.push(GeneratedFile {
            path: PathBuf::from(&config.out).join(format!("{}.hpp", table.name)),
            content: emit_table_header(table, &config.package)?,
        });
    }

    Ok(files)
}
