// Generated e2e runtime test — rust/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
use e2e_type_overrides_rust_postgresql::db::queries::queries;
use sqlx::postgres::PgPoolOptions;
use sqlx::PgPool;
#[allow(unused_imports)]
use time::macros::{date, datetime, time};

// ─── test setup ───────────────────────────────────────────────────────────────

async fn gen_setup_db() -> PgPool {
    let url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e".into());
    let bootstrap = PgPool::connect(&url).await.unwrap();
    let schema = format!("test_{}", uuid::Uuid::new_v4().simple());
    sqlx::query(&format!("CREATE SCHEMA \"{schema}\""))
        .execute(&bootstrap)
        .await
        .unwrap();
    bootstrap.close().await;
    let pool = PgPoolOptions::new()
        .after_connect({
            let schema = schema.clone();
            move |conn, _meta| {
                let schema = schema.clone();
                Box::pin(async move {
                    sqlx::query(&format!("SET search_path TO \"{schema}\""))
                        .execute(&mut *conn)
                        .await?;
                    Ok(())
                })
            }
        })
        .connect(&url)
        .await
        .unwrap();
    let ddl = include_str!("../../../../../fixtures/type_overrides/postgresql/schema.sql");
    for stmt in ddl.split(';').map(str::trim).filter(|s| !s.is_empty()) {
        sqlx::query(stmt).execute(&pool).await.unwrap();
    }
    pool
}

#[allow(dead_code)]
fn gen_assert_json_str(got: &str, want: serde_json::Value) {
    let got: serde_json::Value = serde_json::from_str(got).unwrap();
    assert_eq!(got, want);
}

// ─── scenarios ────────────────────────────────────────────────────────────────

// ─── :exec queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_update_payload_gen() {
    let pool = gen_setup_db().await;
    queries::insert_event(&pool, "test".to_string(), serde_json::json!({"v": 1}), Some(serde_json::json!({"source": "web"})), uuid::Uuid::new_v4(), datetime!(2024-06-01 12:00:00), None, None, None).await.unwrap();
    queries::update_payload(&pool, serde_json::json!({"v": 2, "changed": true}), None, 1).await.unwrap();
    let ev = queries::get_event(&pool, 1).await.unwrap();
    let ev = ev.expect("expected non-nil ev");
    assert_eq!(ev.payload, serde_json::json!({"v": 2, "changed": true}));
    assert!(ev.meta.is_none());
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_update_event_date_gen() {
    let pool = gen_setup_db().await;
    queries::insert_event(&pool, "dated".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-01 12:00:00), None, Some(date!(2024-01-01)), None).await.unwrap();
    queries::update_event_date(&pool, Some(date!(2024-12-31)), 1).await.unwrap();
    let ev = queries::get_event(&pool, 1).await.unwrap();
    let ev = ev.expect("expected non-nil ev");
    assert_eq!(ev.event_date, Some(date!(2024-12-31)));
}

// ─── :execrows queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_insert_event_rows_gen() {
    let pool = gen_setup_db().await;
    let n = queries::insert_event_rows(&pool, "rowtest".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-01 12:00:00), None, None, None).await.unwrap();
    assert_eq!(n, 1);
}

// ─── :many queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_list_events_gen() {
    let pool = gen_setup_db().await;
    let ts = datetime!(2024-06-01 12:00:00);
    queries::insert_event(&pool, "alpha".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), ts, None, None, None).await.unwrap();
    queries::insert_event(&pool, "beta".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), ts, None, None, None).await.unwrap();
    queries::insert_event(&pool, "gamma".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), ts, None, None, None).await.unwrap();
    let events = queries::list_events(&pool).await.unwrap();
    assert_eq!(events.len(), 3);
    assert_eq!(events[0].name, "alpha".to_string());
    assert_eq!(events[1].name, "beta".to_string());
    assert_eq!(events[2].name, "gamma".to_string());
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_get_events_by_date_range_gen() {
    let pool = gen_setup_db().await;
    queries::insert_event(&pool, "early".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-01-01 10:00:00), None, None, None).await.unwrap();
    queries::insert_event(&pool, "mid".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-01 12:00:00), None, None, None).await.unwrap();
    queries::insert_event(&pool, "late".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-12-01 15:00:00), None, None, None).await.unwrap();
    let events = queries::get_events_by_date_range(&pool, datetime!(2024-01-01 00:00:00), datetime!(2024-07-01 00:00:00)).await.unwrap();
    assert_eq!(events.len(), 2);
    assert_eq!(events[0].name, "early".to_string());
    assert_eq!(events[1].name, "mid".to_string());
}

// ─── :one queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_insert_and_get_event_gen() {
    let pool = gen_setup_db().await;
    let doc_id = uuid::Uuid::new_v4();
    queries::insert_event(&pool, "login".to_string(), serde_json::json!({"type": "click", "x": 10}), Some(serde_json::json!({"source": "web"})), doc_id, datetime!(2024-06-01 12:00:00), Some(datetime!(2024-06-01 14:00:00 UTC)), Some(date!(2024-06-01)), Some(time!(09:00:00))).await.unwrap();
    let ev = queries::get_event(&pool, 1).await.unwrap();
    let ev = ev.expect("expected non-nil ev");
    assert_eq!(ev.name, "login".to_string());
    assert_eq!(ev.payload, serde_json::json!({"type": "click", "x": 10}));
    assert_eq!(ev.meta, Some(serde_json::json!({"source": "web"})));
    assert_eq!(ev.doc_id, doc_id);
    assert_eq!(ev.created_at, datetime!(2024-06-01 12:00:00));
    assert_eq!(ev.scheduled_at, Some(datetime!(2024-06-01 14:00:00 UTC)));
    assert_eq!(ev.event_date, Some(date!(2024-06-01)));
    assert_eq!(ev.event_time, Some(time!(09:00:00)));
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_get_event_not_found_gen() {
    let pool = gen_setup_db().await;
    let result = queries::get_event(&pool, 999).await.unwrap();
    assert!(result.is_none());
}

// ─── count queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_count_events_gen() {
    let pool = gen_setup_db().await;
    queries::insert_event(&pool, "ev1".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-01 00:00:00), None, None, None).await.unwrap();
    queries::insert_event(&pool, "ev2".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-02 00:00:00), None, None, None).await.unwrap();
    queries::insert_event(&pool, "ev3".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-03 00:00:00), None, None, None).await.unwrap();
    let row = queries::count_events(&pool, datetime!(2024-01-01 00:00:00)).await.unwrap();
    let row = row.expect("expected non-nil row");
    assert_eq!(row.total, 3);
}

// ─── projection queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_find_by_date_gen() {
    let pool = gen_setup_db().await;
    let target = date!(2024-06-15);
    queries::insert_event(&pool, "dated".to_string(), serde_json::json!({}), None, uuid::Uuid::new_v4(), datetime!(2024-06-01 12:00:00), None, Some(target), None).await.unwrap();
    let row = queries::find_by_date(&pool, Some(target)).await.unwrap();
    let row = row.expect("expected non-nil row");
    assert_eq!(row.name, "dated".to_string());
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_find_by_uuid_gen() {
    let pool = gen_setup_db().await;
    let doc_id = uuid::Uuid::new_v4();
    queries::insert_event(&pool, "uuid-test".to_string(), serde_json::json!({}), None, doc_id, datetime!(2024-06-01 12:00:00), None, None, None).await.unwrap();
    let row = queries::find_by_uuid(&pool, doc_id).await.unwrap();
    let row = row.expect("expected non-nil row");
    assert_eq!(row.name, "uuid-test".to_string());
}

