// Generated e2e runtime test — java/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.*;
import java.util.List;
import java.util.UUID;
import com.example.db.queries.Queries;
import com.example.db.models.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private static final ObjectMapper GEN_MAPPER = new ObjectMapper();
    private static final String URL =
        System.getenv().getOrDefault("DATABASE_URL",
            "jdbc:postgresql://localhost:15432/sqltgen_e2e");
    private static final String USER = "sqltgen";
    private static final String PASS = "sqltgen";

    private Connection conn;
    private String dbName;

    @BeforeEach
    void setUp() throws Exception {
        dbName = "test_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection admin = DriverManager.getConnection(URL, USER, PASS);
             Statement s = admin.createStatement()) {
            s.execute("CREATE DATABASE \"" + dbName + "\"");
        }
        String baseUrl = URL.replaceFirst("/[^/]*$", "/" + dbName);
        conn = DriverManager.getConnection(baseUrl, USER, PASS);
        conn.setAutoCommit(true);
        var ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/schema_qualified/postgresql/schema.sql"));
        try (Statement s = conn.createStatement()) {
            for (String stmt : ddl.split(";")) {
                String t = stmt.strip();
                if (!t.isEmpty()) s.execute(t);
            }
        }
    }

    @AfterEach
    void tearDown() throws Exception {
        if (conn != null) conn.close();
        try (Connection admin = DriverManager.getConnection(URL, USER, PASS);
             Statement s = admin.createStatement()) {
            s.execute("DROP DATABASE IF EXISTS \"" + dbName + "\"");
        }
    }

    private static JsonNode genJson(String raw) {
        try {
            return GEN_MAPPER.readTree(raw);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── cross-schema queries ────────────────────────────────────────────────────────────

    @Test
    void testCreateAndListAuditLogsGen() throws Exception {
        Queries.createAuditLog(conn, 1L, "login");
        Queries.createAuditLog(conn, 1L, "view_dashboard");
        var logs = Queries.listAuditLogs(conn);
        assertEquals(2, logs.size());
        assertEquals("view_dashboard", logs.get(0).action());
        assertEquals("login", logs.get(1).action());
        assertEquals(1L, logs.get(0).userId());
    }

    // ─── public schema queries ────────────────────────────────────────────────────────────

    @Test
    void testGetUserFromPublicSchemaGen() throws Exception {
        var result = Queries.getUser(conn, 999L);
        assertTrue(result.isEmpty());
    }

}
