// Generated e2e runtime test — rust/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
use e2e_enums_rust_postgresql::db::queries::queries;
use e2e_enums_rust_postgresql::db::models::priority::Priority;
use e2e_enums_rust_postgresql::db::models::status::Status;
use sqlx::postgres::PgPoolOptions;
use sqlx::PgPool;
#[allow(unused_imports)]
use time::macros::{date, datetime, time};

// ─── test setup ───────────────────────────────────────────────────────────────

async fn gen_setup_db() -> PgPool {
    let url = std::env::var("DATABASE_URL")
        .unwrap_or_else(|_| "postgres://sqltgen:sqltgen@localhost:15432/sqltgen_e2e".into());
    let bootstrap = PgPool::connect(&url).await.unwrap();
    let schema = format!("test_{}", uuid::Uuid::new_v4().simple());
    sqlx::query(&format!("CREATE SCHEMA \"{schema}\""))
        .execute(&bootstrap)
        .await
        .unwrap();
    bootstrap.close().await;
    let pool = PgPoolOptions::new()
        .after_connect({
            let schema = schema.clone();
            move |conn, _meta| {
                let schema = schema.clone();
                Box::pin(async move {
                    sqlx::query(&format!("SET search_path TO \"{schema}\""))
                        .execute(&mut *conn)
                        .await?;
                    Ok(())
                })
            }
        })
        .connect(&url)
        .await
        .unwrap();
    let ddl = include_str!("../../../../../fixtures/enums/postgresql/schema.sql");
    for stmt in ddl.split(';').map(str::trim).filter(|s| !s.is_empty()) {
        sqlx::query(stmt).execute(&pool).await.unwrap();
    }
    pool
}

#[allow(dead_code)]
fn gen_assert_json_str(got: &str, want: serde_json::Value) {
    let got: serde_json::Value = serde_json::from_str(got).unwrap();
    assert_eq!(got, want);
}

// ─── scenarios ────────────────────────────────────────────────────────────────

// ─── :exec queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_delete_task_gen() {
    let pool = gen_setup_db().await;
    let _ = queries::create_task(&pool, "Temp".to_string(), "low".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    queries::delete_task(&pool, 1).await.unwrap();
    let result = queries::get_task(&pool, 1).await.unwrap();
    assert!(result.is_none());
}

// ─── :many queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_list_by_priority_gen() {
    let pool = gen_setup_db().await;
    let _ = queries::create_task(&pool, "Low task".to_string(), "low".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "High task 1".to_string(), "high".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "High task 2".to_string(), "high".parse::<Priority>().unwrap(), "done".parse::<Status>().unwrap(), None).await.unwrap();
    let tasks = queries::list_tasks_by_priority(&pool, "high".parse::<Priority>().unwrap()).await.unwrap();
    assert_eq!(tasks.len(), 2);
    assert_eq!(tasks[0].title, "High task 1".to_string());
    assert_eq!(tasks[1].title, "High task 2".to_string());
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_list_by_status_gen() {
    let pool = gen_setup_db().await;
    let _ = queries::create_task(&pool, "Open 1".to_string(), "low".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "Done 1".to_string(), "medium".parse::<Priority>().unwrap(), "done".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "Open 2".to_string(), "high".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let tasks = queries::list_tasks_by_status(&pool, "open".parse::<Status>().unwrap()).await.unwrap();
    assert_eq!(tasks.len(), 2);
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_list_by_priority_or_all_gen() {
    let pool = gen_setup_db().await;
    let _ = queries::create_task(&pool, "Low".to_string(), "low".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "High".to_string(), "high".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let all_tasks = queries::list_tasks_by_priority_or_all(&pool, None).await.unwrap();
    assert_eq!(all_tasks.len(), 2);
    let high_tasks = queries::list_tasks_by_priority_or_all(&pool, Some("high".parse::<Priority>().unwrap())).await.unwrap();
    assert_eq!(high_tasks.len(), 1);
    assert_eq!(high_tasks[0].title, "High".to_string());
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_count_by_status_gen() {
    let pool = gen_setup_db().await;
    let _ = queries::create_task(&pool, "A".to_string(), "low".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "B".to_string(), "low".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let _ = queries::create_task(&pool, "C".to_string(), "high".parse::<Priority>().unwrap(), "done".parse::<Status>().unwrap(), None).await.unwrap();
    let counts = queries::count_by_status(&pool).await.unwrap();
    assert_eq!(counts.len(), 2);
}

// ─── :one queries ────────────────────────────────────────────────────────────

#[allow(unused_variables)]
#[tokio::test]
async fn test_create_and_get_task_gen() {
    let pool = gen_setup_db().await;
    let task = queries::create_task(&pool, "Fix bug".to_string(), "high".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), Some("Fix the login bug".to_string())).await.unwrap();
    let task = task.expect("expected non-nil task");
    assert_eq!(task.title, "Fix bug".to_string());
    assert_eq!(task.priority, "high".parse::<Priority>().unwrap());
    assert_eq!(task.status, "open".parse::<Status>().unwrap());
    assert_eq!(task.description, Some("Fix the login bug".to_string()));
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_get_task_not_found_gen() {
    let pool = gen_setup_db().await;
    let result = queries::get_task(&pool, 999).await.unwrap();
    assert!(result.is_none());
}

#[allow(unused_variables)]
#[tokio::test]
async fn test_update_task_status_gen() {
    let pool = gen_setup_db().await;
    let task = queries::create_task(&pool, "Deploy".to_string(), "critical".parse::<Priority>().unwrap(), "open".parse::<Status>().unwrap(), None).await.unwrap();
    let updated = queries::update_task_status(&pool, "in_progress".parse::<Status>().unwrap(), 1).await.unwrap();
    let updated = updated.expect("expected non-nil updated");
    assert_eq!(updated.status, "in_progress".parse::<Status>().unwrap());
    assert_eq!(updated.priority, "critical".parse::<Priority>().unwrap());
}

