"""Generated e2e runtime test — python/sqlite. DO NOT EDIT.

Auto-generated by scripts/e2e_testgen from test_spec.yaml.
"""

import datetime
import json
import os
import pathlib
import uuid

import sqlite3
import pytest

from gen import queries

_FIXTURES = pathlib.Path(__file__).parent / "../../../../fixtures/type_overrides/sqlite"


@pytest.fixture()
def conn():
    """Yield an in-memory SQLite connection with the schema loaded."""
    schema_sql = (_FIXTURES / "schema.sql").read_text()
    c = sqlite3.connect(":memory:")
    c.executescript(schema_sql)
    yield c
    c.close()


def test_insert_and_get_event(conn):
    doc_id = str(uuid.uuid4())
    queries.insert_event(conn, 'login', json.dumps({'type': 'click', 'x': 10}), json.dumps({'source': 'web'}), doc_id, '2024-06-01 12:00:00', '2024-06-01 14:00:00', '2024-06-01', '09:00:00')
    ev = queries.get_event(conn, 1)
    assert ev is not None
    assert ev.name == 'login'
    assert ev.payload == json.dumps({'type': 'click', 'x': 10})
    assert ev.meta == json.dumps({'source': 'web'})
    assert str(ev.doc_id) == doc_id
    assert ev.scheduled_at == '2024-06-01 14:00:00'
    assert ev.event_date == '2024-06-01'
    assert ev.event_time == '09:00:00'


def test_get_event_not_found(conn):
    result = queries.get_event(conn, 999)
    assert result is None


def test_list_events(conn):
    ts = '2024-06-01 12:00:00'
    queries.insert_event(conn, 'alpha', json.dumps({}), None, str(uuid.uuid4()), ts, None, None, None)
    queries.insert_event(conn, 'beta', json.dumps({}), None, str(uuid.uuid4()), ts, None, None, None)
    queries.insert_event(conn, 'gamma', json.dumps({}), None, str(uuid.uuid4()), ts, None, None, None)
    events = queries.list_events(conn)
    assert len(events) == 3
    assert events[0].name == 'alpha'
    assert events[1].name == 'beta'
    assert events[2].name == 'gamma'


def test_get_events_by_date_range(conn):
    queries.insert_event(conn, 'early', json.dumps({}), None, str(uuid.uuid4()), '2024-01-01 10:00:00', None, None, None)
    queries.insert_event(conn, 'mid', json.dumps({}), None, str(uuid.uuid4()), '2024-06-01 12:00:00', None, None, None)
    queries.insert_event(conn, 'late', json.dumps({}), None, str(uuid.uuid4()), '2024-12-01 15:00:00', None, None, None)
    events = queries.get_events_by_date_range(conn, '2024-01-01 00:00:00', '2024-07-01 00:00:00')
    assert len(events) == 2
    assert events[0].name == 'early'
    assert events[1].name == 'mid'


def test_update_payload(conn):
    queries.insert_event(conn, 'test', json.dumps({'v': 1}), json.dumps({'source': 'web'}), str(uuid.uuid4()), '2024-06-01 12:00:00', None, None, None)
    queries.update_payload(conn, json.dumps({'v': 2, 'changed': True}), None, 1)
    ev = queries.get_event(conn, 1)
    assert ev is not None
    assert ev.payload == json.dumps({'v': 2, 'changed': True})
    assert ev.meta is None


def test_update_event_date(conn):
    queries.insert_event(conn, 'dated', json.dumps({}), None, str(uuid.uuid4()), '2024-06-01 12:00:00', None, '2024-01-01', None)
    queries.update_event_date(conn, '2024-12-31', 1)
    ev = queries.get_event(conn, 1)
    assert ev is not None
    assert ev.event_date == '2024-12-31'


def test_insert_event_rows(conn):
    n = queries.insert_event_rows(conn, 'rowtest', json.dumps({}), None, str(uuid.uuid4()), '2024-06-01 12:00:00', None, None, None)
    assert n == 1


def test_find_by_date(conn):
    target = '2024-06-15'
    queries.insert_event(conn, 'dated', json.dumps({}), None, str(uuid.uuid4()), '2024-06-01 12:00:00', None, target, None)
    row = queries.find_by_date(conn, target)
    assert row is not None
    assert row.name == 'dated'


def test_find_by_uuid(conn):
    doc_id = str(uuid.uuid4())
    queries.insert_event(conn, 'uuid-test', json.dumps({}), None, doc_id, '2024-06-01 12:00:00', None, None, None)
    row = queries.find_by_doc_id(conn, doc_id)
    assert row is not None
    assert row.name == 'uuid-test'


def test_count_events(conn):
    queries.insert_event(conn, 'ev1', json.dumps({}), None, str(uuid.uuid4()), '2024-06-01 00:00:00', None, None, None)
    queries.insert_event(conn, 'ev2', json.dumps({}), None, str(uuid.uuid4()), '2024-06-02 00:00:00', None, None, None)
    queries.insert_event(conn, 'ev3', json.dumps({}), None, str(uuid.uuid4()), '2024-06-03 00:00:00', None, None, None)
    row = queries.count_events(conn, '2024-01-01 00:00:00')
    assert row is not None
    assert row.total == 3


