// Generated e2e runtime test — kotlin/sqlite. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.example.db.models.*
import com.example.db.queries.Queries
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.UUID

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private val GEN_MAPPER = ObjectMapper()
    private lateinit var conn: Connection

    @BeforeEach
    fun setUp() {
        conn = DriverManager.getConnection("jdbc:sqlite::memory:")
        conn.autoCommit = true
        val ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/type_overrides/sqlite/schema.sql"))
        conn.createStatement().use { s ->
            for (stmt in ddl.split(";")) {
                val t = stmt.trim()
                if (t.isNotEmpty()) s.execute(t)
            }
        }
    }

    @AfterEach
    fun tearDown() {
        conn.close()
    }

    private fun genJson(raw: String): JsonNode = GEN_MAPPER.readTree(raw)

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    fun testUpdatePayloadGen() {
        Queries.insertEvent(conn, "test", "{\"v\": 1}", "{\"source\": \"web\"}", "550e8400-e29b-41d4-a716-446655440007", "2024-06-01T12:00:00", null, null, null)
        Queries.updatePayload(conn, "{\"v\": 2, \"changed\": true}", null, 1)
        val ev = Queries.getEvent(conn, 1)!!
        assertNotNull(ev)
        assertEquals(genJson("{\"v\": 2, \"changed\": true}"), genJson(ev.payload))
        assertNull(ev.meta)
    }

    @Test
    fun testUpdateEventDateGen() {
        Queries.insertEvent(conn, "dated", "{}", null, "550e8400-e29b-41d4-a716-446655440008", "2024-06-01T12:00:00", null, "2024-01-01", null)
        Queries.updateEventDate(conn, "2024-12-31", 1)
        val ev = Queries.getEvent(conn, 1)!!
        assertNotNull(ev)
        assertEquals("2024-12-31", ev.eventDate)
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    fun testInsertEventRowsGen() {
        val n = Queries.insertEventRows(conn, "rowtest", "{}", null, "550e8400-e29b-41d4-a716-446655440009", "2024-06-01T12:00:00", null, null, null)
        assertEquals(1, n)
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    fun testListEventsGen() {
        Queries.insertEvent(conn, "alpha", "{}", null, "550e8400-e29b-41d4-a716-446655440001", "2024-06-01T12:00:00", null, null, null)
        Queries.insertEvent(conn, "beta", "{}", null, "550e8400-e29b-41d4-a716-446655440002", "2024-06-01T12:00:00", null, null, null)
        Queries.insertEvent(conn, "gamma", "{}", null, "550e8400-e29b-41d4-a716-446655440003", "2024-06-01T12:00:00", null, null, null)
        val events = Queries.listEvents(conn)
        assertEquals(3, events.size)
        assertEquals("alpha", events[0].name)
        assertEquals("beta", events[1].name)
        assertEquals("gamma", events[2].name)
    }

    @Test
    fun testGetEventsByDateRangeGen() {
        Queries.insertEvent(conn, "early", "{}", null, "550e8400-e29b-41d4-a716-446655440004", "2024-01-01T10:00:00", null, null, null)
        Queries.insertEvent(conn, "mid", "{}", null, "550e8400-e29b-41d4-a716-446655440005", "2024-06-01T12:00:00", null, null, null)
        Queries.insertEvent(conn, "late", "{}", null, "550e8400-e29b-41d4-a716-446655440006", "2024-12-01T15:00:00", null, null, null)
        val events = Queries.getEventsByDateRange(conn, "2024-01-01T00:00:00", "2024-07-01T00:00:00")
        assertEquals(2, events.size)
        assertEquals("early", events[0].name)
        assertEquals("mid", events[1].name)
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    fun testInsertAndGetEventGen() {
        Queries.insertEvent(conn, "login", "{\"type\": \"click\", \"x\": 10}", "{\"source\": \"web\"}", "550e8400-e29b-41d4-a716-446655440000", "2024-06-01T12:00:00", "2024-06-01T14:00:00Z", "2024-06-01", null)
        val ev = Queries.getEvent(conn, 1)!!
        assertNotNull(ev)
        assertEquals("login", ev.name)
        assertEquals(genJson("{\"type\": \"click\", \"x\": 10}"), genJson(ev.payload))
        assertEquals(genJson("{\"source\": \"web\"}"), genJson(ev.meta!!))
        assertEquals("550e8400-e29b-41d4-a716-446655440000", ev.docId)
        assertEquals("2024-06-01T12:00:00", ev.createdAt)
        assertEquals("2024-06-01T14:00:00Z", ev.scheduledAt)
        assertEquals("2024-06-01", ev.eventDate)
        assertNull(ev.eventTime)
    }

    @Test
    fun testGetEventNotFoundGen() {
        val result = Queries.getEvent(conn, 999)
        assertNull(result)
    }

    // ─── count queries ────────────────────────────────────────────────────────────

    @Test
    fun testCountEventsGen() {
        Queries.insertEvent(conn, "ev1", "{}", null, "550e8400-e29b-41d4-a716-44665544000c", "2024-06-01T00:00:00", null, null, null)
        Queries.insertEvent(conn, "ev2", "{}", null, "550e8400-e29b-41d4-a716-44665544000d", "2024-06-02T00:00:00", null, null, null)
        Queries.insertEvent(conn, "ev3", "{}", null, "550e8400-e29b-41d4-a716-44665544000e", "2024-06-03T00:00:00", null, null, null)
        val row = Queries.countEvents(conn, "2024-01-01T00:00:00")!!
        assertNotNull(row)
        assertEquals(3L, row.total)
    }

    // ─── projection queries ────────────────────────────────────────────────────────────

    @Test
    fun testFindByDateGen() {
        Queries.insertEvent(conn, "dated", "{}", null, "550e8400-e29b-41d4-a716-44665544000a", "2024-06-01T12:00:00", null, "2024-06-15", null)
        val row = Queries.findByDate(conn, "2024-06-15")!!
        assertNotNull(row)
        assertEquals("dated", row.name)
    }

    @Test
    fun testFindByUuidGen() {
        Queries.insertEvent(conn, "uuid-test", "{}", null, "550e8400-e29b-41d4-a716-44665544000b", "2024-06-01T12:00:00", null, null, null)
        val row = Queries.findByDocId(conn, "550e8400-e29b-41d4-a716-44665544000b")!!
        assertNotNull(row)
        assertEquals("uuid-test", row.name)
    }

}
