// Generated e2e runtime test — kotlin/sqlite. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.example.db.models.*
import com.example.db.queries.Queries
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.UUID

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private val GEN_MAPPER = ObjectMapper()
    private lateinit var conn: Connection

    @BeforeEach
    fun setUp() {
        conn = DriverManager.getConnection("jdbc:sqlite::memory:")
        conn.autoCommit = true
        val ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/type_overrides/sqlite/schema.sql"))
        conn.createStatement().use { s ->
            for (stmt in ddl.split(";")) {
                val t = stmt.trim()
                if (t.isNotEmpty()) s.execute(t)
            }
        }
    }

    @AfterEach
    fun tearDown() {
        conn.close()
    }

    private fun genJson(raw: String): JsonNode = GEN_MAPPER.readTree(raw)

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    fun testUpdatePayloadGen() {
        Queries.insertEvent(conn, "test", "{\"v\": 1}", "{\"source\": \"web\"}", UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        Queries.updatePayload(conn, "{\"v\": 2, \"changed\": true}", null, 1)
        val ev = Queries.getEvent(conn, 1)!!
        assertNotNull(ev)
        assertEquals(genJson("{\"v\": 2, \"changed\": true}"), genJson(ev.payload))
        assertNull(ev.meta)
    }

    @Test
    fun testUpdateEventDateGen() {
        Queries.insertEvent(conn, "dated", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, LocalDate.of(2024, 1, 1), null)
        Queries.updateEventDate(conn, LocalDate.of(2024, 12, 31), 1)
        val ev = Queries.getEvent(conn, 1)!!
        assertNotNull(ev)
        assertEquals(LocalDate.of(2024, 12, 31), ev.eventDate)
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    fun testInsertEventRowsGen() {
        val n = Queries.insertEventRows(conn, "rowtest", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        assertEquals(1L, n)
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    fun testListEventsGen() {
        val ts = LocalDateTime.of(2024, 6, 1, 12, 0, 0)
        Queries.insertEvent(conn, "alpha", "{}", null, UUID.randomUUID().toString(), ts, null, null, null)
        Queries.insertEvent(conn, "beta", "{}", null, UUID.randomUUID().toString(), ts, null, null, null)
        Queries.insertEvent(conn, "gamma", "{}", null, UUID.randomUUID().toString(), ts, null, null, null)
        val events = Queries.listEvents(conn)
        assertEquals(3, events.size)
        assertEquals("alpha", events[0].name)
        assertEquals("beta", events[1].name)
        assertEquals("gamma", events[2].name)
    }

    @Test
    fun testGetEventsByDateRangeGen() {
        Queries.insertEvent(conn, "early", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 1, 1, 10, 0, 0), null, null, null)
        Queries.insertEvent(conn, "mid", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        Queries.insertEvent(conn, "late", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 12, 1, 15, 0, 0), null, null, null)
        val events = Queries.getEventsByDateRange(conn, LocalDateTime.of(2024, 1, 1, 0, 0, 0), LocalDateTime.of(2024, 7, 1, 0, 0, 0))
        assertEquals(2, events.size)
        assertEquals("early", events[0].name)
        assertEquals("mid", events[1].name)
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    fun testInsertAndGetEventGen() {
        val doc_id = UUID.randomUUID().toString()
        Queries.insertEvent(conn, "login", "{\"type\": \"click\", \"x\": 10}", "{\"source\": \"web\"}", doc_id, LocalDateTime.of(2024, 6, 1, 12, 0, 0), LocalDateTime.of(2024, 6, 1, 14, 0, 0), LocalDate.of(2024, 6, 1), LocalTime.of(9, 0, 0))
        val ev = Queries.getEvent(conn, 1)!!
        assertNotNull(ev)
        assertEquals("login", ev.name)
        assertEquals(genJson("{\"type\": \"click\", \"x\": 10}"), genJson(ev.payload))
        assertEquals(genJson("{\"source\": \"web\"}"), genJson(ev.meta!!))
        assertEquals(doc_id, ev.docId)
        assertEquals(LocalDateTime.of(2024, 6, 1, 12, 0, 0), ev.createdAt)
        assertEquals(LocalDateTime.of(2024, 6, 1, 14, 0, 0), ev.scheduledAt)
        assertEquals(LocalDate.of(2024, 6, 1), ev.eventDate)
        assertEquals(LocalTime.of(9, 0, 0), ev.eventTime)
    }

    @Test
    fun testGetEventNotFoundGen() {
        val result = Queries.getEvent(conn, 999)
        assertNull(result)
    }

    // ─── count queries ────────────────────────────────────────────────────────────

    @Test
    fun testCountEventsGen() {
        Queries.insertEvent(conn, "ev1", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 0, 0, 0), null, null, null)
        Queries.insertEvent(conn, "ev2", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 2, 0, 0, 0), null, null, null)
        Queries.insertEvent(conn, "ev3", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 3, 0, 0, 0), null, null, null)
        val row = Queries.countEvents(conn, LocalDateTime.of(2024, 1, 1, 0, 0, 0))!!
        assertNotNull(row)
        assertEquals(3L, row.total)
    }

    // ─── projection queries ────────────────────────────────────────────────────────────

    @Test
    fun testFindByDateGen() {
        val target = LocalDate.of(2024, 6, 15)
        Queries.insertEvent(conn, "dated", "{}", null, UUID.randomUUID().toString(), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, target, null)
        val row = Queries.findByDate(conn, target)!!
        assertNotNull(row)
        assertEquals("dated", row.name)
    }

    @Test
    fun testFindByUuidGen() {
        val doc_id = UUID.randomUUID().toString()
        Queries.insertEvent(conn, "uuid-test", "{}", null, doc_id, LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        val row = Queries.findByDocId(conn, doc_id)!!
        assertNotNull(row)
        assertEquals("uuid-test", row.name)
    }

}
