// Generated e2e runtime test — java/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db;

import static org.junit.jupiter.api.Assertions.*;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.*;
import java.util.List;
import java.util.UUID;
import com.example.db.queries.Queries;
import com.example.db.models.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private static final ObjectMapper GEN_MAPPER = new ObjectMapper();
    private static final String URL =
        System.getenv().getOrDefault("DATABASE_URL",
            "jdbc:postgresql://localhost:15432/sqltgen_e2e");
    private static final String USER = "sqltgen";
    private static final String PASS = "sqltgen";

    private Connection conn;
    private String dbName;

    @BeforeEach
    void setUp() throws Exception {
        dbName = "test_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection admin = DriverManager.getConnection(URL, USER, PASS);
             Statement s = admin.createStatement()) {
            s.execute("CREATE DATABASE \"" + dbName + "\"");
        }
        String baseUrl = URL.replaceFirst("/[^/]*$", "/" + dbName);
        conn = DriverManager.getConnection(baseUrl, USER, PASS);
        conn.setAutoCommit(true);
        var ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/bookstore/postgresql/schema.sql"));
        try (Statement s = conn.createStatement()) {
            for (String stmt : ddl.split(";")) {
                String t = stmt.strip();
                if (!t.isEmpty()) s.execute(t);
            }
        }
    }

    @AfterEach
    void tearDown() throws Exception {
        if (conn != null) conn.close();
        try (Connection admin = DriverManager.getConnection(URL, USER, PASS);
             Statement s = admin.createStatement()) {
            s.execute("DROP DATABASE IF EXISTS \"" + dbName + "\"");
        }
    }

    private static JsonNode genJson(String raw) {
        try {
            return GEN_MAPPER.readTree(raw);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    void testAddSaleItemGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createCustomer(conn, "Customer", "c@example.com");
        Queries.createBook(conn, 1L, "Book", "sci-fi", new java.math.BigDecimal("10.0"), null);
        Queries.createSale(conn, 1L);
        Queries.addSaleItem(conn, 1L, 1L, 3, new java.math.BigDecimal("10.0"));
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    void testDeleteBookByIdGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1L, "Book1", "sci-fi", new java.math.BigDecimal("10.0"), null);
        var affected = Queries.deleteBookById(conn, 1L);
        assertEquals(1, affected);
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    void testListAuthorsGen() throws Exception {
        Queries.createAuthor(conn, "Asimov", null, 1920);
        Queries.createAuthor(conn, "Herbert", null, 1920);
        var authors = Queries.listAuthors(conn);
        assertEquals(2, authors.size());
        assertEquals("Asimov", authors.get(0).name());
        assertEquals("Herbert", authors.get(1).name());
    }

    @Test
    void testListBooksByGenreGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1L, "SciFi1", "sci-fi", new java.math.BigDecimal("9.99"), null);
        Queries.createBook(conn, 1L, "Fantasy1", "fantasy", new java.math.BigDecimal("11.99"), null);
        var books = Queries.listBooksByGenre(conn, "sci-fi");
        assertEquals(1, books.size());
        assertEquals("SciFi1", books.get(0).title());
    }

    @Test
    void testListBooksByGenreOrAllGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1L, "B1", "sci-fi", new java.math.BigDecimal("9.99"), null);
        Queries.createBook(conn, 1L, "B2", "fantasy", new java.math.BigDecimal("9.99"), null);
        var all_books = Queries.listBooksByGenreOrAll(conn, null);
        assertEquals(2, all_books.size());
        var scifi = Queries.listBooksByGenreOrAll(conn, "sci-fi");
        assertEquals(1, scifi.size());
    }

    @Test
    void testListBooksWithAuthorJoinGen() throws Exception {
        Queries.createAuthor(conn, "Author A", "Bio A", 1920);
        Queries.createBook(conn, 1L, "Book A", "sci-fi", new java.math.BigDecimal("9.99"), null);
        var rows = Queries.listBooksWithAuthor(conn);
        assertEquals(1, rows.size());
        assertEquals("Author A", rows.get(0).authorName());
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    void testGetAuthorGen() throws Exception {
        Queries.createAuthor(conn, "Asimov", "Sci-fi master", 1920);
        var author = Queries.getAuthor(conn, 1L).orElseThrow();
        assertNotNull(author);
        assertEquals("Asimov", author.name());
        assertEquals("Sci-fi master", author.bio());
        assertEquals(1920, author.birthYear());
    }

    @Test
    void testGetAuthorNotFoundGen() throws Exception {
        var result = Queries.getAuthor(conn, 999L);
        assertTrue(result.isEmpty());
    }

    @Test
    void testGetBookGen() throws Exception {
        Queries.createAuthor(conn, "Herbert", null, 1920);
        Queries.createBook(conn, 1L, "Dune", "sci-fi", new java.math.BigDecimal("12.99"), LocalDate.of(1965, 6, 1));
        var book = Queries.getBook(conn, 1L).orElseThrow();
        assertNotNull(book);
        assertEquals("Dune", book.title());
        assertEquals("sci-fi", book.genre());
    }

    // ─── aggregates ────────────────────────────────────────────────────────────

    @Test
    void testCountBooksByGenreGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1L, "B1", "sci-fi", new java.math.BigDecimal("10.0"), null);
        Queries.createBook(conn, 1L, "B2", "sci-fi", new java.math.BigDecimal("10.0"), null);
        Queries.createBook(conn, 1L, "B3", "fantasy", new java.math.BigDecimal("10.0"), null);
        var counts = Queries.countBooksByGenre(conn);
        assertEquals(2, counts.size());
    }

    // ─── filtering ────────────────────────────────────────────────────────────

    @Test
    void testGetBooksByPriceRangeGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1L, "Cheap", "sci-fi", new java.math.BigDecimal("5.99"), null);
        Queries.createBook(conn, 1L, "Mid", "sci-fi", new java.math.BigDecimal("10.5"), null);
        Queries.createBook(conn, 1L, "Expensive", "sci-fi", new java.math.BigDecimal("20.99"), null);
        var books = Queries.getBooksByPriceRange(conn, new java.math.BigDecimal("7.0"), new java.math.BigDecimal("15.0"));
        assertEquals(1, books.size());
        assertEquals("Mid", books.get(0).title());
    }

    @Test
    void testSearchBooksByTitleGen() throws Exception {
        Queries.createAuthor(conn, "A", null, 1900);
        Queries.createBook(conn, 1L, "Foundation", "sci-fi", new java.math.BigDecimal("9.99"), null);
        Queries.createBook(conn, 1L, "Dune", "sci-fi", new java.math.BigDecimal("12.99"), null);
        var books = Queries.searchBooksByTitle(conn, "%ound%");
        assertEquals(1, books.size());
        assertEquals("Foundation", books.get(0).title());
    }

    // ─── NULL handling ────────────────────────────────────────────────────────────

    @Test
    void testAuthorsWithNullBioGen() throws Exception {
        Queries.createAuthor(conn, "WithBio", "Has bio", 1900);
        Queries.createAuthor(conn, "NoBio", null, 1900);
        var authors = Queries.getAuthorsWithNullBio(conn);
        assertEquals(1, authors.size());
        assertEquals("NoBio", authors.get(0).name());
    }

    @Test
    void testAuthorsWithBioGen() throws Exception {
        Queries.createAuthor(conn, "WithBio", "Bio", 1900);
        Queries.createAuthor(conn, "NoBio", null, 1900);
        var authors = Queries.getAuthorsWithBio(conn);
        assertEquals(1, authors.size());
        assertEquals("WithBio", authors.get(0).name());
    }

}
