/**
 * Generated e2e runtime test — typescript/mysql. DO NOT EDIT.
 *
 * Auto-generated by scripts/e2e_testgen from test_spec.yaml.
 */
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes, randomUUID } from 'node:crypto';
import mysql from 'mysql2/promise';

import * as queries from './gen/queries';

const FIXTURES = join(__dirname, '../../../../fixtures/bookstore/mysql');
const MYSQL_HOST = process.env['MYSQL_HOST'] ?? '127.0.0.1';
const MYSQL_PORT = parseInt(process.env['MYSQL_PORT'] ?? '13306', 10);

const ROOT_CONFIG = {
  host: MYSQL_HOST,
  port: MYSQL_PORT,
  user: 'root',
  password: 'sqltgen',
  database: 'sqltgen_e2e',
};

const TEST_CONFIG = {
  host: MYSQL_HOST,
  port: MYSQL_PORT,
  user: 'sqltgen',
  password: 'sqltgen',
};

async function makeConn(): Promise<{ db: mysql.Connection; dbName: string }> {
  const dbName = 'test_' + randomBytes(16).toString('hex');
  const admin = await mysql.createConnection(ROOT_CONFIG);
  await admin.execute(`CREATE DATABASE \`${dbName}\``);
  await admin.execute(`GRANT ALL ON \`${dbName}\`.* TO 'sqltgen'@'%'`);
  await admin.end();
  const db = await mysql.createConnection({ ...TEST_CONFIG, database: dbName });
  const schemaSql = readFileSync(join(FIXTURES, 'schema.sql'), 'utf8');
  for (const stmt of schemaSql.split(';').map((s: string) => s.trim()).filter(Boolean)) {
    await db.execute(stmt);
  }
  return { db, dbName };
}

async function teardown(db: mysql.Connection, dbName: string): Promise<void> {
  await db.end();
  const admin = await mysql.createConnection(ROOT_CONFIG);
  await admin.execute(`DROP DATABASE IF EXISTS \`${dbName}\``);
  await admin.end();
}

// ─── :exec queries ────────────────────────────────────────────────────────────

describe(':exec queries', () => {
  it('add sale item', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createCustomer(db, 'Customer', 'c@example.com')
      await queries.createBook(db, 1, 'Book', 'sci-fi', 10.0, null)
      await queries.createSale(db, 1)
      await queries.addSaleItem(db, 1, 1, 3, 10.0)
    } finally { await teardown(db, dbName); }
  });

});

// ─── :execrows queries ────────────────────────────────────────────────────────────

describe(':execrows queries', () => {
  it('delete book by id', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createBook(db, 1, 'Book1', 'sci-fi', 10.0, null)
      const affected = await queries.deleteBookById(db, 1)
      assert.equal(Number(affected), 1)
    } finally { await teardown(db, dbName); }
  });

});

// ─── :many queries ────────────────────────────────────────────────────────────

describe(':many queries', () => {
  it('list authors', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'Asimov', null, 1920)
      await queries.createAuthor(db, 'Herbert', null, 1920)
      const authors = await queries.listAuthors(db)
      assert.equal(authors.length, 2)
      assert.equal(authors[0].name, 'Asimov')
      assert.equal(authors[1].name, 'Herbert')
    } finally { await teardown(db, dbName); }
  });

  it('list books by genre', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createBook(db, 1, 'SciFi1', 'sci-fi', 9.99, null)
      await queries.createBook(db, 1, 'Fantasy1', 'fantasy', 11.99, null)
      const books = await queries.listBooksByGenre(db, 'sci-fi')
      assert.equal(books.length, 1)
      assert.equal(books[0].title, 'SciFi1')
    } finally { await teardown(db, dbName); }
  });

  it('list books by genre or all', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createBook(db, 1, 'B1', 'sci-fi', 9.99, null)
      await queries.createBook(db, 1, 'B2', 'fantasy', 9.99, null)
      const all_books = await queries.listBooksByGenreOrAll(db, null)
      assert.equal(all_books.length, 2)
      const scifi = await queries.listBooksByGenreOrAll(db, 'sci-fi')
      assert.equal(scifi.length, 1)
    } finally { await teardown(db, dbName); }
  });

  it('list books with author join', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'Author A', 'Bio A', 1920)
      await queries.createBook(db, 1, 'Book A', 'sci-fi', 9.99, null)
      const rows = await queries.listBooksWithAuthor(db)
      assert.equal(rows.length, 1)
      assert.equal(rows[0].author_name, 'Author A')
    } finally { await teardown(db, dbName); }
  });

});

// ─── :one queries ────────────────────────────────────────────────────────────

describe(':one queries', () => {
  it('get author', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'Asimov', 'Sci-fi master', 1920)
      const author = await queries.getAuthor(db, 1)
      assert.ok(author)
      assert.equal(author.name, 'Asimov')
      assert.equal(author.bio, 'Sci-fi master')
      assert.equal(Number(author.birth_year), 1920)
    } finally { await teardown(db, dbName); }
  });

  it('get author not found', async () => {
    const { db, dbName } = await makeConn();
    try {
      const result = await queries.getAuthor(db, 999)
      assert.equal(result, null)
    } finally { await teardown(db, dbName); }
  });

  it('get book', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'Herbert', null, 1920)
      await queries.createBook(db, 1, 'Dune', 'sci-fi', 12.99, '1965-06-01')
      const book = await queries.getBook(db, 1)
      assert.ok(book)
      assert.equal(book.title, 'Dune')
      assert.equal(book.genre, 'sci-fi')
    } finally { await teardown(db, dbName); }
  });

});

// ─── aggregates ────────────────────────────────────────────────────────────

describe('aggregates', () => {
  it('count books by genre', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createBook(db, 1, 'B1', 'sci-fi', 10.0, null)
      await queries.createBook(db, 1, 'B2', 'sci-fi', 10.0, null)
      await queries.createBook(db, 1, 'B3', 'fantasy', 10.0, null)
      const counts = await queries.countBooksByGenre(db)
      assert.equal(counts.length, 2)
    } finally { await teardown(db, dbName); }
  });

});

// ─── filtering ────────────────────────────────────────────────────────────

describe('filtering', () => {
  it('get books by price range', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createBook(db, 1, 'Cheap', 'sci-fi', 5.99, null)
      await queries.createBook(db, 1, 'Mid', 'sci-fi', 10.5, null)
      await queries.createBook(db, 1, 'Expensive', 'sci-fi', 20.99, null)
      const books = await queries.getBooksByPriceRange(db, 7.0, 15.0)
      assert.equal(books.length, 1)
      assert.equal(books[0].title, 'Mid')
    } finally { await teardown(db, dbName); }
  });

  it('search books by title', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'A', null, 1900)
      await queries.createBook(db, 1, 'Foundation', 'sci-fi', 9.99, null)
      await queries.createBook(db, 1, 'Dune', 'sci-fi', 12.99, null)
      const books = await queries.searchBooksByTitle(db, '%ound%')
      assert.equal(books.length, 1)
      assert.equal(books[0].title, 'Foundation')
    } finally { await teardown(db, dbName); }
  });

});

// ─── NULL handling ────────────────────────────────────────────────────────────

describe('NULL handling', () => {
  it('authors with null bio', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'WithBio', 'Has bio', 1900)
      await queries.createAuthor(db, 'NoBio', null, 1900)
      const authors = await queries.getAuthorsWithNullBio(db)
      assert.equal(authors.length, 1)
      assert.equal(authors[0].name, 'NoBio')
    } finally { await teardown(db, dbName); }
  });

  it('authors with bio', async () => {
    const { db, dbName } = await makeConn();
    try {
      await queries.createAuthor(db, 'WithBio', 'Bio', 1900)
      await queries.createAuthor(db, 'NoBio', null, 1900)
      const authors = await queries.getAuthorsWithBio(db)
      assert.equal(authors.length, 1)
      assert.equal(authors[0].name, 'WithBio')
    } finally { await teardown(db, dbName); }
  });

});

