use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::GeneratedFile;
use crate::config::{ListParamStrategy, OutputConfig};

use super::core::{emit_mysql_query, emit_pg_query, emit_sqlite_query, QueryContext};
use super::{JsOutput, JsTarget};

pub(super) struct TsCoreContract {
    pub(super) output: JsOutput,
    pub(super) runtime_hint: &'static str,
    pub(super) date_as_string: bool,
    pub(super) normalize_sql: fn(&str) -> String,
    pub(super) emit_query: fn(&mut String, &QueryContext, &ListParamStrategy) -> anyhow::Result<()>,
    pub(super) helper_content: String,
}

fn passthrough_sql(sql: &str) -> String {
    sql.to_string()
}

fn anon_sql(sql: &str) -> String {
    crate::backend::sql_rewrite::rewrite_to_anon_params(sql)
}

pub(super) fn resolve_ts_contract(target: JsTarget, output: JsOutput) -> TsCoreContract {
    match target {
        JsTarget::Postgres => TsCoreContract {
            output,
            runtime_hint: "pg (node-postgres) — npm install pg",
            date_as_string: false,
            normalize_sql: passthrough_sql,
            emit_query: emit_pg_query,
            helper_content: build_helper_file(target, output),
        },
        JsTarget::Sqlite => TsCoreContract {
            output,
            runtime_hint: "better-sqlite3 — npm install better-sqlite3",
            date_as_string: false,
            normalize_sql: anon_sql,
            emit_query: emit_sqlite_query,
            helper_content: build_helper_file(target, output),
        },
        JsTarget::Mysql => TsCoreContract {
            output,
            runtime_hint: "mysql2 — npm install mysql2",
            date_as_string: true,
            normalize_sql: anon_sql,
            emit_query: emit_mysql_query,
            helper_content: build_helper_file(target, output),
        },
    }
}

pub(super) fn emit_helper_file(contract: &TsCoreContract, config: &OutputConfig, ext: &str) -> GeneratedFile {
    GeneratedFile { path: PathBuf::from(&config.out).join(format!("_sqltgen.{ext}")), content: contract.helper_content.clone() }
}

fn build_helper_file(target: JsTarget, output: JsOutput) -> String {
    let mut src = String::new();
    let _ = writeln!(src, "// Generated by sqltgen. Do not edit.");
    let _ = writeln!(src);
    match output {
        JsOutput::TypeScript => {
            match target {
                JsTarget::Postgres => {
                    let _ = writeln!(src, "import type {{ ClientBase }} from 'pg';");
                    let _ = writeln!(src, "export type Db = ClientBase;");
                },
                JsTarget::Sqlite => {
                    let _ = writeln!(src, "import type {{ Database }} from 'better-sqlite3';");
                    let _ = writeln!(src, "export type Db = Database;");
                },
                JsTarget::Mysql => {
                    let _ = writeln!(src, "import type {{ Connection }} from 'mysql2/promise';");
                    let _ = writeln!(src, "export type Db = Connection;");
                },
            }
            let _ = writeln!(src, "export type ConnectFn = () => Db | Promise<Db>;");
            let _ = writeln!(src, "type ClosableDb = Db & {{ release?: () => void; close?: () => void }};");
            let _ = writeln!(src);
            let _ = writeln!(src, "export async function releaseDb(db: Db): Promise<void> {{");
            let _ = writeln!(src, "  const closable = db as ClosableDb;");
            let _ = writeln!(src, "  if (typeof closable.release === 'function') {{");
            let _ = writeln!(src, "    closable.release();");
            let _ = writeln!(src, "    return;");
            let _ = writeln!(src, "  }}");
            let _ = writeln!(src, "  if (typeof closable.close === 'function') {{");
            let _ = writeln!(src, "    closable.close();");
            let _ = writeln!(src, "  }}");
            let _ = writeln!(src, "}}");
        },
        JsOutput::JavaScript => {
            match target {
                JsTarget::Postgres => {
                    let _ = writeln!(src, "/** @typedef {{import('pg').ClientBase}} Db */");
                },
                JsTarget::Sqlite => {
                    let _ = writeln!(src, "/** @typedef {{import('better-sqlite3').Database}} Db */");
                },
                JsTarget::Mysql => {
                    let _ = writeln!(src, "/** @typedef {{import('mysql2/promise').Connection}} Db */");
                },
            }
            let _ = writeln!(src, "/** @typedef {{() => Db | Promise<Db>}} ConnectFn */");
            let _ = writeln!(src);
            let _ = writeln!(src, "/** @param {{Db}} db */");
            let _ = writeln!(src, "export async function releaseDb(db) {{");
            let _ = writeln!(src, "  if (typeof db.release === 'function') {{");
            let _ = writeln!(src, "    db.release();");
            let _ = writeln!(src, "    return;");
            let _ = writeln!(src, "  }}");
            let _ = writeln!(src, "  if (typeof db.close === 'function') {{");
            let _ = writeln!(src, "    db.close();");
            let _ = writeln!(src, "  }}");
            let _ = writeln!(src, "}}");
        },
    }
    src
}
