use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::common::{
    group_queries, has_inline_rows, infer_row_type_name, infer_table, model_file_stem, model_name, needed_enums, querier_class_name, queries_file_stem,
    row_type_name as inline_row_type_name, sql_const_name,
};
use crate::backend::naming::{to_camel_case, to_pascal_case, to_screaming_snake_case};
use crate::backend::sql_rewrite::{positional_bind_names, rewrite_to_anon_params, split_at_in_clause};
use crate::backend::GeneratedFile;
use crate::config::{ListParamStrategy, OutputConfig};
use crate::ir::{EnumType, Parameter, Query, QueryCmd, Schema, SqlType, Table};

use super::adapter::JsDriverAdapter;
use super::typemap::JsTypeMap;
use super::{JsOutput, TypeScriptCodegen};

#[cfg(test)]
use super::JsTarget;

/// All data needed for a single `generate()` call, bundled to reduce parameter threading.
pub(super) struct GenerationContext<'a> {
    pub schema: &'a Schema,
    pub queries: &'a [Query],
    pub config: &'a OutputConfig,
    pub adapter: &'a dyn JsDriverAdapter,
    pub type_map: &'a JsTypeMap,
    pub strategy: ListParamStrategy,
}

/// Per-query context computed once and forwarded to body helpers.
pub(super) struct QueryContext<'a> {
    query: &'a Query,
    schema: &'a Schema,
    adapter: &'a dyn JsDriverAdapter,
    type_map: &'a JsTypeMap,
    fn_name: String,
    ret: String,
    conn_type: &'static str,
}

impl<'a> QueryContext<'a> {
    fn new(query: &'a Query, schema: &'a Schema, adapter: &'a dyn JsDriverAdapter, type_map: &'a JsTypeMap, conn_type: &'static str) -> Self {
        Self { fn_name: to_camel_case(&query.name), ret: return_type(query, schema), query, schema, adapter, type_map, conn_type }
    }

    fn params(&self) -> Vec<&'a Parameter> {
        self.query.params.iter().collect()
    }
}

pub(super) fn generate_core_files(codegen: &TypeScriptCodegen, ctx: &GenerationContext) -> anyhow::Result<Vec<GeneratedFile>> {
    let ext = codegen.ext();
    let ds = ctx.schema.default_schema.as_deref();
    let mut files = Vec::new();
    for table in &ctx.schema.tables {
        let content = codegen.emit_model_file(table, ds, ctx.config)?;
        let file_stem = model_file_stem(table, ds);
        files.push(GeneratedFile { path: PathBuf::from(&ctx.config.out).join("models").join(format!("{file_stem}.{ext}")), content });
    }
    for e in &ctx.schema.enums {
        let content = codegen.emit_enum_file(e)?;
        files.push(GeneratedFile { path: PathBuf::from(&ctx.config.out).join("models").join(format!("{}.{ext}", e.name)), content });
    }
    let groups = group_queries(ctx.queries);
    let mut group_stems: Vec<String> = Vec::new();
    for (group, group_queries) in &groups {
        let stem = queries_file_stem(group).to_string();
        group_stems.push(stem.clone());
        let content = build_queries_file_with_adapter(ctx, group, group_queries)?;
        files.push(GeneratedFile { path: PathBuf::from(&ctx.config.out).join("queries").join(format!("{stem}.{ext}")), content });
    }
    let index_content = codegen.emit_index_file(ctx.schema, &group_stems)?;
    files.push(GeneratedFile { path: PathBuf::from(&ctx.config.out).join(format!("index.{ext}")), content: index_content });
    // models/index.{ext}
    if !ctx.schema.tables.is_empty() || !ctx.schema.enums.is_empty() {
        let stems: Vec<String> = ctx.schema.tables.iter().map(|t| model_file_stem(t, ds)).chain(ctx.schema.enums.iter().map(|e| e.name.clone())).collect();
        let content = codegen.emit_subdir_index_file(&stems)?;
        files.push(GeneratedFile { path: PathBuf::from(&ctx.config.out).join("models").join(format!("index.{ext}")), content });
    }
    // queries/index.{ext}
    if !group_stems.is_empty() {
        let content = codegen.emit_subdir_index_file(&group_stems)?;
        files.push(GeneratedFile { path: PathBuf::from(&ctx.config.out).join("queries").join(format!("index.{ext}")), content });
    }
    Ok(files)
}

impl TypeScriptCodegen {
    /// Returns the file extension: `"ts"` for TypeScript, `"js"` for JavaScript.
    pub(crate) fn ext(&self) -> &'static str {
        match self.output {
            JsOutput::TypeScript => "ts",
            JsOutput::JavaScript => "js",
        }
    }

    pub(crate) fn emit_model_file(&self, table: &Table, default_schema: Option<&str>, config: &OutputConfig) -> anyhow::Result<String> {
        let adapter = super::adapter::build_adapter(self.target, self.output);
        let type_map = super::typemap::build_js_type_map(config, adapter.as_ref());
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;

        // Import any enum types referenced by this table's columns.
        let mut enum_imports: BTreeSet<String> = BTreeSet::new();
        for col in &table.columns {
            crate::backend::common::collect_enum_names_from_type(&col.sql_type, &mut enum_imports);
        }
        if !enum_imports.is_empty() {
            writeln!(src)?;
            let import_ext = match self.output {
                JsOutput::TypeScript => "",
                JsOutput::JavaScript => ".js",
            };
            for name in &enum_imports {
                let pascal = to_pascal_case(name);
                match self.output {
                    JsOutput::TypeScript => writeln!(src, "import type {{ {pascal} }} from './{name}{import_ext}';")?,
                    JsOutput::JavaScript => writeln!(src, "/** @typedef {{import('./{name}{import_ext}').{pascal}}} {pascal} */")?,
                }
            }
        }

        writeln!(src)?;
        let name = model_name(table, default_schema);
        let fields: Vec<(&str, &SqlType, bool)> = table.columns.iter().map(|c| (c.name.as_str(), &c.sql_type, c.nullable)).collect();
        match self.output {
            JsOutput::TypeScript => emit_ts_interface(&mut src, &name, &fields, &type_map)?,
            JsOutput::JavaScript => emit_js_typedef(&mut src, &name, &fields, &type_map)?,
        }
        Ok(src)
    }

    /// Emit a model file for a single enum type.
    pub(crate) fn emit_enum_file(&self, e: &EnumType) -> anyhow::Result<String> {
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        let name = to_pascal_case(&e.name);
        match self.output {
            JsOutput::TypeScript => emit_ts_enum(&mut src, &name, e)?,
            JsOutput::JavaScript => emit_js_enum(&mut src, &name, e)?,
        }
        Ok(src)
    }

    pub(crate) fn emit_index_file(&self, schema: &Schema, group_stems: &[String]) -> anyhow::Result<String> {
        // TypeScript imports must not use .ts extensions; JS (ESM) requires .js.
        let (models_ref, queries_ref, helper_ref) = match self.output {
            JsOutput::TypeScript => ("'./models'", "'./queries'", "'./sqltgen'"),
            JsOutput::JavaScript => ("'./models/index.js'", "'./queries/index.js'", "'./sqltgen.js'"),
        };
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        if !schema.tables.is_empty() || !schema.enums.is_empty() {
            writeln!(src, "export * from {models_ref};")?;
        }
        if !group_stems.is_empty() {
            writeln!(src, "export * from {queries_ref};")?;
        }
        writeln!(src, "export * from {helper_ref};")?;
        Ok(src)
    }

    /// Emit an `index.{ext}` barrel file that re-exports all named stems.
    pub(crate) fn emit_subdir_index_file(&self, stems: &[String]) -> anyhow::Result<String> {
        let ext = self.ext();
        let import_ext = match self.output {
            JsOutput::TypeScript => "".to_string(),
            JsOutput::JavaScript => format!(".{ext}"),
        };
        let mut src = String::new();
        writeln!(src, "// Generated by sqltgen. Do not edit.")?;
        writeln!(src)?;
        for stem in stems {
            writeln!(src, "export * from './{stem}{import_ext}';")?;
        }
        Ok(src)
    }
}

// ─── Type emission ────────────────────────────────────────────────────────────

/// Emit a TypeScript `interface` block for the given fields.
fn emit_ts_interface(src: &mut String, name: &str, fields: &[(&str, &SqlType, bool)], type_map: &JsTypeMap) -> anyhow::Result<()> {
    writeln!(src, "export interface {name} {{")?;
    for (fname, ftype, nullable) in fields {
        writeln!(src, "  {fname}: {};", type_map.field_type(ftype, *nullable))?;
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Emit a JSDoc `@typedef` block for the given fields.
fn emit_js_typedef(src: &mut String, name: &str, fields: &[(&str, &SqlType, bool)], type_map: &JsTypeMap) -> anyhow::Result<()> {
    writeln!(src, "/**")?;
    writeln!(src, " * @typedef {{Object}} {name}")?;
    for (fname, ftype, nullable) in fields {
        let ty = type_map.field_type(ftype, *nullable);
        writeln!(src, " * @property {{{ty}}} {fname}")?;
    }
    writeln!(src, " */")?;
    Ok(())
}

/// Emit a TypeScript union type for a SQL enum.
fn emit_ts_enum(src: &mut String, name: &str, e: &EnumType) -> anyhow::Result<()> {
    let variants: Vec<String> = e.variants.iter().map(|v| format!("\"{}\"", v)).collect();
    writeln!(src, "export type {name} = {};", variants.join(" | "))?;
    Ok(())
}

/// Emit a JavaScript frozen object enum for a SQL enum.
fn emit_js_enum(src: &mut String, name: &str, e: &EnumType) -> anyhow::Result<()> {
    writeln!(src, "/** @readonly @enum {{string}} */")?;
    writeln!(src, "export const {name} = Object.freeze(/** @type {{const}} */ ({{")?;
    for v in &e.variants {
        let variant_name = to_screaming_snake_case(v);
        writeln!(src, "  {variant_name}: \"{v}\",")?;
    }
    writeln!(src, "}}));")?;
    Ok(())
}

/// Emit the inline row type for a query whose result doesn't match any schema table.
fn emit_inline_row_type_with_adapter(src: &mut String, query: &Query, adapter: &dyn JsDriverAdapter, type_map: &JsTypeMap) -> anyhow::Result<()> {
    let name = inline_row_type_name(&query.name);
    let fields: Vec<(&str, &SqlType, bool)> = query.result_columns.iter().map(|c| (c.name.as_str(), &c.sql_type, c.nullable)).collect();
    match adapter.output() {
        JsOutput::TypeScript => emit_ts_interface(src, &name, &fields, type_map),
        JsOutput::JavaScript => emit_js_typedef(src, &name, &fields, type_map),
    }
}

#[cfg(test)]
pub(super) fn js_type(sql_type: &SqlType, nullable: bool, target: &JsTarget) -> String {
    let adapter = super::adapter::build_adapter(*target, JsOutput::TypeScript);
    super::typemap::build_js_type_map(&OutputConfig::default(), adapter.as_ref()).field_type(sql_type, nullable)
}

// ─── Queries file ─────────────────────────────────────────────────────────────

fn build_queries_file_with_adapter(ctx: &GenerationContext, group: &str, queries: &[Query]) -> anyhow::Result<String> {
    let mut src = String::new();
    writeln!(src, "// Generated by sqltgen. Do not edit.")?;
    writeln!(src, "// Runtime: {}", ctx.adapter.runtime_hint())?;
    emit_runtime_imports(&mut src, ctx.adapter)?;
    let ds = ctx.schema.default_schema.as_deref();
    emit_table_imports(&mut src, &needed_tables(queries, ctx.schema), ds, ctx.adapter.output())?;
    emit_enum_imports(&mut src, &needed_enums(&queries.iter().collect::<Vec<_>>()), ctx.adapter.output())?;
    writeln!(src)?;
    emit_sql_constants(&mut src, queries, ctx.adapter, &ctx.strategy)?;
    for query in queries {
        writeln!(src)?;
        if has_inline_rows(query, ctx.schema) {
            emit_inline_row_type_with_adapter(&mut src, query, ctx.adapter, ctx.type_map)?;
            writeln!(src)?;
        }
        emit_query(&mut src, query, ctx)?;
    }
    if !queries.is_empty() {
        writeln!(src)?;
        emit_querier_class(&mut src, group, queries, ctx)?;
    }
    Ok(src)
}

#[cfg(test)]
pub(super) fn build_queries_file(
    group: &str,
    queries: &[Query],
    schema: &Schema,
    target: &JsTarget,
    output: &JsOutput,
    config: &OutputConfig,
) -> anyhow::Result<String> {
    let adapter = super::adapter::build_adapter(*target, *output);
    let type_map = super::typemap::build_js_type_map(config, adapter.as_ref());
    let strategy = config.list_params.clone().unwrap_or_default();
    let ctx = GenerationContext { schema, queries, config, adapter: adapter.as_ref(), type_map: &type_map, strategy };
    build_queries_file_with_adapter(&ctx, group, queries)
}

#[cfg(test)]
pub(super) fn emit_inline_row_type(src: &mut String, query: &Query, output: &JsOutput, target: &JsTarget, config: &OutputConfig) -> anyhow::Result<()> {
    let adapter = super::adapter::build_adapter(*target, *output);
    let type_map = super::typemap::build_js_type_map(config, adapter.as_ref());
    emit_inline_row_type_with_adapter(src, query, adapter.as_ref(), &type_map)
}

fn emit_querier_class(src: &mut String, group: &str, queries: &[Query], ctx: &GenerationContext) -> anyhow::Result<()> {
    let class_name = querier_class_name(group);
    match ctx.adapter.output() {
        JsOutput::TypeScript => {
            writeln!(src, "export class {class_name} {{")?;
            writeln!(src, "  constructor(private readonly connect: ConnectFn) {{}}")?;
            for query in queries {
                writeln!(src)?;
                emit_ts_querier_method(src, query, ctx.schema, ctx.type_map)?;
            }
            writeln!(src, "}}")?;
        },
        JsOutput::JavaScript => {
            writeln!(src, "export class {class_name} {{")?;
            writeln!(src, "  /** @param {{ConnectFn}} connect */")?;
            writeln!(src, "  constructor(connect) {{")?;
            writeln!(src, "    this.connect = connect;")?;
            writeln!(src, "  }}")?;
            for query in queries {
                writeln!(src)?;
                emit_js_querier_method(src, query)?;
            }
            writeln!(src, "}}")?;
        },
    }
    Ok(())
}

fn emit_ts_querier_method(src: &mut String, query: &Query, schema: &Schema, type_map: &JsTypeMap) -> anyhow::Result<()> {
    let fn_name = to_camel_case(&query.name);
    let ret = return_type(query, schema);
    let params = query
        .params
        .iter()
        .map(|p| {
            let ty = if p.is_list {
                let elem = type_map.param_type(&p.sql_type, false);
                format!("{elem}[]")
            } else {
                type_map.param_type(&p.sql_type, p.nullable)
            };
            format!("{}: {ty}", to_camel_case(&p.name))
        })
        .collect::<Vec<_>>()
        .join(", ");
    let args = query.params.iter().map(|p| to_camel_case(&p.name)).collect::<Vec<_>>().join(", ");

    writeln!(src, "  async {fn_name}({params}): Promise<{ret}> {{")?;
    writeln!(src, "    const db = await this.connect();")?;
    writeln!(src, "    try {{")?;
    if args.is_empty() {
        writeln!(src, "      return {fn_name}(db);")?;
    } else {
        writeln!(src, "      return {fn_name}(db, {args});")?;
    }
    writeln!(src, "    }} finally {{")?;
    writeln!(src, "      await releaseDb(db);")?;
    writeln!(src, "    }}")?;
    writeln!(src, "  }}")?;
    Ok(())
}

fn emit_js_querier_method(src: &mut String, query: &Query) -> anyhow::Result<()> {
    let fn_name = to_camel_case(&query.name);
    let params = query.params.iter().map(|p| to_camel_case(&p.name)).collect::<Vec<_>>().join(", ");
    let args = if params.is_empty() { "db".to_string() } else { format!("db, {params}") };
    writeln!(src, "  async {fn_name}({params}) {{")?;
    writeln!(src, "    const db = await this.connect();")?;
    writeln!(src, "    try {{")?;
    writeln!(src, "      return {fn_name}({args});")?;
    writeln!(src, "    }} finally {{")?;
    writeln!(src, "      await releaseDb(db);")?;
    writeln!(src, "    }}")?;
    writeln!(src, "  }}")?;
    Ok(())
}

/// Collect the schema tables used as return types by any query.
fn needed_tables<'a>(queries: &[Query], schema: &'a Schema) -> Vec<&'a Table> {
    let mut tables: Vec<&Table> = queries.iter().filter_map(|q| infer_table(q, schema)).collect();
    tables.sort_by_key(|t| &t.name);
    tables.dedup_by_key(|t| &t.name);
    tables
}

/// Emit imports for the generated runtime helper module.
fn emit_runtime_imports(src: &mut String, adapter: &dyn JsDriverAdapter) -> anyhow::Result<()> {
    match adapter.output() {
        JsOutput::TypeScript => {
            writeln!(src, "import type {{ ConnectFn, Db }} from '../sqltgen';")?;
            writeln!(src, "import {{ releaseDb }} from '../sqltgen';")?;
        },
        JsOutput::JavaScript => {
            writeln!(src, "import {{ releaseDb }} from '../sqltgen.js';")?;
            writeln!(src, "/** @typedef {{import('../sqltgen.js').Db}} Db */")?;
            writeln!(src, "/** @typedef {{import('../sqltgen.js').ConnectFn}} ConnectFn */")?;
        },
    }
    Ok(())
}

/// Emit table type imports into the queries file.
fn emit_table_imports(src: &mut String, tables: &[&Table], default_schema: Option<&str>, output: JsOutput) -> anyhow::Result<()> {
    if tables.is_empty() {
        return Ok(());
    }
    writeln!(src)?;
    for table in tables {
        let class_name = model_name(table, default_schema);
        let file_stem = model_file_stem(table, default_schema);
        match output {
            JsOutput::TypeScript => writeln!(src, "import type {{ {class_name} }} from '../models/{file_stem}';")?,
            JsOutput::JavaScript => writeln!(src, "/** @typedef {{import('../models/{file_stem}.js').{class_name}}} {class_name} */")?,
        }
    }
    Ok(())
}

/// Emit enum type imports into the queries file.
fn emit_enum_imports(src: &mut String, enums: &BTreeSet<String>, output: JsOutput) -> anyhow::Result<()> {
    if enums.is_empty() {
        return Ok(());
    }
    writeln!(src)?;
    for name in enums {
        let class_name = to_pascal_case(name);
        match output {
            JsOutput::TypeScript => writeln!(src, "import type {{ {class_name} }} from '../models/{name}';")?,
            JsOutput::JavaScript => writeln!(src, "/** @typedef {{import('../models/{name}.js').{class_name}}} {class_name} */")?,
        }
    }
    Ok(())
}

/// Emit SQL string constants for all non-dynamic-list queries.
fn emit_sql_constants(src: &mut String, queries: &[Query], adapter: &dyn JsDriverAdapter, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    for query in queries {
        if query.params.iter().any(|p| p.is_list) && *strategy == ListParamStrategy::Dynamic {
            continue;
        }
        let const_name = sql_const_name(&query.name);
        let sql = match query.params.iter().find(|p| p.is_list) {
            Some(lp) => {
                let raw = lp.native_list_sql.as_deref().unwrap_or(&query.sql);
                adapter.apply_native_list_sql(raw, lp)
            },
            None => adapter.normalize_sql(&query.sql),
        };
        let sql = sql.trim_end().trim_end_matches(';');
        let sql = sql.replace('`', "\\`").replace("${", "\\${");
        writeln!(src, "const {const_name} = `{sql}`;")?;
    }
    Ok(())
}

// ─── Query function emission ──────────────────────────────────────────────────

fn emit_query(src: &mut String, query: &Query, ctx: &GenerationContext) -> anyhow::Result<()> {
    let qctx = QueryContext::new(query, ctx.schema, ctx.adapter, ctx.type_map, "Db");
    ctx.adapter.emit_query(src, &qctx, &ctx.strategy)
}

/// Emit the JSDoc annotation block for a query function (JS output only).
fn emit_jsdoc(src: &mut String, ctx: &QueryContext, params: &[&Parameter]) -> anyhow::Result<()> {
    if matches!(ctx.adapter.output(), JsOutput::TypeScript) {
        return Ok(());
    }
    writeln!(src, "/**")?;
    writeln!(src, " * @param {{{}}} db", ctx.conn_type)?;
    for p in params {
        let ty = if p.is_list {
            let elem = ctx.type_map.param_type(&p.sql_type, false);
            format!("{elem}[]")
        } else {
            ctx.type_map.param_type(&p.sql_type, p.nullable)
        };
        writeln!(src, " * @param {{{ty}}} {}", to_camel_case(&p.name))?;
    }
    writeln!(src, " * @returns {{Promise<{}>}}", ctx.ret)?;
    writeln!(src, " */")?;
    Ok(())
}

/// Emit the `export async function` opening line.
/// TypeScript includes type annotations; JavaScript uses plain parameter names.
fn emit_fn_open(src: &mut String, ctx: &QueryContext, params: &[&Parameter]) -> anyhow::Result<()> {
    match ctx.adapter.output() {
        JsOutput::TypeScript => {
            let typed: Vec<String> = params
                .iter()
                .map(|p| {
                    let ty = if p.is_list {
                        let elem = ctx.type_map.param_type(&p.sql_type, false);
                        format!("{elem}[]")
                    } else {
                        ctx.type_map.param_type(&p.sql_type, p.nullable)
                    };
                    format!("{}: {ty}", to_camel_case(&p.name))
                })
                .collect();
            let sig = std::iter::once(format!("db: {}", ctx.conn_type)).chain(typed).collect::<Vec<_>>().join(", ");
            writeln!(src, "export async function {}({sig}): Promise<{}> {{", ctx.fn_name, ctx.ret)?;
        },
        JsOutput::JavaScript => {
            let names: Vec<String> = std::iter::once("db".to_string()).chain(params.iter().map(|p| to_camel_case(&p.name))).collect();
            writeln!(src, "export async function {}({}) {{", ctx.fn_name, names.join(", "))?;
        },
    }
    Ok(())
}

/// Compute the JS/TS return type string for a query.
fn return_type(query: &Query, schema: &Schema) -> String {
    let row = ts_row_type(query, schema);
    match query.cmd {
        QueryCmd::One => format!("{row} | null"),
        QueryCmd::Many => format!("{row}[]"),
        QueryCmd::Exec => "void".to_string(),
        QueryCmd::ExecRows => "number".to_string(),
    }
}

/// Compute the row type name for a query result (table name or `{Query}Row`).
fn ts_row_type(query: &Query, schema: &Schema) -> String {
    infer_row_type_name(query, schema).unwrap_or_else(|| inline_row_type_name(&query.name))
}

// ─── PostgreSQL (pg) ─────────────────────────────────────────────────────────

pub(super) fn emit_pg_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = ctx.query.params.iter().find(|p| p.is_list) {
        return emit_pg_list_query(src, ctx, strategy, lp);
    }
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    emit_jsdoc(src, ctx, &params)?;
    emit_fn_open(src, ctx, &params)?;
    let args = pg_params_array(ctx.query, ctx.type_map);
    emit_pg_body(src, ctx, &const_name, &args)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Emit the query body for a PostgreSQL function: the `db.query(...)` call and result handling.
///
/// Accepts either a SQL constant name (static query) or a runtime `sql` variable (dynamic list
/// expansion) as `sql_expr`, and the pre-built params array string as `args`.
fn emit_pg_body(src: &mut String, ctx: &QueryContext, sql_expr: &str, args: &str) -> anyhow::Result<()> {
    match ctx.query.cmd {
        QueryCmd::Exec => writeln!(src, "  await db.query({sql_expr}, {args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = await db.query({sql_expr}, {args});")?;
            writeln!(src, "  return result.rowCount ?? 0;")?;
        },
        QueryCmd::One => {
            let row = ts_row_type(ctx.query, ctx.schema);
            let call = pg_query_call(sql_expr, &row, args, ctx.adapter.output());
            writeln!(src, "  const result = await {call};")?;
            if let Some(transform) = ctx.type_map.row_transform_expr(ctx.query, "raw") {
                writeln!(src, "  const raw = result.rows[0];")?;
                writeln!(src, "  if (!raw) return null;")?;
                writeln!(src, "  return {transform};")?;
            } else {
                writeln!(src, "  return result.rows[0] ?? null;")?;
            }
        },
        QueryCmd::Many => {
            let row = ts_row_type(ctx.query, ctx.schema);
            let call = pg_query_call(sql_expr, &row, args, ctx.adapter.output());
            writeln!(src, "  const result = await {call};")?;
            if let Some(transform) = ctx.type_map.row_transform_expr(ctx.query, "raw") {
                writeln!(src, "  return result.rows.map(raw => ({transform}));")?;
            } else {
                writeln!(src, "  return result.rows;")?;
            }
        },
    }
    Ok(())
}

/// Build `db.query<Row>(sql, args)` for TypeScript or `db.query(sql, args)` for JavaScript.
fn pg_query_call(const_name: &str, row_type: &str, args: &str, output: JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!("db.query<{row_type}>({const_name}, {args})"),
        JsOutput::JavaScript => format!("db.query({const_name}, {args})"),
    }
}

/// Build the `[p1, p2, ...]` params array for a pg query (unique params by index).
///
/// PostgreSQL uses `$N` reference-by-number, so each unique parameter index appears
/// exactly once in the bound array regardless of how many times it is referenced in
/// the SQL. Contrast with [`mysql_params_array`], which uses [`positional_bind_names`]
/// to repeat values for every anonymous `?` occurrence.
fn pg_params_array(query: &Query, type_map: &JsTypeMap) -> String {
    let mut params: Vec<&Parameter> = query.params.iter().collect();
    params.sort_by_key(|p| p.index);
    let exprs: Vec<String> = params.iter().map(|p| type_map.write_expr(p)).collect();
    format!("[{}]", exprs.join(", "))
}

fn emit_pg_list_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, ctx, &params)?;
    emit_fn_open(src, ctx, &params)?;
    match strategy {
        ListParamStrategy::Native => {
            let mut sorted_params: Vec<&Parameter> = ctx.query.params.iter().collect();
            sorted_params.sort_by_key(|p| p.index);
            let exprs: Vec<String> = sorted_params
                .iter()
                .map(|p| if p.is_list { ctx.adapter.list_arg(&p.sql_type, &to_camel_case(&p.name)) } else { ctx.type_map.write_expr(p) })
                .collect();
            let args = format!("[{}]", exprs.join(", "));
            emit_pg_body(src, ctx, &const_name, &args)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = before_raw.replace('"', "\\\"").replace('\n', " ");
            let after = after_raw.replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            let offset = scalar_params.iter().filter(|p| p.index < lp.index).count() + 1;
            writeln!(src, "  const placeholders = {lp_name}.map((_, i) => '$' + ({offset} + i)).join(', ');")?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| ctx.type_map.write_expr(p)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| ctx.type_map.write_expr(p)).collect();
            let list_spread = format!("...{}", ctx.adapter.list_arg(&lp.sql_type, &lp_name));
            let all_args = [before_args, vec![list_spread], after_args].concat().join(", ");
            emit_pg_body(src, ctx, "sql", &format!("[{all_args}]"))?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

// ─── SQLite (better-sqlite3) ─────────────────────────────────────────────────

pub(super) fn emit_sqlite_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = ctx.query.params.iter().find(|p| p.is_list) {
        return emit_sqlite_list_query(src, ctx, strategy, lp);
    }
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    emit_jsdoc(src, ctx, &params)?;
    emit_fn_open(src, ctx, &params)?;
    let args = sqlite_spread_args(ctx.query, ctx.type_map);
    emit_sqlite_body(src, ctx, &const_name, &args)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the spread argument list for a better-sqlite3 prepared statement call.
///
/// better-sqlite3 uses anonymous `?` placeholders; the arg list must follow the SQL
/// occurrence order including repeated params (e.g. a `@genre` used twice → two args).
fn sqlite_spread_args(query: &Query, type_map: &JsTypeMap) -> String {
    positional_bind_names(query)
        .iter()
        .map(|&n| {
            let param = query.params.iter().find(|p| p.name == n);
            param.map(|p| type_map.write_expr(p)).unwrap_or_else(|| to_camel_case(n))
        })
        .collect::<Vec<_>>()
        .join(", ")
}

/// Returns ` as Type` for TypeScript or empty string for JavaScript.
///
/// Used for better-sqlite3 `.get()`/`.all()` return types and mysql2 row casts,
/// both of which need an explicit `as T` only in TypeScript output.
fn ts_cast(ts_type: &str, output: JsOutput) -> String {
    match output {
        JsOutput::TypeScript => format!(" as {ts_type}"),
        JsOutput::JavaScript => String::new(),
    }
}

fn emit_sqlite_list_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, ctx, &params)?;
    emit_fn_open(src, ctx, &params)?;
    match strategy {
        ListParamStrategy::Native => {
            let stringify = ctx.type_map.list_json_stringify(&lp.sql_type, &lp_name);
            writeln!(src, "  const {lp_name}Json = {stringify};")?;
            let args = sqlite_list_spread_args(ctx.query, lp, &format!("{lp_name}Json"), ctx.type_map);
            emit_sqlite_body(src, ctx, &const_name, &args)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = rewrite_to_anon_params(&before_raw).replace('"', "\\\"").replace('\n', " ");
            let after = rewrite_to_anon_params(&after_raw).replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            writeln!(src, r#"  const placeholders = {lp_name}.map(() => "?").join(", ");"#)?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| ctx.type_map.write_expr(p)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| ctx.type_map.write_expr(p)).collect();
            let list_spread = format!("...{}", ctx.adapter.list_arg(&lp.sql_type, &lp_name));
            let all_args = [before_args, vec![list_spread], after_args].concat().join(", ");
            emit_sqlite_body(src, ctx, "sql", &all_args)?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the spread args string for a SQLite native-list query.
///
/// Follows SQL occurrence order (via [`positional_bind_names`]), substituting the list
/// param's JSON expression wherever that param's name would appear.
fn sqlite_list_spread_args(query: &Query, lp: &Parameter, lp_expr: &str, type_map: &JsTypeMap) -> String {
    let lp_camel = to_camel_case(&lp.name);
    positional_bind_names(query)
        .iter()
        .map(|&n| {
            let cn = to_camel_case(n);
            if cn == lp_camel {
                lp_expr.to_string()
            } else {
                let param = query.params.iter().find(|p| p.name == n);
                param.map(|p| type_map.write_expr(p)).unwrap_or(cn)
            }
        })
        .collect::<Vec<_>>()
        .join(", ")
}

fn emit_sqlite_body(src: &mut String, ctx: &QueryContext, sql_expr: &str, args: &str) -> anyhow::Result<()> {
    match ctx.query.cmd {
        QueryCmd::Exec => writeln!(src, "  db.prepare({sql_expr}).run({args});")?,
        QueryCmd::ExecRows => {
            writeln!(src, "  const result = db.prepare({sql_expr}).run({args});")?;
            writeln!(src, "  return result.changes;")?;
        },
        QueryCmd::One => {
            let row = ts_row_type(ctx.query, ctx.schema);
            let cast = ts_cast(&format!("{row} | undefined"), ctx.adapter.output());
            if let Some(transform) = ctx.type_map.row_transform_expr(ctx.query, "raw") {
                writeln!(src, "  const raw = db.prepare({sql_expr}).get({args}){cast};")?;
                writeln!(src, "  if (!raw) return null;")?;
                writeln!(src, "  return {transform};")?;
            } else {
                writeln!(src, "  const row = db.prepare({sql_expr}).get({args}){cast};")?;
                writeln!(src, "  return row ?? null;")?;
            }
        },
        QueryCmd::Many => {
            let row = ts_row_type(ctx.query, ctx.schema);
            let cast = ts_cast(&format!("{row}[]"), ctx.adapter.output());
            if let Some(transform) = ctx.type_map.row_transform_expr(ctx.query, "raw") {
                writeln!(src, "  return (db.prepare({sql_expr}).all({args}){cast}).map(raw => ({transform}));")?;
            } else {
                writeln!(src, "  return db.prepare({sql_expr}).all({args}){cast};")?;
            }
        },
    }
    Ok(())
}

// ─── MySQL (mysql2) ───────────────────────────────────────────────────────────

pub(super) fn emit_mysql_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = ctx.query.params.iter().find(|p| p.is_list) {
        return emit_mysql_list_query(src, ctx, strategy, lp);
    }
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    emit_jsdoc(src, ctx, &params)?;
    emit_fn_open(src, ctx, &params)?;
    let args = mysql_params_array(ctx.query, ctx.type_map);
    emit_mysql_body(src, ctx, &const_name, &args)?;
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the `[p1, p2, ...]` params array for mysql2 (positional `?`, params in SQL order).
fn mysql_params_array(query: &Query, type_map: &JsTypeMap) -> String {
    let exprs: Vec<String> = positional_bind_names(query)
        .iter()
        .map(|&n| {
            let param = query.params.iter().find(|p| p.name == n);
            param.map(|p| type_map.write_expr(p)).unwrap_or_else(|| to_camel_case(n))
        })
        .collect();
    format!("[{}]", exprs.join(", "))
}

fn emit_mysql_body(src: &mut String, ctx: &QueryContext, sql_expr: &str, args: &str) -> anyhow::Result<()> {
    // mysql2's execute() sends all JS `number` values as DOUBLE in the binary
    // protocol. MySQL rejects DOUBLE for LIMIT/OFFSET and other integer contexts.
    // Using query() sends parameters via the text protocol (client-side escaping),
    // which avoids the type mismatch and works correctly for all param types.
    match ctx.query.cmd {
        QueryCmd::Exec => writeln!(src, "  await db.query({sql_expr}, {args});")?,
        QueryCmd::ExecRows => {
            let rsh = mysql_type_param(ctx.adapter.output(), "ResultSetHeader");
            writeln!(src, "  const [result] = await db.query{rsh}({sql_expr}, {args});")?;
            writeln!(src, "  return result.affectedRows;")?;
        },
        QueryCmd::One => {
            let row = ts_row_type(ctx.query, ctx.schema);
            let rdp = mysql_type_param(ctx.adapter.output(), "RowDataPacket[]");
            let cast = ts_cast(&format!("{row} | undefined"), ctx.adapter.output());
            writeln!(src, "  const [rows] = await db.query{rdp}({sql_expr}, {args});")?;
            if let Some(transform) = ctx.type_map.row_transform_expr(ctx.query, "raw") {
                writeln!(src, "  const raw = rows[0]{cast};")?;
                writeln!(src, "  if (!raw) return null;")?;
                writeln!(src, "  return {transform};")?;
            } else {
                writeln!(src, "  return (rows[0]{cast}) ?? null;")?;
            }
        },
        QueryCmd::Many => {
            let row = ts_row_type(ctx.query, ctx.schema);
            let rdp = mysql_type_param(ctx.adapter.output(), "RowDataPacket[]");
            let cast = ts_cast(&format!("{row}[]"), ctx.adapter.output());
            writeln!(src, "  const [rows] = await db.query{rdp}({sql_expr}, {args});")?;
            if let Some(transform) = ctx.type_map.row_transform_expr(ctx.query, "raw") {
                writeln!(src, "  return (rows{cast}).map(raw => ({transform}));")?;
            } else {
                writeln!(src, "  return rows{cast};")?;
            }
        },
    }
    Ok(())
}

/// Emit `<T>` (TypeScript generic type argument) or empty string (JavaScript).
///
/// Used to make mysql2 `query` calls typed: `db.query<RowDataPacket[]>(...)`.
fn mysql_type_param(output: JsOutput, ts_type: &str) -> String {
    match output {
        JsOutput::TypeScript => format!("<{ts_type}>"),
        JsOutput::JavaScript => String::new(),
    }
}

fn emit_mysql_list_query(src: &mut String, ctx: &QueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let const_name = sql_const_name(&ctx.query.name);
    let params = ctx.params();
    let lp_name = to_camel_case(&lp.name);
    emit_jsdoc(src, ctx, &params)?;
    emit_fn_open(src, ctx, &params)?;
    match strategy {
        ListParamStrategy::Native => {
            let stringify = ctx.type_map.list_json_stringify(&lp.sql_type, &lp_name);
            writeln!(src, "  const {lp_name}Json = {stringify};")?;
            let args = mysql_list_params_array(ctx.query, lp, &format!("{lp_name}Json"), ctx.type_map);
            emit_mysql_body(src, ctx, &const_name, &args)?;
        },
        ListParamStrategy::Dynamic => {
            let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = rewrite_to_anon_params(&before_raw).replace('"', "\\\"").replace('\n', " ");
            let after = rewrite_to_anon_params(&after_raw).replace('"', "\\\"").replace('\n', " ");
            let before = before.trim_end().trim_end_matches(';');
            let after = after.trim_start();
            writeln!(src, r#"  const placeholders = {lp_name}.map(() => "?").join(", ");"#)?;
            writeln!(src, r#"  const sql = `{before}IN (${{placeholders}}){after}`;"#)?;
            let before_args: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| ctx.type_map.write_expr(p)).collect();
            let after_args: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| ctx.type_map.write_expr(p)).collect();
            let list_spread = format!("...{}", ctx.adapter.list_arg(&lp.sql_type, &lp_name));
            let all_args = [before_args, vec![list_spread], after_args].concat().join(", ");
            emit_mysql_body(src, ctx, "sql", &format!("[{all_args}]"))?;
        },
    }
    writeln!(src, "}}")?;
    Ok(())
}

/// Build the `[p1, p2, ...]` array for a MySQL native list query,
/// substituting the JSON-stringified expression for the list param slot.
fn mysql_list_params_array(query: &Query, lp: &Parameter, lp_expr: &str, type_map: &JsTypeMap) -> String {
    let mut params: Vec<&Parameter> = query.params.iter().collect();
    params.sort_by_key(|p| p.index);
    let exprs: Vec<String> = params.iter().map(|p| if p.index == lp.index { lp_expr.to_string() } else { type_map.write_expr(p) }).collect();
    format!("[{}]", exprs.join(", "))
}
