use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::GeneratedFile;
use crate::config::OutputConfig;

use super::RustTarget;

/// SQL placeholder normalization mode for sqlx drivers.
#[derive(Clone, Copy)]
pub(super) enum RustSqlNormMode {
    /// Preserve indexed placeholders (`$N`).
    Preserve,
    /// Rewrite positional placeholders to anonymous `?`.
    AnonParams,
}

/// Bind ordering mode for scalar query params.
#[derive(Clone, Copy)]
pub(super) enum RustBindMode {
    /// Bind once per unique parameter index.
    UniqueParams,
    /// Bind once per SQL placeholder occurrence.
    Positional,
}

/// Placeholder style for runtime-expanded list params.
#[derive(Clone, Copy)]
pub(super) enum RustPlaceholderMode {
    /// Generate `$N` placeholders.
    NumberedDollar,
    /// Generate anonymous `?` placeholders.
    QuestionMark,
}

/// Compile-time adapter contract consumed by the Rust core emitter.
pub(super) struct RustCoreContract {
    /// Generated helper module source (`_sqltgen.rs`).
    pub(super) helper_source: String,
    /// SQL normalization mode for this target.
    pub(super) sql_norm_mode: RustSqlNormMode,
    /// Scalar bind ordering mode for this target.
    pub(super) bind_mode: RustBindMode,
    /// Dynamic list placeholder style for this target.
    pub(super) placeholder_mode: RustPlaceholderMode,
}

/// Resolve the Rust adapter contract for the selected engine target.
pub(super) fn resolve_rust_contract(target: &RustTarget) -> RustCoreContract {
    match target {
        RustTarget::Postgres => RustCoreContract {
            helper_source: build_helper_file("PgPool"),
            sql_norm_mode: RustSqlNormMode::Preserve,
            bind_mode: RustBindMode::UniqueParams,
            placeholder_mode: RustPlaceholderMode::NumberedDollar,
        },
        RustTarget::Sqlite => RustCoreContract {
            helper_source: build_helper_file("SqlitePool"),
            sql_norm_mode: RustSqlNormMode::AnonParams,
            bind_mode: RustBindMode::Positional,
            placeholder_mode: RustPlaceholderMode::QuestionMark,
        },
        RustTarget::Mysql => RustCoreContract {
            helper_source: build_helper_file("MySqlPool"),
            sql_norm_mode: RustSqlNormMode::AnonParams,
            bind_mode: RustBindMode::Positional,
            placeholder_mode: RustPlaceholderMode::QuestionMark,
        },
    }
}

/// Emit the engine-specific helper module selected by the contract.
pub(super) fn emit_helper_file(contract: &RustCoreContract, config: &OutputConfig) -> GeneratedFile {
    GeneratedFile { path: PathBuf::from(&config.out).join("_sqltgen.rs"), content: contract.helper_source.clone() }
}

fn build_helper_file(pool_type: &str) -> String {
    let mut src = String::new();
    let _ = writeln!(src, "// Generated by sqltgen. Do not edit.");
    let _ = writeln!(src, "pub type DbPool = sqlx::{pool_type};");
    src
}
