"""Generated e2e runtime test — python/postgresql. DO NOT EDIT.

Auto-generated by scripts/e2e_testgen from test_spec.yaml.
"""

import datetime
import json
import os
import pathlib
import uuid

import psycopg
import pytest

from gen.queries import queries
from gen.models import *

_FIXTURES = pathlib.Path(__file__).parent / "../../../../fixtures/enums/postgresql"
_DB_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://sqltgen:sqltgen@localhost:15432/sqltgen_e2e",
)


@pytest.fixture()
def conn():
    """Yield a psycopg connection with an isolated schema; drop it on teardown."""
    schema = "test_" + uuid.uuid4().hex
    schema_sql = (_FIXTURES / "schema.sql").read_text()

    with psycopg.connect(_DB_URL, autocommit=True) as c:
        c.execute(f'CREATE SCHEMA "{schema}"')
        c.execute(f'SET search_path TO "{schema}"')
        c.execute(schema_sql)
        yield c
        c.execute(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE')


def test_create_and_get_task(conn):
    task = queries.create_task(conn, 'Fix bug', Priority('high'), Status('open'), 'Fix the login bug')
    assert task is not None
    assert task.title == 'Fix bug'
    assert task.priority == Priority('high')
    assert task.status == Status('open')
    assert task.description == 'Fix the login bug'


def test_get_task_not_found(conn):
    result = queries.get_task(conn, 999)
    assert result is None


def test_update_task_status(conn):
    task = queries.create_task(conn, 'Deploy', Priority('critical'), Status('open'), None)
    updated = queries.update_task_status(conn, Status('in_progress'), 1)
    assert updated is not None
    assert updated.status == Status('in_progress')
    assert updated.priority == Priority('critical')


def test_list_by_priority(conn):
    queries.create_task(conn, 'Low task', Priority('low'), Status('open'), None)
    queries.create_task(conn, 'High task 1', Priority('high'), Status('open'), None)
    queries.create_task(conn, 'High task 2', Priority('high'), Status('done'), None)
    tasks = queries.list_tasks_by_priority(conn, Priority('high'))
    assert len(tasks) == 2
    assert tasks[0].title == 'High task 1'
    assert tasks[1].title == 'High task 2'


def test_list_by_status(conn):
    queries.create_task(conn, 'Open 1', Priority('low'), Status('open'), None)
    queries.create_task(conn, 'Done 1', Priority('medium'), Status('done'), None)
    queries.create_task(conn, 'Open 2', Priority('high'), Status('open'), None)
    tasks = queries.list_tasks_by_status(conn, Status('open'))
    assert len(tasks) == 2


def test_list_by_priority_or_all(conn):
    queries.create_task(conn, 'Low', Priority('low'), Status('open'), None)
    queries.create_task(conn, 'High', Priority('high'), Status('open'), None)
    all_tasks = queries.list_tasks_by_priority_or_all(conn, None)
    assert len(all_tasks) == 2
    high_tasks = queries.list_tasks_by_priority_or_all(conn, Priority('high'))
    assert len(high_tasks) == 1
    assert high_tasks[0].title == 'High'


def test_count_by_status(conn):
    queries.create_task(conn, 'A', Priority('low'), Status('open'), None)
    queries.create_task(conn, 'B', Priority('low'), Status('open'), None)
    queries.create_task(conn, 'C', Priority('high'), Status('done'), None)
    counts = queries.count_by_status(conn)
    assert len(counts) == 2


def test_delete_task(conn):
    queries.create_task(conn, 'Temp', Priority('low'), Status('open'), None)
    queries.delete_task(conn, 1)
    result = queries.get_task(conn, 1)
    assert result is None


