use std::path::PathBuf;

use crate::backend::GeneratedFile;
use crate::config::OutputConfig;

use super::GoTarget;

/// How SQL placeholders are formatted for this engine.
#[derive(Clone, Copy, PartialEq)]
pub(super) enum GoPlaceholderMode {
    /// PostgreSQL-style `$N` numbered placeholders.
    NumberedDollar,
    /// Anonymous `?` placeholders (SQLite, MySQL).
    QuestionMark,
}

/// How scalar query parameters are bound for this engine.
#[derive(Clone, Copy)]
pub(super) enum GoBindMode {
    /// Bind once per unique parameter index (PostgreSQL `$N` resolves by number).
    UniqueParams,
    /// Bind once per SQL placeholder occurrence (SQLite, MySQL positional).
    Positional,
}

/// How JSON columns are represented in Go.
#[derive(Clone, Copy)]
pub(super) enum GoJsonMode {
    /// `[]byte` — PostgreSQL returns raw JSON bytes.
    Bytes,
    /// `string` — SQLite and MySQL return JSON as a text string.
    String,
}

/// Compile-time adapter contract consumed by the Go core emitter.
///
/// Captures all engine/driver differences so core.rs can emit clean,
/// branch-free code.
pub(super) struct GoCoreContract {
    /// One-line comment naming the recommended driver, emitted in `_sqltgen.go`.
    pub(super) driver_comment: &'static str,
    /// Placeholder format used when rewriting SQL.
    pub(super) placeholder_mode: GoPlaceholderMode,
    /// Whether to bind params by unique index or by SQL occurrence order.
    pub(super) bind_mode: GoBindMode,
    /// JSON column representation.
    pub(super) json_mode: GoJsonMode,
}

/// Resolve the Go adapter contract for the selected engine target.
pub(super) fn resolve_go_contract(target: &GoTarget) -> GoCoreContract {
    match target {
        GoTarget::Postgres => GoCoreContract {
            driver_comment: "// Driver: github.com/jackc/pgx/v5/stdlib (database/sql)",
            placeholder_mode: GoPlaceholderMode::NumberedDollar,
            bind_mode: GoBindMode::UniqueParams,
            json_mode: GoJsonMode::Bytes,
        },
        GoTarget::Sqlite => GoCoreContract {
            driver_comment: "// Driver: modernc.org/sqlite",
            placeholder_mode: GoPlaceholderMode::QuestionMark,
            bind_mode: GoBindMode::Positional,
            json_mode: GoJsonMode::String,
        },
        GoTarget::Mysql => GoCoreContract {
            driver_comment: "// Driver: github.com/go-sql-driver/mysql",
            placeholder_mode: GoPlaceholderMode::QuestionMark,
            bind_mode: GoBindMode::Positional,
            json_mode: GoJsonMode::String,
        },
    }
}

/// Emit the static `_sqltgen.go` helper file.
pub(super) fn emit_helper_file(contract: &GoCoreContract, package_name: &str, config: &OutputConfig) -> GeneratedFile {
    let content = build_helper_content(contract, package_name);
    GeneratedFile { path: PathBuf::from(&config.out).join("sqltgen.go"), content }
}

fn build_helper_content(contract: &GoCoreContract, package_name: &str) -> String {
    let dollar = contract.placeholder_mode == GoPlaceholderMode::NumberedDollar;
    let use_pq = matches!(contract.placeholder_mode, GoPlaceholderMode::NumberedDollar);
    let mut src = String::new();
    src.push_str("// Code generated by sqltgen. Do not edit.\n");
    src.push_str(contract.driver_comment);
    src.push('\n');
    src.push('\n');
    src.push_str("package ");
    src.push_str(package_name);
    src.push('\n');
    src.push('\n');
    src.push_str("import (\n");
    src.push_str("\t\"context\"\n");
    src.push_str("\t\"database/sql\"\n");
    src.push_str("\t\"fmt\"\n");
    src.push_str("\t\"strings\"\n");
    if use_pq {
        src.push_str("\t\"github.com/lib/pq\"\n");
    }
    src.push_str(")\n");
    src.push('\n');
    src.push_str("// execRows runs a statement and returns the number of affected rows.\n");
    src.push_str("func execRows(ctx context.Context, db *sql.DB, query string, args ...any) (int64, error) {\n");
    src.push_str("\tresult, err := db.ExecContext(ctx, query, args...)\n");
    src.push_str("\tif err != nil {\n");
    src.push_str("\t\treturn 0, err\n");
    src.push_str("\t}\n");
    src.push_str("\treturn result.RowsAffected()\n");
    src.push_str("}\n");
    src.push('\n');
    src.push_str("// buildInClause constructs an IN clause with n positional placeholders.\n");
    src.push_str("// It returns the assembled SQL and a flat args slice.\n");
    src.push_str("func buildInClause(prefix, suffix string, startIdx int, count int) string {\n");
    src.push_str("\tplaceholders := make([]string, count)\n");
    src.push_str("\tfor i := range count {\n");
    if dollar {
        src.push_str("\t\tplaceholders[i] = fmt.Sprintf(\"$%d\", startIdx+i)\n");
    } else {
        src.push_str("\t\tplaceholders[i] = \"?\"\n");
        src.push_str("\t\t_ = fmt.Sprintf // suppress unused import\n");
    }
    src.push_str("\t}\n");
    src.push_str("\treturn prefix + \"IN (\" + strings.Join(placeholders, \", \") + \")\" + suffix\n");
    src.push_str("}\n");
    src.push('\n');
    src.push_str("// scanArray returns a scan destination for SQL ARRAY columns.\n");
    if use_pq {
        src.push_str("func scanArray(dest any) any {\n");
        src.push_str("\treturn pq.Array(dest)\n");
        src.push_str("}\n");
    } else {
        src.push_str("func scanArray(dest any) any {\n");
        src.push_str("\treturn dest\n");
        src.push_str("}\n");
    }
    src
}
