// Generated e2e runtime test — kotlin/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.example.db.models.*
import com.example.db.queries.Queries
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.UUID

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private val GEN_MAPPER = ObjectMapper()
    private val url = System.getenv()
        .getOrDefault("DATABASE_URL", "jdbc:postgresql://localhost:15432/sqltgen_e2e")

    private lateinit var conn: Connection
    private lateinit var dbName: String

    @BeforeEach
    fun setUp() {
        dbName = "test_" + UUID.randomUUID().toString().replace("-", "")
        DriverManager.getConnection(url, "sqltgen", "sqltgen").use { admin ->
            admin.createStatement().use { s ->
                s.execute("""CREATE DATABASE "$dbName"""")
            }
        }
        val baseUrl = url.replaceFirst(Regex("/[^/]*$"), "/$dbName")
        conn = DriverManager.getConnection(baseUrl, "sqltgen", "sqltgen")
        conn.autoCommit = true
        val ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/type_overrides/postgresql/schema.sql"))
        conn.createStatement().use { s ->
            for (stmt in ddl.split(";")) {
                val t = stmt.trim()
                if (t.isNotEmpty()) s.execute(t)
            }
        }
    }

    @AfterEach
    fun tearDown() {
        conn.close()
        DriverManager.getConnection(url, "sqltgen", "sqltgen").use { admin ->
            admin.createStatement().use { s ->
                s.execute("""DROP DATABASE IF EXISTS "$dbName"""")
            }
        }
    }

    private fun genJson(raw: String): JsonNode = GEN_MAPPER.readTree(raw)

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    fun testUpdatePayloadGen() {
        Queries.insertEvent(conn, "test", "{\"v\": 1}", "{\"source\": \"web\"}", UUID.fromString("550e8400-e29b-41d4-a716-446655440007"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        Queries.updatePayload(conn, "{\"v\": 2, \"changed\": true}", null, 1L)
        val ev = Queries.getEvent(conn, 1L)!!
        assertNotNull(ev)
        assertEquals(genJson("{\"v\": 2, \"changed\": true}"), genJson(ev.payload))
        assertNull(ev.meta)
    }

    @Test
    fun testUpdateEventDateGen() {
        Queries.insertEvent(conn, "dated", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440008"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, LocalDate.of(2024, 1, 1), null)
        Queries.updateEventDate(conn, LocalDate.of(2024, 12, 31), 1L)
        val ev = Queries.getEvent(conn, 1L)!!
        assertNotNull(ev)
        assertEquals(LocalDate.of(2024, 12, 31), ev.eventDate)
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    fun testInsertEventRowsGen() {
        val n = Queries.insertEventRows(conn, "rowtest", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440009"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        assertEquals(1, n)
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    fun testListEventsGen() {
        Queries.insertEvent(conn, "alpha", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440001"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        Queries.insertEvent(conn, "beta", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440002"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        Queries.insertEvent(conn, "gamma", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440003"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        val events = Queries.listEvents(conn)
        assertEquals(3, events.size)
        assertEquals("alpha", events[0].name)
        assertEquals("beta", events[1].name)
        assertEquals("gamma", events[2].name)
    }

    @Test
    fun testGetEventsByDateRangeGen() {
        Queries.insertEvent(conn, "early", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440004"), LocalDateTime.of(2024, 1, 1, 10, 0, 0), null, null, null)
        Queries.insertEvent(conn, "mid", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440005"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        Queries.insertEvent(conn, "late", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-446655440006"), LocalDateTime.of(2024, 12, 1, 15, 0, 0), null, null, null)
        val events = Queries.getEventsByDateRange(conn, LocalDateTime.of(2024, 1, 1, 0, 0, 0), LocalDateTime.of(2024, 7, 1, 0, 0, 0))
        assertEquals(2, events.size)
        assertEquals("early", events[0].name)
        assertEquals("mid", events[1].name)
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    fun testInsertAndGetEventGen() {
        Queries.insertEvent(conn, "login", "{\"type\": \"click\", \"x\": 10}", "{\"source\": \"web\"}", UUID.fromString("550e8400-e29b-41d4-a716-446655440000"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), OffsetDateTime.of(2024, 6, 1, 14, 0, 0, 0, ZoneOffset.UTC), LocalDate.of(2024, 6, 1), null)
        val ev = Queries.getEvent(conn, 1L)!!
        assertNotNull(ev)
        assertEquals("login", ev.name)
        assertEquals(genJson("{\"type\": \"click\", \"x\": 10}"), genJson(ev.payload))
        assertEquals(genJson("{\"source\": \"web\"}"), genJson(ev.meta!!))
        assertEquals(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"), ev.docId)
        assertEquals(LocalDateTime.of(2024, 6, 1, 12, 0, 0), ev.createdAt)
        assertEquals(OffsetDateTime.of(2024, 6, 1, 14, 0, 0, 0, ZoneOffset.UTC), ev.scheduledAt)
        assertEquals(LocalDate.of(2024, 6, 1), ev.eventDate)
        assertNull(ev.eventTime)
    }

    @Test
    fun testGetEventNotFoundGen() {
        val result = Queries.getEvent(conn, 999L)
        assertNull(result)
    }

    // ─── count queries ────────────────────────────────────────────────────────────

    @Test
    fun testCountEventsGen() {
        Queries.insertEvent(conn, "ev1", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-44665544000c"), LocalDateTime.of(2024, 6, 1, 0, 0, 0), null, null, null)
        Queries.insertEvent(conn, "ev2", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-44665544000d"), LocalDateTime.of(2024, 6, 2, 0, 0, 0), null, null, null)
        Queries.insertEvent(conn, "ev3", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-44665544000e"), LocalDateTime.of(2024, 6, 3, 0, 0, 0), null, null, null)
        val row = Queries.countEvents(conn, LocalDateTime.of(2024, 1, 1, 0, 0, 0))!!
        assertNotNull(row)
        assertEquals(3L, row.total)
    }

    // ─── projection queries ────────────────────────────────────────────────────────────

    @Test
    fun testFindByDateGen() {
        Queries.insertEvent(conn, "dated", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-44665544000a"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, LocalDate.of(2024, 6, 15), null)
        val row = Queries.findByDate(conn, LocalDate.of(2024, 6, 15))!!
        assertNotNull(row)
        assertEquals("dated", row.name)
    }

    @Test
    fun testFindByUuidGen() {
        Queries.insertEvent(conn, "uuid-test", "{}", null, UUID.fromString("550e8400-e29b-41d4-a716-44665544000b"), LocalDateTime.of(2024, 6, 1, 12, 0, 0), null, null, null)
        val row = Queries.findByUuid(conn, UUID.fromString("550e8400-e29b-41d4-a716-44665544000b"))!!
        assertNotNull(row)
        assertEquals("uuid-test", row.name)
    }

}
