// Generated e2e runtime test — kotlin/postgresql. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.example.db.models.*
import com.example.db.queries.Queries
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.UUID

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private val GEN_MAPPER = ObjectMapper()
    private val url = System.getenv()
        .getOrDefault("DATABASE_URL", "jdbc:postgresql://localhost:15432/sqltgen_e2e")

    private lateinit var conn: Connection
    private lateinit var dbName: String

    @BeforeEach
    fun setUp() {
        dbName = "test_" + UUID.randomUUID().toString().replace("-", "")
        DriverManager.getConnection(url, "sqltgen", "sqltgen").use { admin ->
            admin.createStatement().use { s ->
                s.execute("""CREATE DATABASE "$dbName"""")
            }
        }
        val baseUrl = url.replaceFirst(Regex("/[^/]*$"), "/$dbName")
        conn = DriverManager.getConnection(baseUrl, "sqltgen", "sqltgen")
        conn.autoCommit = true
        val ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/enums/postgresql/schema.sql"))
        conn.createStatement().use { s ->
            for (stmt in ddl.split(";")) {
                val t = stmt.trim()
                if (t.isNotEmpty()) s.execute(t)
            }
        }
    }

    @AfterEach
    fun tearDown() {
        conn.close()
        DriverManager.getConnection(url, "sqltgen", "sqltgen").use { admin ->
            admin.createStatement().use { s ->
                s.execute("""DROP DATABASE IF EXISTS "$dbName"""")
            }
        }
    }

    private fun genJson(raw: String): JsonNode = GEN_MAPPER.readTree(raw)

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    fun testDeleteTaskGen() {
        Queries.createTask(conn, "Temp", Priority.fromValue("low"), Status.fromValue("open"), null)
        Queries.deleteTask(conn, 1L)
        val result = Queries.getTask(conn, 1L)
        assertNull(result)
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    fun testListByPriorityGen() {
        Queries.createTask(conn, "Low task", Priority.fromValue("low"), Status.fromValue("open"), null)
        Queries.createTask(conn, "High task 1", Priority.fromValue("high"), Status.fromValue("open"), null)
        Queries.createTask(conn, "High task 2", Priority.fromValue("high"), Status.fromValue("done"), null)
        val tasks = Queries.listTasksByPriority(conn, Priority.fromValue("high"))
        assertEquals(2, tasks.size)
        assertEquals("High task 1", tasks[0].title)
        assertEquals("High task 2", tasks[1].title)
    }

    @Test
    fun testListByStatusGen() {
        Queries.createTask(conn, "Open 1", Priority.fromValue("low"), Status.fromValue("open"), null)
        Queries.createTask(conn, "Done 1", Priority.fromValue("medium"), Status.fromValue("done"), null)
        Queries.createTask(conn, "Open 2", Priority.fromValue("high"), Status.fromValue("open"), null)
        val tasks = Queries.listTasksByStatus(conn, Status.fromValue("open"))
        assertEquals(2, tasks.size)
    }

    @Test
    fun testListByPriorityOrAllGen() {
        Queries.createTask(conn, "Low", Priority.fromValue("low"), Status.fromValue("open"), null)
        Queries.createTask(conn, "High", Priority.fromValue("high"), Status.fromValue("open"), null)
        val all_tasks = Queries.listTasksByPriorityOrAll(conn, null)
        assertEquals(2, all_tasks.size)
        val high_tasks = Queries.listTasksByPriorityOrAll(conn, Priority.fromValue("high"))
        assertEquals(1, high_tasks.size)
        assertEquals("High", high_tasks[0].title)
    }

    @Test
    fun testCountByStatusGen() {
        Queries.createTask(conn, "A", Priority.fromValue("low"), Status.fromValue("open"), null)
        Queries.createTask(conn, "B", Priority.fromValue("low"), Status.fromValue("open"), null)
        Queries.createTask(conn, "C", Priority.fromValue("high"), Status.fromValue("done"), null)
        val counts = Queries.countByStatus(conn)
        assertEquals(2, counts.size)
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    fun testCreateAndGetTaskGen() {
        val task = Queries.createTask(conn, "Fix bug", Priority.fromValue("high"), Status.fromValue("open"), "Fix the login bug")!!
        assertNotNull(task)
        assertEquals("Fix bug", task.title)
        assertEquals(Priority.fromValue("high"), task.priority)
        assertEquals(Status.fromValue("open"), task.status)
        assertEquals("Fix the login bug", task.description)
    }

    @Test
    fun testGetTaskNotFoundGen() {
        val result = Queries.getTask(conn, 999L)
        assertNull(result)
    }

    @Test
    fun testUpdateTaskStatusGen() {
        val task = Queries.createTask(conn, "Deploy", Priority.fromValue("critical"), Status.fromValue("open"), null)!!
        val updated = Queries.updateTaskStatus(conn, Status.fromValue("in_progress"), 1L)!!
        assertNotNull(updated)
        assertEquals(Status.fromValue("in_progress"), updated.status)
        assertEquals(Priority.fromValue("critical"), updated.priority)
    }

    // ─── enum array queries ────────────────────────────────────────────────────────────

    @Test
    fun testCreateWithEnumArrayGen() {
        val task = Queries.createTaskWithTags(conn, "Tagged task", Priority.fromValue("high"), Status.fromValue("open"), null, listOf(Priority.fromValue("high"), Priority.fromValue("critical")))!!
        assertNotNull(task)
        assertEquals("Tagged task", task.title)
        assertEquals(2, task.tags.size)
        assertEquals(Priority.fromValue("high"), task.tags[0])
        assertEquals(Priority.fromValue("critical"), task.tags[1])
    }

    @Test
    fun testGetTaskTagsGen() {
        Queries.createTaskWithTags(conn, "Read tags", Priority.fromValue("low"), Status.fromValue("open"), null, listOf(Priority.fromValue("low"), Priority.fromValue("medium"), Priority.fromValue("high")))
        val row = Queries.getTaskTags(conn, 1L)!!
        assertNotNull(row)
        assertEquals(3, row.tags.size)
        assertEquals(Priority.fromValue("low"), row.tags[0])
        assertEquals(Priority.fromValue("medium"), row.tags[1])
        assertEquals(Priority.fromValue("high"), row.tags[2])
    }

    @Test
    fun testUpdateTaskTagsGen() {
        Queries.createTaskWithTags(conn, "Update tags", Priority.fromValue("medium"), Status.fromValue("open"), null, listOf(Priority.fromValue("low")))
        val updated = Queries.updateTaskTags(conn, listOf(Priority.fromValue("high"), Priority.fromValue("critical")), 1L)!!
        assertNotNull(updated)
        assertEquals(2, updated.tags.size)
        assertEquals(Priority.fromValue("high"), updated.tags[0])
        assertEquals(Priority.fromValue("critical"), updated.tags[1])
    }

    @Test
    fun testEmptyEnumArrayGen() {
        Queries.createTaskWithTags(conn, "No tags", Priority.fromValue("low"), Status.fromValue("open"), null, emptyList<Priority>())
        val row = Queries.getTaskTags(conn, 1L)!!
        assertNotNull(row)
        assertEquals(0, row.tags.size)
    }

}
