// Generated e2e runtime test — kotlin/sqlite. DO NOT EDIT.
//
// Auto-generated by scripts/e2e_testgen from test_spec.yaml.
package com.example.db

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.example.db.models.*
import com.example.db.queries.Queries
import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import java.sql.Connection
import java.sql.DriverManager
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.ZoneOffset
import java.util.UUID

// ─── test setup ───────────────────────────────────────────────────────────────

class RuntimeGenTest {

    private val GEN_MAPPER = ObjectMapper()
    private lateinit var conn: Connection

    @BeforeEach
    fun setUp() {
        conn = DriverManager.getConnection("jdbc:sqlite::memory:")
        conn.autoCommit = true
        val ddl = java.nio.file.Files.readString(
            java.nio.file.Path.of("../../../../fixtures/bookstore/sqlite/schema.sql"))
        conn.createStatement().use { s ->
            for (stmt in ddl.split(";")) {
                val t = stmt.trim()
                if (t.isNotEmpty()) s.execute(t)
            }
        }
    }

    @AfterEach
    fun tearDown() {
        conn.close()
    }

    private fun genJson(raw: String): JsonNode = GEN_MAPPER.readTree(raw)

// ─── scenarios ────────────────────────────────────────────────────────────────

    // ─── :exec queries ────────────────────────────────────────────────────────────

    @Test
    fun testAddSaleItemGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createCustomer(conn, "Customer", "c@example.com")
        Queries.createBook(conn, 1, "Book", "sci-fi", 10.0, null)
        Queries.createSale(conn, 1)
        Queries.addSaleItem(conn, 1, 1, 3, 10.0)
    }

    // ─── :execrows queries ────────────────────────────────────────────────────────────

    @Test
    fun testDeleteBookByIdGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1, "Book1", "sci-fi", 10.0, null)
        val affected = Queries.deleteBookById(conn, 1)
        assertEquals(1, affected)
    }

    // ─── :many queries ────────────────────────────────────────────────────────────

    @Test
    fun testListAuthorsGen() {
        Queries.createAuthor(conn, "Asimov", null, 1920)
        Queries.createAuthor(conn, "Herbert", null, 1920)
        val authors = Queries.listAuthors(conn)
        assertEquals(2, authors.size)
        assertEquals("Asimov", authors[0].name)
        assertEquals("Herbert", authors[1].name)
    }

    @Test
    fun testListBooksByGenreGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1, "SciFi1", "sci-fi", 9.99, null)
        Queries.createBook(conn, 1, "Fantasy1", "fantasy", 11.99, null)
        val books = Queries.listBooksByGenre(conn, "sci-fi")
        assertEquals(1, books.size)
        assertEquals("SciFi1", books[0].title)
    }

    @Test
    fun testListBooksByGenreOrAllGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1, "B1", "sci-fi", 9.99, null)
        Queries.createBook(conn, 1, "B2", "fantasy", 9.99, null)
        val all_books = Queries.listBooksByGenreOrAll(conn, null)
        assertEquals(2, all_books.size)
        val scifi = Queries.listBooksByGenreOrAll(conn, "sci-fi")
        assertEquals(1, scifi.size)
    }

    @Test
    fun testListBooksWithAuthorJoinGen() {
        Queries.createAuthor(conn, "Author A", "Bio A", 1920)
        Queries.createBook(conn, 1, "Book A", "sci-fi", 9.99, null)
        val rows = Queries.listBooksWithAuthor(conn)
        assertEquals(1, rows.size)
        assertEquals("Author A", rows[0].authorName)
    }

    // ─── :one queries ────────────────────────────────────────────────────────────

    @Test
    fun testGetAuthorGen() {
        Queries.createAuthor(conn, "Asimov", "Sci-fi master", 1920)
        val author = Queries.getAuthor(conn, 1)!!
        assertNotNull(author)
        assertEquals("Asimov", author.name)
        assertEquals("Sci-fi master", author.bio)
        assertEquals(1920, author.birthYear)
    }

    @Test
    fun testGetAuthorNotFoundGen() {
        val result = Queries.getAuthor(conn, 999)
        assertNull(result)
    }

    @Test
    fun testGetBookGen() {
        Queries.createAuthor(conn, "Herbert", null, 1920)
        Queries.createBook(conn, 1, "Dune", "sci-fi", 12.99, "1965-06-01")
        val book = Queries.getBook(conn, 1)!!
        assertNotNull(book)
        assertEquals("Dune", book.title)
        assertEquals("sci-fi", book.genre)
    }

    // ─── aggregates ────────────────────────────────────────────────────────────

    @Test
    fun testCountBooksByGenreGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1, "B1", "sci-fi", 10.0, null)
        Queries.createBook(conn, 1, "B2", "sci-fi", 10.0, null)
        Queries.createBook(conn, 1, "B3", "fantasy", 10.0, null)
        val counts = Queries.countBooksByGenre(conn)
        assertEquals(2, counts.size)
    }

    // ─── filtering ────────────────────────────────────────────────────────────

    @Test
    fun testGetBooksByPriceRangeGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1, "Cheap", "sci-fi", 5.99, null)
        Queries.createBook(conn, 1, "Mid", "sci-fi", 10.5, null)
        Queries.createBook(conn, 1, "Expensive", "sci-fi", 20.99, null)
        val books = Queries.getBooksByPriceRange(conn, 7.0, 15.0)
        assertEquals(1, books.size)
        assertEquals("Mid", books[0].title)
    }

    @Test
    fun testSearchBooksByTitleGen() {
        Queries.createAuthor(conn, "A", null, 1900)
        Queries.createBook(conn, 1, "Foundation", "sci-fi", 9.99, null)
        Queries.createBook(conn, 1, "Dune", "sci-fi", 12.99, null)
        val books = Queries.searchBooksByTitle(conn, "%ound%")
        assertEquals(1, books.size)
        assertEquals("Foundation", books[0].title)
    }

    // ─── NULL handling ────────────────────────────────────────────────────────────

    @Test
    fun testAuthorsWithNullBioGen() {
        Queries.createAuthor(conn, "WithBio", "Has bio", 1900)
        Queries.createAuthor(conn, "NoBio", null, 1900)
        val authors = Queries.getAuthorsWithNullBio(conn)
        assertEquals(1, authors.size)
        assertEquals("NoBio", authors[0].name)
    }

    @Test
    fun testAuthorsWithBioGen() {
        Queries.createAuthor(conn, "WithBio", "Bio", 1900)
        Queries.createAuthor(conn, "NoBio", null, 1900)
        val authors = Queries.getAuthorsWithBio(conn)
        assertEquals(1, authors.size)
        assertEquals("WithBio", authors[0].name)
    }

}
