use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::common::{
    group_queries, has_inline_rows, infer_row_type_name, infer_table, querier_class_name, queries_file_stem, row_type_name, sql_const_name,
};
use crate::backend::naming::{to_pascal_case, to_snake_case};
use crate::backend::sql_rewrite::{positional_bind_names, rewrite_to_anon_params, rewrite_to_percent_s, split_at_in_clause};
use crate::backend::GeneratedFile;
use crate::config::{resolve_type_override, Language, ListParamStrategy, OutputConfig, ResolvedType, TypeVariant};
use crate::ir::{NativeListBind, Parameter, Query, QueryCmd, Schema, SqlType};

use super::adapter::{FieldReadConverter, PythonCoreContract, PythonJsonMode, PythonSqlNormMode};

#[cfg(test)]
use super::PythonTarget;

/// Resolve any configured type override for the given SQL type and variant.
///
/// Python has no preset names — only explicit and FQN string forms.
fn get_type_override_python(sql_type: &SqlType, variant: TypeVariant, config: &OutputConfig) -> Option<ResolvedType> {
    resolve_type_override(sql_type, variant, config, Language::Python, |_| None)
}

/// Map a SQL column type to its Python type string, applying any configured field override.
fn python_field_type(sql_type: &SqlType, nullable: bool, contract: &PythonCoreContract, config: &OutputConfig) -> String {
    if let Some(resolved) = get_type_override_python(sql_type, TypeVariant::Field, config) {
        return if nullable { format!("{} | None", resolved.name) } else { resolved.name };
    }
    python_type_with_json_mode(sql_type, nullable, contract.sql.json_mode)
}

/// Map a SQL parameter type to its Python type string, applying any configured param override.
fn python_param_type_resolved(sql_type: &SqlType, nullable: bool, contract: &PythonCoreContract, config: &OutputConfig) -> String {
    if let Some(resolved) = get_type_override_python(sql_type, TypeVariant::Param, config) {
        return if nullable { format!("{} | None", resolved.name) } else { resolved.name };
    }
    python_type_with_json_mode(sql_type, nullable, contract.sql.json_mode)
}

/// Per-query context forwarded to all emitters within a queries file.
struct PythonQueryContext<'a> {
    query: &'a Query,
    schema: &'a Schema,
    contract: &'a PythonCoreContract,
    config: &'a OutputConfig,
}

/// Emit all Python files except the helper module.
pub(super) fn generate_core_files(
    schema: &Schema,
    queries: &[Query],
    contract: &PythonCoreContract,
    config: &OutputConfig,
) -> anyhow::Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();

    for table in &schema.tables {
        let class_name = to_pascal_case(&table.name);
        let mut src = String::new();
        writeln!(src, "# Generated by sqltgen. Do not edit.")?;
        writeln!(src, "from __future__ import annotations")?;
        writeln!(src)?;
        writeln!(src, "import dataclasses")?;

        let mut imports = TypeImports::default();
        for col in &table.columns {
            imports.scan_field(&col.sql_type, config);
        }
        imports.write(&mut src)?;

        writeln!(src)?;
        writeln!(src)?;
        writeln!(src, "@dataclasses.dataclass")?;
        writeln!(src, "class {class_name}:")?;
        for col in &table.columns {
            let ty = python_field_type(&col.sql_type, col.nullable, contract, config);
            writeln!(src, "    {}: {}", col.name, ty)?;
        }

        let path = PathBuf::from(&config.out).join(format!("{}.py", table.name));
        files.push(GeneratedFile { path, content: src });
    }

    let groups = group_queries(queries);
    let mut group_stems: Vec<String> = Vec::new();
    for (group, group_queries) in &groups {
        let stem = queries_file_stem(group).to_string();
        group_stems.push(stem.clone());
        let src = build_queries_file(group, group_queries, schema, contract, config)?;
        let path = PathBuf::from(&config.out).join(format!("{stem}.py"));
        files.push(GeneratedFile { path, content: src });
    }

    let mut src = String::new();
    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    for table in &schema.tables {
        let class_name = to_pascal_case(&table.name);
        writeln!(src, "from .{} import {}", table.name, class_name)?;
    }
    for stem in &group_stems {
        writeln!(src, "from . import {stem}")?;
    }

    let path = PathBuf::from(&config.out).join("__init__.py");
    files.push(GeneratedFile { path, content: src });

    Ok(files)
}

fn build_queries_file(group: &str, queries: &[Query], schema: &Schema, contract: &PythonCoreContract, config: &OutputConfig) -> anyhow::Result<String> {
    let strategy = config.list_params.clone().unwrap_or_default();
    let mut src = String::new();

    let any_inline_rows = queries.iter().any(|q| has_inline_rows(q, schema));

    let mut imports = TypeImports::default();
    for query in queries {
        for p in &query.params {
            imports.scan_param(&p.sql_type, config);
        }
        for col in &query.result_columns {
            imports.scan_field(&col.sql_type, config);
        }
    }

    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    writeln!(src, "{}", contract.runtime.runtime_banner)?;
    writeln!(src, "from __future__ import annotations")?;
    writeln!(src)?;
    if any_inline_rows {
        writeln!(src, "import dataclasses")?;
    }
    writeln!(src, "{}", contract.runtime.db_import)?;
    writeln!(src, "from collections.abc import Callable")?;
    writeln!(src, "from contextlib import closing")?;
    writeln!(src, "from ._sqltgen import execute, exec_stmt")?;
    imports.write(&mut src)?;
    if let Some(json_import) = contract.sql.json_param_import {
        let needs_json_wrap = queries.iter().any(|q| q.params.iter().any(|p| matches!(p.sql_type, SqlType::Json | SqlType::Jsonb)));
        if needs_json_wrap {
            writeln!(src, "{json_import}")?;
        }
    }
    writeln!(src)?;
    writeln!(src, "Connection = {}", contract.runtime.conn_type_expr)?;

    // Emit driver-specific field read converters when any result column needs one.
    let needed_converters: Vec<&FieldReadConverter> =
        contract.field_read_converters.iter().filter(|conv| queries.iter().any(|q| q.result_columns.iter().any(|col| col.sql_type == conv.sql_type))).collect();
    for conv in &needed_converters {
        writeln!(src)?;
        writeln!(src)?;
        write!(src, "{}", conv.fn_body)?;
    }

    let mut needed_tables: BTreeSet<&str> = BTreeSet::new();
    for query in queries {
        if let Some(table_name) = infer_table(query, schema) {
            needed_tables.insert(table_name);
        }
    }
    if !needed_tables.is_empty() {
        writeln!(src)?;
        for table_name in &needed_tables {
            let class_name = to_pascal_case(table_name);
            writeln!(src, "from .{table_name} import {class_name}")?;
        }
    }

    writeln!(src)?;
    for query in queries {
        if query.params.iter().any(|p| p.is_list) && strategy == ListParamStrategy::Dynamic {
            continue;
        }
        let const_name = sql_const_name(&query.name);
        let base_sql = if let Some(lp) = query.params.iter().find(|p| p.is_list) {
            lp.native_list_sql.clone().unwrap_or_else(|| query.sql.clone())
        } else {
            query.sql.clone()
        };
        let sql = normalize_sql(&base_sql, contract.sql.sql_norm_mode);
        let sql = sql.trim_end().trim_end_matches(';');
        let sql = sql.replace("\"\"\"", "\\\"\\\"\\\"");
        writeln!(src, "{const_name} = \"\"\"\\")?;
        for line in sql.lines() {
            writeln!(src, "{line}")?;
        }
        writeln!(src, "\"\"\"")?;
    }

    for query in queries {
        let ctx = PythonQueryContext { query, schema, contract, config };
        writeln!(src)?;
        writeln!(src)?;
        if has_inline_rows(query, schema) {
            emit_row_dataclass(&mut src, &ctx)?;
            writeln!(src)?;
            writeln!(src)?;
        }
        emit_python_query(&mut src, &ctx, &strategy)?;
    }

    if !queries.is_empty() {
        writeln!(src)?;
        writeln!(src)?;
        emit_python_querier(&mut src, group, queries, schema, contract, config)?;
    }

    Ok(src)
}

fn emit_python_querier(
    src: &mut String,
    group: &str,
    queries: &[Query],
    schema: &Schema,
    contract: &PythonCoreContract,
    config: &OutputConfig,
) -> anyhow::Result<()> {
    let class_name = querier_class_name(group);
    let conn_type = "Connection";
    writeln!(src, "class {class_name}:")?;
    writeln!(src, "    def __init__(self, connect: Callable[[], {conn_type}]) -> None:")?;
    writeln!(src, "        self._connect = connect")?;

    for query in queries {
        writeln!(src)?;
        let fn_name = to_snake_case(&query.name);
        let return_type = cursor_return_type(query, schema);
        let params_sig = query
            .params
            .iter()
            .map(|p| {
                let ty = if p.is_list {
                    format!("list[{}]", python_param_type_resolved(&p.sql_type, false, contract, config))
                } else {
                    python_param_type_resolved(&p.sql_type, p.nullable, contract, config)
                };
                format!("{}: {ty}", to_snake_case(&p.name))
            })
            .collect::<Vec<_>>()
            .join(", ");
        let args = query.params.iter().map(|p| to_snake_case(&p.name)).collect::<Vec<_>>().join(", ");

        let params_part = if params_sig.is_empty() { String::new() } else { format!(", {params_sig}") };
        writeln!(src, "    def {fn_name}(self{params_part}) -> {return_type}:")?;

        writeln!(src, "        with closing(self._connect()) as conn:")?;
        if args.is_empty() {
            writeln!(src, "            return {fn_name}(conn)")?;
        } else {
            writeln!(src, "            return {fn_name}(conn, {args})")?;
        }
    }

    Ok(())
}

fn emit_row_dataclass(src: &mut String, ctx: &PythonQueryContext) -> anyhow::Result<()> {
    let name = row_type_name(&ctx.query.name);
    writeln!(src, "@dataclasses.dataclass")?;
    writeln!(src, "class {name}:")?;
    for col in &ctx.query.result_columns {
        let ty = python_field_type(&col.sql_type, col.nullable, ctx.contract, ctx.config);
        writeln!(src, "    {}: {}", col.name, ty)?;
    }
    Ok(())
}

fn emit_python_query(src: &mut String, ctx: &PythonQueryContext, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = ctx.query.params.iter().find(|p| p.is_list) {
        return emit_python_list_query(src, ctx, strategy, lp);
    }
    emit_standard_query(src, ctx)
}

fn emit_standard_query(src: &mut String, ctx: &PythonQueryContext) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&ctx.query.name);
    let const_name = sql_const_name(&ctx.query.name);
    let return_type = cursor_return_type(ctx.query, ctx.schema);
    let conn_type = "Connection";

    let params_sig: String = std::iter::once(format!("conn: {conn_type}"))
        .chain(
            ctx.query
                .params
                .iter()
                .map(|p| format!("{}: {}", to_snake_case(&p.name), python_param_type_resolved(&p.sql_type, p.nullable, ctx.contract, ctx.config))),
        )
        .collect::<Vec<_>>()
        .join(", ");

    let args = build_helper_args(&const_name, ctx.query, ctx.contract.sql.json_param_wrapper);
    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;
    if ctx.query.cmd == QueryCmd::Exec {
        writeln!(src, "    exec_stmt({args})")?;
    } else {
        writeln!(src, "    with execute({args}) as cur:")?;
        emit_python_result_block(src, ctx, "cur", "        ")?;
    }
    Ok(())
}

fn emit_python_list_query(src: &mut String, ctx: &PythonQueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&ctx.query.name);
    let const_name = sql_const_name(&ctx.query.name);
    let conn_type = "Connection";
    let return_type = cursor_return_type(ctx.query, ctx.schema);
    let lp_name = to_snake_case(&lp.name);
    let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();

    let params_sig: String = std::iter::once(format!("conn: {conn_type}"))
        .chain(ctx.query.params.iter().map(|p| {
            let ty = if p.is_list {
                format!("list[{}]", python_param_type_resolved(&p.sql_type, false, ctx.contract, ctx.config))
            } else {
                python_param_type_resolved(&p.sql_type, p.nullable, ctx.contract, ctx.config)
            };
            format!("{}: {ty}", to_snake_case(&p.name))
        }))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;

    match strategy {
        ListParamStrategy::Native => match &lp.native_list_bind {
            Some(NativeListBind::Array) => {
                let scalar_args = build_scalar_args(&scalar_params, lp, &lp_name);
                emit_list_body(src, ctx, &format!("conn, {const_name}, {scalar_args}"))?;
            },
            Some(NativeListBind::Json) | None => {
                writeln!(src, "    import json")?;
                writeln!(src, "    {lp_name}_json = json.dumps({lp_name})")?;
                let scalar_args = build_scalar_args(&scalar_params, lp, &format!("{lp_name}_json"));
                emit_list_body(src, ctx, &format!("conn, {const_name}, {scalar_args}"))?;
            },
        },
        ListParamStrategy::Dynamic => {
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = normalize_sql(&before_raw, ctx.contract.sql.sql_norm_mode).replace('"', "\\\"").replace('\n', " ");
            let after = normalize_sql(&after_raw, ctx.contract.sql.sql_norm_mode).replace('"', "\\\"").replace('\n', " ");
            let args_expr = build_dynamic_args(&scalar_params, lp);
            writeln!(src, "    placeholders = \", \".join([\"{}\"] * len({lp_name}))", ctx.contract.sql.dynamic_placeholder_token)?;
            writeln!(src, "    sql = f\"{before}IN ({{placeholders}}){after}\"")?;
            emit_list_body(src, ctx, &format!("conn, sql, {args_expr}"))?;
        },
    }

    Ok(())
}

fn emit_list_body(src: &mut String, ctx: &PythonQueryContext, helper_args: &str) -> anyhow::Result<()> {
    if ctx.query.cmd == QueryCmd::Exec {
        writeln!(src, "    exec_stmt({helper_args})")?;
    } else {
        writeln!(src, "    with execute({helper_args}) as cur:")?;
        emit_python_result_block(src, ctx, "cur", "        ")?;
    }
    Ok(())
}

fn emit_python_result_block(src: &mut String, ctx: &PythonQueryContext, cursor: &str, indent: &str) -> anyhow::Result<()> {
    let converters = ctx.contract.field_read_converters;
    match ctx.query.cmd {
        QueryCmd::Exec => {},
        QueryCmd::ExecRows => writeln!(src, "{indent}return {cursor}.rowcount")?,
        QueryCmd::One => {
            let row_type = result_row_type(ctx.query, ctx.schema);
            let expr = build_row_expr(&row_type, "row", &ctx.query.result_columns, converters);
            writeln!(src, "{indent}row = {cursor}.fetchone()")?;
            writeln!(src, "{indent}if row is None:")?;
            writeln!(src, "{indent}    return None")?;
            writeln!(src, "{indent}return {expr}")?;
        },
        QueryCmd::Many => {
            let row_type = result_row_type(ctx.query, ctx.schema);
            let expr = build_row_expr(&row_type, "row", &ctx.query.result_columns, converters);
            writeln!(src, "{indent}return [{expr} for row in {cursor}.fetchall()]")?;
        },
    }
    Ok(())
}

fn build_scalar_args(scalar_params: &[&Parameter], lp: &Parameter, lp_expr: &str) -> String {
    let mut args: Vec<String> = scalar_params.iter().map(|p| to_snake_case(&p.name)).collect();
    let insert_pos = scalar_params.iter().filter(|p| p.index < lp.index).count();
    args.insert(insert_pos, lp_expr.to_string());
    build_arg_tuple(&args)
}

fn build_arg_tuple(args: &[String]) -> String {
    match args.len() {
        0 => "()".to_string(),
        1 => format!("({},)", args[0]),
        _ => format!("({})", args.join(", ")),
    }
}

fn build_dynamic_args(scalar_params: &[&Parameter], lp: &Parameter) -> String {
    let lp_name = to_snake_case(&lp.name);
    let before: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_snake_case(&p.name)).collect();
    let after: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_snake_case(&p.name)).collect();
    let before_tuple = build_arg_tuple(&before);
    let after_tuple = build_arg_tuple(&after);
    match (before.is_empty(), after.is_empty()) {
        (true, true) => format!("tuple({lp_name})"),
        (false, true) => format!("{before_tuple} + tuple({lp_name})"),
        (true, false) => format!("tuple({lp_name}) + {after_tuple}"),
        (false, false) => format!("{before_tuple} + tuple({lp_name}) + {after_tuple}"),
    }
}

fn build_helper_args(const_name: &str, query: &Query, json_wrapper: Option<&str>) -> String {
    if query.params.is_empty() {
        return format!("conn, {const_name}");
    }
    let bind_names = positional_bind_names(query);
    let args: Vec<String> = bind_names
        .iter()
        .map(|&name| {
            let sql_type = query.params.iter().find(|p| p.name == name).map(|p| &p.sql_type);
            let snake = to_snake_case(name);
            if let Some(ty) = sql_type {
                wrap_json_param(&snake, ty, json_wrapper)
            } else {
                snake
            }
        })
        .collect();
    let tuple = build_arg_tuple(&args);
    format!("conn, {const_name}, {tuple}")
}

/// Find the read converter for a SQL type, if any.
fn find_converter<'a>(sql_type: &SqlType, converters: &'a [FieldReadConverter]) -> Option<&'a FieldReadConverter> {
    converters.iter().find(|c| c.sql_type == *sql_type)
}

/// Build a row construction expression, applying read converters where needed.
///
/// When no converters apply, returns `RowType(*row)`. When converters are needed,
/// returns indexed access like `RowType(row[0], _to_time(row[1]), row[2])`.
fn build_row_expr(row_type: &str, row_var: &str, columns: &[crate::ir::ResultColumn], converters: &[FieldReadConverter]) -> String {
    let any_converted = columns.iter().any(|col| find_converter(&col.sql_type, converters).is_some());
    if !any_converted {
        return format!("{row_type}(*{row_var})");
    }
    let args: Vec<String> = columns
        .iter()
        .enumerate()
        .map(|(i, col)| {
            let raw = format!("{row_var}[{i}]");
            if let Some(conv) = find_converter(&col.sql_type, converters) {
                format!("{}({raw})", conv.fn_name)
            } else {
                raw
            }
        })
        .collect();
    format!("{row_type}({})", args.join(", "))
}

/// Wrap a parameter expression with the JSON adapter if the type is Json/Jsonb.
fn wrap_json_param(expr: &str, sql_type: &SqlType, json_wrapper: Option<&str>) -> String {
    if let Some(wrapper) = json_wrapper {
        if matches!(sql_type, SqlType::Json | SqlType::Jsonb) {
            return wrapper.replace("{value}", expr);
        }
    }
    expr.to_string()
}

fn cursor_return_type(query: &Query, schema: &Schema) -> String {
    match query.cmd {
        QueryCmd::One => format!("{} | None", result_row_type(query, schema)),
        QueryCmd::Many => format!("list[{}]", result_row_type(query, schema)),
        QueryCmd::Exec => "None".to_string(),
        QueryCmd::ExecRows => "int".to_string(),
    }
}

#[cfg(test)]
pub(super) fn python_type_for_target(sql_type: &SqlType, nullable: bool, target: &PythonTarget) -> String {
    let json_mode = match target {
        PythonTarget::Postgres => PythonJsonMode::Object,
        PythonTarget::Sqlite | PythonTarget::Mysql => PythonJsonMode::Text,
    };
    python_type_with_json_mode(sql_type, nullable, json_mode)
}

fn python_type_with_json_mode(sql_type: &SqlType, nullable: bool, json_mode: PythonJsonMode) -> String {
    let base = match sql_type {
        SqlType::Boolean => "bool".to_string(),
        SqlType::SmallInt | SqlType::Integer | SqlType::BigInt => "int".to_string(),
        SqlType::Real | SqlType::Double => "float".to_string(),
        SqlType::Decimal => "decimal.Decimal".to_string(),
        SqlType::Text | SqlType::Char(_) | SqlType::VarChar(_) => "str".to_string(),
        SqlType::Bytes => "bytes".to_string(),
        SqlType::Date => "datetime.date".to_string(),
        SqlType::Time => "datetime.time".to_string(),
        SqlType::Timestamp | SqlType::TimestampTz => "datetime.datetime".to_string(),
        SqlType::Interval => "datetime.timedelta".to_string(),
        SqlType::Uuid => "uuid.UUID".to_string(),
        SqlType::Json | SqlType::Jsonb => match json_mode {
            PythonJsonMode::Object => "object".to_string(),
            PythonJsonMode::Text => "str".to_string(),
        },
        SqlType::Array(inner) => {
            let inner_ty = python_type_with_json_mode(inner, false, json_mode);
            let list_ty = format!("list[{inner_ty}]");
            return if nullable { format!("{list_ty} | None") } else { list_ty };
        },
        SqlType::Custom(_) => "Any".to_string(),
    };
    if nullable {
        format!("{base} | None")
    } else {
        base
    }
}

#[derive(Default)]
struct TypeImports {
    decimal: bool,
    datetime: bool,
    uuid: bool,
    any_type: bool,
    extra: BTreeSet<String>,
}

impl TypeImports {
    fn scan(&mut self, ty: &SqlType) {
        match ty {
            SqlType::Decimal => self.decimal = true,
            SqlType::Date | SqlType::Time | SqlType::Timestamp | SqlType::TimestampTz | SqlType::Interval => self.datetime = true,
            SqlType::Uuid => self.uuid = true,
            SqlType::Json | SqlType::Jsonb => {},
            SqlType::Custom(_) => self.any_type = true,
            SqlType::Array(inner) => self.scan(inner),
            _ => {},
        }
    }

    fn scan_field(&mut self, sql_type: &SqlType, config: &OutputConfig) {
        if let Some(resolved) = get_type_override_python(sql_type, TypeVariant::Field, config) {
            if let Some(import) = resolved.import {
                self.extra.insert(import);
            }
        } else {
            self.scan(sql_type);
        }
    }

    fn scan_param(&mut self, sql_type: &SqlType, config: &OutputConfig) {
        if let Some(resolved) = get_type_override_python(sql_type, TypeVariant::Param, config) {
            if let Some(import) = resolved.import {
                self.extra.insert(import);
            }
        } else {
            self.scan(sql_type);
        }
    }

    fn write(&self, src: &mut String) -> anyhow::Result<()> {
        if self.decimal {
            writeln!(src, "import decimal")?;
        }
        if self.datetime {
            writeln!(src, "import datetime")?;
        }
        if self.uuid {
            writeln!(src, "import uuid")?;
        }
        if self.any_type {
            writeln!(src, "from typing import Any")?;
        }
        for import in &self.extra {
            writeln!(src, "{import}")?;
        }
        Ok(())
    }
}

fn normalize_sql(sql: &str, mode: PythonSqlNormMode) -> String {
    match mode {
        PythonSqlNormMode::PercentS => rewrite_to_percent_s(sql),
        PythonSqlNormMode::AnonParams => rewrite_to_anon_params(sql),
    }
}

fn result_row_type(query: &Query, schema: &Schema) -> String {
    infer_row_type_name(query, schema).unwrap_or_else(|| "Any".to_string())
}
