use std::collections::BTreeSet;
use std::fmt::Write;
use std::path::PathBuf;

use crate::backend::common::{
    group_queries, has_inline_rows, infer_row_type_name, infer_table, model_file_stem, model_name, needed_enums, querier_class_name, queries_file_stem,
    row_type_name, sql_const_name,
};
use crate::backend::naming::{to_pascal_case, to_screaming_snake_case, to_snake_case};
use crate::backend::sql_rewrite::{positional_bind_names, rewrite_to_anon_params, rewrite_to_percent_s, split_at_in_clause};
use crate::backend::GeneratedFile;
use crate::config::{ListParamStrategy, OutputConfig};
use crate::ir::{EnumType, NativeListBind, Parameter, Query, QueryCmd, Schema, SqlType};

use super::adapter::{FieldReadConverter, PythonCoreContract, PythonSqlNormMode};
use super::typemap::PythonTypeMap;

#[cfg(test)]
use super::PythonTarget;

/// All data needed for a single `generate()` call, bundled to reduce parameter threading.
pub(super) struct GenerationContext<'a> {
    pub schema: &'a Schema,
    pub queries: &'a [Query],
    pub config: &'a OutputConfig,
    pub contract: &'a PythonCoreContract,
    pub type_map: &'a PythonTypeMap,
    pub strategy: ListParamStrategy,
}

/// Per-query context forwarded to all emitters within a queries file.
struct PythonQueryContext<'a> {
    query: &'a Query,
    schema: &'a Schema,
    contract: &'a PythonCoreContract,
    type_map: &'a PythonTypeMap,
}

/// Emit all Python files except the helper module.
pub(super) fn generate_core_files(ctx: &GenerationContext) -> anyhow::Result<Vec<GeneratedFile>> {
    let mut files = Vec::new();

    let ds = ctx.schema.default_schema.as_deref();
    for table in &ctx.schema.tables {
        let class_name = model_name(table, ds);
        let file_stem = model_file_stem(table, ds);
        let mut src = String::new();
        writeln!(src, "# Generated by sqltgen. Do not edit.")?;
        writeln!(src, "from __future__ import annotations")?;
        writeln!(src)?;
        writeln!(src, "import dataclasses")?;

        let mut imports = TypeImports::default();
        for col in &table.columns {
            imports.add(ctx.type_map.import_for(&col.sql_type));
        }
        imports.write(&mut src)?;

        // Import any enum types referenced by this table's columns.
        let mut enum_imports: BTreeSet<String> = BTreeSet::new();
        for col in &table.columns {
            crate::backend::common::collect_enum_names_from_type(&col.sql_type, &mut enum_imports);
        }
        for name in &enum_imports {
            writeln!(src, "from .{name} import {}", to_pascal_case(name))?;
        }

        writeln!(src)?;
        writeln!(src)?;
        writeln!(src, "@dataclasses.dataclass")?;
        writeln!(src, "class {class_name}:")?;
        for col in &table.columns {
            let ty = ctx.type_map.field_type(&col.sql_type, col.nullable);
            writeln!(src, "    {}: {}", col.name, ty)?;
        }

        let path = PathBuf::from(&ctx.config.out).join("models").join(format!("{file_stem}.py"));
        files.push(GeneratedFile { path, content: src });
    }

    for e in &ctx.schema.enums {
        let mut src = String::new();
        emit_python_enum(&mut src, e)?;
        let path = PathBuf::from(&ctx.config.out).join("models").join(format!("{}.py", e.name));
        files.push(GeneratedFile { path, content: src });
    }

    let groups = group_queries(ctx.queries);
    let mut group_stems: Vec<String> = Vec::new();
    for (group, group_queries) in &groups {
        let stem = queries_file_stem(group).to_string();
        group_stems.push(stem.clone());
        let src = build_queries_file(ctx, group, group_queries)?;
        let path = PathBuf::from(&ctx.config.out).join("queries").join(format!("{stem}.py"));
        files.push(GeneratedFile { path, content: src });
    }

    if !ctx.schema.tables.is_empty() || !ctx.schema.enums.is_empty() {
        let mut src = String::new();
        writeln!(src, "# Generated by sqltgen. Do not edit.")?;
        for table in &ctx.schema.tables {
            let class_name = model_name(table, ds);
            let file_stem = model_file_stem(table, ds);
            writeln!(src, "from .{file_stem} import {class_name}")?;
        }
        for e in &ctx.schema.enums {
            let class_name = to_pascal_case(&e.name);
            writeln!(src, "from .{} import {}", e.name, class_name)?;
        }
        let path = PathBuf::from(&ctx.config.out).join("models").join("__init__.py");
        files.push(GeneratedFile { path, content: src });
    }

    if !group_stems.is_empty() {
        let mut src = String::new();
        writeln!(src, "# Generated by sqltgen. Do not edit.")?;
        for stem in &group_stems {
            writeln!(src, "from . import {stem}")?;
        }
        let path = PathBuf::from(&ctx.config.out).join("queries").join("__init__.py");
        files.push(GeneratedFile { path, content: src });
    }

    let mut src = String::new();
    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    if !ctx.schema.tables.is_empty() || !ctx.schema.enums.is_empty() {
        writeln!(src, "from . import models")?;
    }
    if !group_stems.is_empty() {
        writeln!(src, "from . import queries")?;
    }
    let path = PathBuf::from(&ctx.config.out).join("__init__.py");
    files.push(GeneratedFile { path, content: src });

    Ok(files)
}

fn build_queries_file(ctx: &GenerationContext, group: &str, queries: &[Query]) -> anyhow::Result<String> {
    let ds = ctx.schema.default_schema.as_deref();
    let mut src = String::new();

    let any_inline_rows = queries.iter().any(|q| has_inline_rows(q, ctx.schema));

    let mut imports = TypeImports::default();
    for query in queries {
        for p in &query.params {
            imports.add(ctx.type_map.import_for(&p.sql_type));
        }
        for col in &query.result_columns {
            imports.add(ctx.type_map.import_for(&col.sql_type));
        }
    }

    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    writeln!(src, "{}", ctx.contract.runtime.runtime_banner)?;
    writeln!(src, "from __future__ import annotations")?;
    writeln!(src)?;
    if any_inline_rows {
        writeln!(src, "import dataclasses")?;
    }
    writeln!(src, "{}", ctx.contract.runtime.db_import)?;
    writeln!(src, "from collections.abc import Callable")?;
    writeln!(src, "from contextlib import closing")?;
    let needs_enum_array_parser =
        queries.iter().any(|q| q.result_columns.iter().any(|col| matches!(&col.sql_type, SqlType::Array(inner) if matches!(inner.as_ref(), SqlType::Enum(_)))));
    if needs_enum_array_parser {
        writeln!(src, "from ..sqltgen import execute, exec_stmt, _parse_enum_array")?;
    } else {
        writeln!(src, "from ..sqltgen import execute, exec_stmt")?;
    }
    imports.write(&mut src)?;
    if let Some(json_import) = ctx.contract.sql.json_param_import {
        let needs_json = queries.iter().any(|q| {
            q.params.iter().any(|p| matches!(p.sql_type, SqlType::Json | SqlType::Jsonb))
                || q.result_columns.iter().any(|c| matches!(c.sql_type, SqlType::Json | SqlType::Jsonb))
        });
        if needs_json {
            writeln!(src, "{json_import}")?;
        }
    }
    writeln!(src)?;
    writeln!(src, "Connection = {}", ctx.contract.runtime.conn_type_expr)?;

    // Emit driver-specific field read converters when any result column needs one.
    let needed_converters: Vec<&FieldReadConverter> = ctx
        .contract
        .field_read_converters
        .iter()
        .filter(|conv| queries.iter().any(|q| q.result_columns.iter().any(|col| col.sql_type == conv.sql_type)))
        .collect();
    for conv in &needed_converters {
        writeln!(src)?;
        writeln!(src)?;
        write!(src, "{}", conv.fn_body)?;
    }

    let mut needed_tables: Vec<_> = queries.iter().filter_map(|q| infer_table(q, ctx.schema)).collect();
    needed_tables.sort_by_key(|t| &t.name);
    needed_tables.dedup_by_key(|t| &t.name);
    let enum_names = needed_enums(&queries.iter().collect::<Vec<_>>());
    if !needed_tables.is_empty() || !enum_names.is_empty() {
        writeln!(src)?;
        for table in &needed_tables {
            let class_name = model_name(table, ds);
            let file_stem = model_file_stem(table, ds);
            writeln!(src, "from ..models.{file_stem} import {class_name}")?;
        }
        for name in &enum_names {
            writeln!(src, "from ..models.{name} import {}", to_pascal_case(name))?;
        }
    }

    writeln!(src)?;
    for query in queries {
        if query.params.iter().any(|p| p.is_list) && ctx.strategy == ListParamStrategy::Dynamic {
            continue;
        }
        let const_name = sql_const_name(&query.name);
        let base_sql = if let Some(lp) = query.params.iter().find(|p| p.is_list) {
            lp.native_list_sql.clone().unwrap_or_else(|| query.sql.clone())
        } else {
            query.sql.clone()
        };
        let sql = normalize_sql(&base_sql, ctx.contract.sql.sql_norm_mode);
        let sql = sql.trim_end().trim_end_matches(';');
        let sql = sql.replace("\"\"\"", "\\\"\\\"\\\"");
        writeln!(src, "{const_name} = \"\"\"\\")?;
        for line in sql.lines() {
            writeln!(src, "{line}")?;
        }
        writeln!(src, "\"\"\"")?;
    }

    for query in queries {
        let qctx = PythonQueryContext { query, schema: ctx.schema, contract: ctx.contract, type_map: ctx.type_map };
        writeln!(src)?;
        writeln!(src)?;
        if has_inline_rows(query, ctx.schema) {
            emit_row_dataclass(&mut src, &qctx)?;
            writeln!(src)?;
            writeln!(src)?;
        }
        emit_python_query(&mut src, &qctx, &ctx.strategy)?;
    }

    if !queries.is_empty() {
        writeln!(src)?;
        writeln!(src)?;
        emit_python_querier(&mut src, group, queries, ctx)?;
    }

    Ok(src)
}

fn emit_python_querier(src: &mut String, group: &str, queries: &[Query], ctx: &GenerationContext) -> anyhow::Result<()> {
    let class_name = querier_class_name(group);
    let conn_type = "Connection";
    writeln!(src, "class {class_name}:")?;
    writeln!(src, "    def __init__(self, connect: Callable[[], {conn_type}]) -> None:")?;
    writeln!(src, "        self._connect = connect")?;

    for query in queries {
        writeln!(src)?;
        let fn_name = to_snake_case(&query.name);
        let return_type = cursor_return_type(query, ctx.schema);
        let params_sig = query
            .params
            .iter()
            .map(|p| {
                let ty =
                    if p.is_list { format!("list[{}]", ctx.type_map.param_type(&p.sql_type, false)) } else { ctx.type_map.param_type(&p.sql_type, p.nullable) };
                format!("{}: {ty}", to_snake_case(&p.name))
            })
            .collect::<Vec<_>>()
            .join(", ");
        let args = query.params.iter().map(|p| to_snake_case(&p.name)).collect::<Vec<_>>().join(", ");

        let params_part = if params_sig.is_empty() { String::new() } else { format!(", {params_sig}") };
        writeln!(src, "    def {fn_name}(self{params_part}) -> {return_type}:")?;

        writeln!(src, "        with closing(self._connect()) as conn:")?;
        if args.is_empty() {
            writeln!(src, "            return {fn_name}(conn)")?;
        } else {
            writeln!(src, "            return {fn_name}(conn, {args})")?;
        }
    }

    Ok(())
}

fn emit_row_dataclass(src: &mut String, ctx: &PythonQueryContext) -> anyhow::Result<()> {
    let name = row_type_name(&ctx.query.name);
    writeln!(src, "@dataclasses.dataclass")?;
    writeln!(src, "class {name}:")?;
    for col in &ctx.query.result_columns {
        let ty = ctx.type_map.field_type(&col.sql_type, col.nullable);
        writeln!(src, "    {}: {}", col.name, ty)?;
    }
    Ok(())
}

fn emit_python_query(src: &mut String, ctx: &PythonQueryContext, strategy: &ListParamStrategy) -> anyhow::Result<()> {
    if let Some(lp) = ctx.query.params.iter().find(|p| p.is_list) {
        return emit_python_list_query(src, ctx, strategy, lp);
    }
    emit_standard_query(src, ctx)
}

fn emit_standard_query(src: &mut String, ctx: &PythonQueryContext) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&ctx.query.name);
    let const_name = sql_const_name(&ctx.query.name);
    let return_type = cursor_return_type(ctx.query, ctx.schema);
    let conn_type = "Connection";

    let params_sig: String = std::iter::once(format!("conn: {conn_type}"))
        .chain(ctx.query.params.iter().map(|p| format!("{}: {}", to_snake_case(&p.name), ctx.type_map.param_type(&p.sql_type, p.nullable))))
        .collect::<Vec<_>>()
        .join(", ");

    let args = build_helper_args(&const_name, ctx.query, ctx.contract.sql.json_param_wrapper);
    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;
    if ctx.query.cmd == QueryCmd::Exec {
        writeln!(src, "    exec_stmt({args})")?;
    } else {
        writeln!(src, "    with execute({args}) as cur:")?;
        emit_python_result_block(src, ctx, "cur", "        ")?;
    }
    Ok(())
}

fn emit_python_list_query(src: &mut String, ctx: &PythonQueryContext, strategy: &ListParamStrategy, lp: &Parameter) -> anyhow::Result<()> {
    let fn_name = to_snake_case(&ctx.query.name);
    let const_name = sql_const_name(&ctx.query.name);
    let conn_type = "Connection";
    let return_type = cursor_return_type(ctx.query, ctx.schema);
    let lp_name = to_snake_case(&lp.name);
    let scalar_params: Vec<&Parameter> = ctx.query.params.iter().filter(|p| !p.is_list).collect();

    let params_sig: String = std::iter::once(format!("conn: {conn_type}"))
        .chain(ctx.query.params.iter().map(|p| {
            let ty =
                if p.is_list { format!("list[{}]", ctx.type_map.param_type(&p.sql_type, false)) } else { ctx.type_map.param_type(&p.sql_type, p.nullable) };
            format!("{}: {ty}", to_snake_case(&p.name))
        }))
        .collect::<Vec<_>>()
        .join(", ");

    writeln!(src, "def {fn_name}({params_sig}) -> {return_type}:")?;

    match strategy {
        ListParamStrategy::Native => match &lp.native_list_bind {
            Some(NativeListBind::Array) => {
                let scalar_args = build_scalar_args(&scalar_params, lp, &lp_name);
                emit_list_body(src, ctx, &format!("conn, {const_name}, {scalar_args}"))?;
            },
            Some(NativeListBind::Json) | None => {
                writeln!(src, "    import json")?;
                writeln!(src, "    {lp_name}_json = json.dumps({lp_name})")?;
                let scalar_args = build_scalar_args(&scalar_params, lp, &format!("{lp_name}_json"));
                emit_list_body(src, ctx, &format!("conn, {const_name}, {scalar_args}"))?;
            },
        },
        ListParamStrategy::Dynamic => {
            let (before_raw, after_raw) = split_at_in_clause(&ctx.query.sql, lp.index).unwrap_or_else(|| (ctx.query.sql.clone(), String::new()));
            let before = normalize_sql(&before_raw, ctx.contract.sql.sql_norm_mode).replace('"', "\\\"").replace('\n', " ");
            let after = normalize_sql(&after_raw, ctx.contract.sql.sql_norm_mode).replace('"', "\\\"").replace('\n', " ");
            let args_expr = build_dynamic_args(&scalar_params, lp);
            writeln!(src, "    placeholders = \", \".join([\"{}\"] * len({lp_name}))", ctx.contract.sql.dynamic_placeholder_token)?;
            writeln!(src, "    sql = f\"{before}IN ({{placeholders}}){after}\"")?;
            emit_list_body(src, ctx, &format!("conn, sql, {args_expr}"))?;
        },
    }

    Ok(())
}

fn emit_list_body(src: &mut String, ctx: &PythonQueryContext, helper_args: &str) -> anyhow::Result<()> {
    if ctx.query.cmd == QueryCmd::Exec {
        writeln!(src, "    exec_stmt({helper_args})")?;
    } else {
        writeln!(src, "    with execute({helper_args}) as cur:")?;
        emit_python_result_block(src, ctx, "cur", "        ")?;
    }
    Ok(())
}

fn emit_python_result_block(src: &mut String, ctx: &PythonQueryContext, cursor: &str, indent: &str) -> anyhow::Result<()> {
    let converters = ctx.contract.field_read_converters;
    match ctx.query.cmd {
        QueryCmd::Exec => {},
        QueryCmd::ExecRows => writeln!(src, "{indent}return {cursor}.rowcount")?,
        QueryCmd::One => {
            let row_type = result_row_type(ctx.query, ctx.schema);
            let expr = build_row_expr(&row_type, "row", &ctx.query.result_columns, converters);
            writeln!(src, "{indent}row = {cursor}.fetchone()")?;
            writeln!(src, "{indent}if row is None:")?;
            writeln!(src, "{indent}    return None")?;
            writeln!(src, "{indent}return {expr}")?;
        },
        QueryCmd::Many => {
            let row_type = result_row_type(ctx.query, ctx.schema);
            let expr = build_row_expr(&row_type, "row", &ctx.query.result_columns, converters);
            writeln!(src, "{indent}return [{expr} for row in {cursor}.fetchall()]")?;
        },
    }
    Ok(())
}

fn build_scalar_args(scalar_params: &[&Parameter], lp: &Parameter, lp_expr: &str) -> String {
    let mut args: Vec<String> = scalar_params.iter().map(|p| to_snake_case(&p.name)).collect();
    let insert_pos = scalar_params.iter().filter(|p| p.index < lp.index).count();
    args.insert(insert_pos, lp_expr.to_string());
    build_arg_tuple(&args)
}

fn build_arg_tuple(args: &[String]) -> String {
    match args.len() {
        0 => "()".to_string(),
        1 => format!("({},)", args[0]),
        _ => format!("({})", args.join(", ")),
    }
}

fn build_dynamic_args(scalar_params: &[&Parameter], lp: &Parameter) -> String {
    let lp_name = to_snake_case(&lp.name);
    let before: Vec<String> = scalar_params.iter().filter(|p| p.index < lp.index).map(|p| to_snake_case(&p.name)).collect();
    let after: Vec<String> = scalar_params.iter().filter(|p| p.index > lp.index).map(|p| to_snake_case(&p.name)).collect();
    let before_tuple = build_arg_tuple(&before);
    let after_tuple = build_arg_tuple(&after);
    match (before.is_empty(), after.is_empty()) {
        (true, true) => format!("tuple({lp_name})"),
        (false, true) => format!("{before_tuple} + tuple({lp_name})"),
        (true, false) => format!("tuple({lp_name}) + {after_tuple}"),
        (false, false) => format!("{before_tuple} + tuple({lp_name}) + {after_tuple}"),
    }
}

fn build_helper_args(const_name: &str, query: &Query, json_wrapper: Option<&str>) -> String {
    if query.params.is_empty() {
        return format!("conn, {const_name}");
    }
    let bind_names = positional_bind_names(query);
    let args: Vec<String> = bind_names
        .iter()
        .map(|&name| {
            let sql_type = query.params.iter().find(|p| p.name == name).map(|p| &p.sql_type);
            let snake = to_snake_case(name);
            if let Some(ty) = sql_type {
                wrap_json_param(&snake, ty, json_wrapper)
            } else {
                snake
            }
        })
        .collect();
    let tuple = build_arg_tuple(&args);
    format!("conn, {const_name}, {tuple}")
}

/// Find the read converter for a SQL type, if any.
fn find_converter<'a>(sql_type: &SqlType, converters: &'a [FieldReadConverter]) -> Option<&'a FieldReadConverter> {
    converters.iter().find(|c| c.sql_type == *sql_type)
}

/// Build a row construction expression, applying read converters where needed.
///
/// When no converters apply, returns `RowType(*row)`. When converters are needed,
/// returns indexed access like `RowType(row[0], _to_time(row[1]), row[2])`.
///
/// Enum array columns (`Array(Enum(name))`) are handled specially: psycopg3
/// returns them as raw PostgreSQL text like `'{low,medium,high}'`, so they
/// are parsed into `list[EnumClass]` at construction time.
fn build_row_expr(row_type: &str, row_var: &str, columns: &[crate::ir::ResultColumn], converters: &[FieldReadConverter]) -> String {
    let needs_indexed = columns.iter().any(|col| {
        find_converter(&col.sql_type, converters).is_some() || matches!(&col.sql_type, SqlType::Array(inner) if matches!(inner.as_ref(), SqlType::Enum(_)))
    });
    if !needs_indexed {
        return format!("{row_type}(*{row_var})");
    }
    let args: Vec<String> = columns
        .iter()
        .enumerate()
        .map(|(i, col)| {
            let raw = format!("{row_var}[{i}]");
            if let Some(conv) = find_converter(&col.sql_type, converters) {
                format!("{}({raw})", conv.fn_name)
            } else if let SqlType::Array(inner) = &col.sql_type {
                if let SqlType::Enum(name) = inner.as_ref() {
                    let cls = to_pascal_case(name);
                    format!("[{cls}(v) for v in {raw}] if isinstance({raw}, list) else _parse_enum_array({raw}, {cls})")
                } else {
                    raw
                }
            } else {
                raw
            }
        })
        .collect();
    format!("{row_type}({})", args.join(", "))
}

/// Wrap a parameter expression with the JSON adapter if the type is Json/Jsonb.
fn wrap_json_param(expr: &str, sql_type: &SqlType, json_wrapper: Option<&str>) -> String {
    if let Some(wrapper) = json_wrapper {
        if matches!(sql_type, SqlType::Json | SqlType::Jsonb) {
            return wrapper.replace("{value}", expr);
        }
    }
    expr.to_string()
}

fn cursor_return_type(query: &Query, schema: &Schema) -> String {
    match query.cmd {
        QueryCmd::One => format!("{} | None", result_row_type(query, schema)),
        QueryCmd::Many => format!("list[{}]", result_row_type(query, schema)),
        QueryCmd::Exec => "None".to_string(),
        QueryCmd::ExecRows => "int".to_string(),
    }
}

#[cfg(test)]
pub(super) fn python_type_for_target(sql_type: &SqlType, nullable: bool, target: &PythonTarget) -> String {
    let contract = super::adapter::resolve_python_contract(target);
    let type_map = super::typemap::build_python_type_map(&OutputConfig::default(), contract.sql.json_mode);
    type_map.field_type(sql_type, nullable)
}

/// Emit a Python enum class for a SQL enum type.
fn emit_python_enum(src: &mut String, e: &EnumType) -> anyhow::Result<()> {
    let class_name = to_pascal_case(&e.name);
    writeln!(src, "# Generated by sqltgen. Do not edit.")?;
    writeln!(src, "import enum")?;
    writeln!(src)?;
    writeln!(src)?;
    writeln!(src, "class {class_name}(str, enum.Enum):")?;
    for v in &e.variants {
        let variant_name = to_screaming_snake_case(v);
        writeln!(src, "    {variant_name} = \"{v}\"")?;
    }
    Ok(())
}

/// Collected import lines needed for the generated file.
///
/// Deduplicates via a `BTreeSet` so imports are emitted in sorted order.
#[derive(Default)]
struct TypeImports(BTreeSet<String>);

impl TypeImports {
    /// Add an import line if present.
    fn add(&mut self, import: Option<String>) {
        if let Some(imp) = import {
            self.0.insert(imp);
        }
    }

    fn write(&self, src: &mut String) -> anyhow::Result<()> {
        for import in &self.0 {
            writeln!(src, "{import}")?;
        }
        Ok(())
    }
}

fn normalize_sql(sql: &str, mode: PythonSqlNormMode) -> String {
    match mode {
        PythonSqlNormMode::PercentS => rewrite_to_percent_s(sql),
        PythonSqlNormMode::AnonParams => rewrite_to_anon_params(sql),
    }
}

fn result_row_type(query: &Query, schema: &Schema) -> String {
    infer_row_type_name(query, schema).unwrap_or_else(|| "Any".to_string())
}
